### ISSUE TITLE
How to install mmcv-full in CUDA9.0 machine?

### ISSUE THREAD

**Issue by Qianyu666** [open-mmlab/mmcv#1016]
Hello, I have tried to install mmcv-full in the sensetime servers with CUDA9.0 but failed.

Due to the fact the machines of sh34 and sh40 only support CUDA9.0 instead of CUDA 9.2, thus I cannot directly install mmcv-full by pip install. I don't find the suitable versions in your provided link: https://download.openmmlab.com/mmcv/dist/.

I have tried to install mmcv-full from the source.  When I was running MMCV_WITH_OPS=1 pip install -e . 
It comes up with the following errors:
`ERROR: Command errored out with exit status 1:
     command: /mnt/lustre/zhouqianyu/envs/mmlab/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/lustre/zhouqianyu/mycode/mmcv/setup.py'"'"'; __file__='"'"'/mnt/lustre/zhouqianyu/mycode/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-t1tcxvuz
         cwd: /mnt/lustre/zhouqianyu/mycode/mmcv/
    Complete output (25 lines):
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/lustre/zhouqianyu/mycode/mmcv/setup.py", line 317, in <module>
        zip_safe=False)
      File "/mnt/lustre/zhouqianyu/miniconda3/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/mnt/lustre/zhouqianyu/envs/mmlab/lib/python3.7/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/mnt/lustre/zhouqianyu/envs/mmlab/lib/python3.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/mnt/lustre/zhouqianyu/envs/mmlab/lib/python3.7/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/mnt/lustre/zhouqianyu/envs/mmlab/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/mnt/lustre/zhouqianyu/envs/mmlab/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/mnt/lustre/zhouqianyu/envs/mmlab/lib/python3.7/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/mnt/lustre/zhouqianyu/envs/mmlab/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    Compiling mmcv._ext without CUDA
    ----------------------------------------
WARNING: Discarding file:///mnt/lustre/zhouqianyu/mycode/mmcv. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

Could your please help me? I will be appreciated it if you can answer my questions. Thank you in advance!

**Comment by zhouzaida** [comment]
hi, @Qianyu666 , please contact me on sensetime IM

**Comment by sunyuhan19981208** [comment]
how to download mmcv on CUDA9.0?
