### ISSUE TITLE
Installation failed "ninja: build stopped: subcommand failed."

### ISSUE THREAD

**Issue by chenyc1601** [open-mmlab/mmcv#1030]
I've tried both installing from command line and building from source, they all ended up with some error like this: 
```
# many many lines before... #
C:/Users/Administrator/anaconda3/envs/mmcv/lib/site-packages/torch/include\c10/util/Optional.h(418): note: ???????? ?? ?? ???"c10::OptionalBase<c10::impl::InlineStreamGuard<c10::cuda::impl::CUDAGuardImpl>>"???
C:/Users/Administrator/anaconda3/envs/mmcv/lib/site-packages/torch/include\c10/core/impl/InlineStreamGuard.h(184): note: ???????? ? ?? ???"c10::optional<c10::impl::InlineStreamGuard<c10::cuda::impl::CUDAGuardImpl>>"???
C:/Users/Administrator/anaconda3/envs/mmcv/lib/site-packages/torch/include\c10/cuda/CUDAGuard.h(232): note: ???????? ? ?? ???"c10::impl::InlineOptionalStreamGuard<c10::cuda::impl::CUDAGuardImpl>"???
C:/Users/Administrator/anaconda3/envs/mmcv/lib/site-packages/torch/include\c10/util/Optional.h(387): warning C4624: "c10::trivially_copyable_optimization_optional_base<T>": ???????????"???"
        with
        [
            T=c10::impl::InlineStreamGuard<c10::cuda::impl::CUDAGuardImpl>
        ]
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\site-packages\torch\utils\cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '8']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 317, in <module>
    zip_safe=False)
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\site-packages\setuptools\__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\site-packages\torch\utils\cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\site-packages\torch\utils\cpp_extension.py", line 690, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\site-packages\torch\utils\cpp_extension.py", line 1359, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\Administrator\anaconda3\envs\mmcv\lib\site-packages\torch\utils\cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```
System: Windows 10
Python: 3.7.10(conda)
GPU: RTX3090
Driver: 456.81, CUDA: 11.1
Pytorch: 1.8.1, cudatoolkit: 11.1 or Pytorch: 1.7.1, cudatoolkit: 11.0, neither works
Also tried CUDA 10.2 with Pytorch 1.8.1, cudatoolkit 10.2, still not working

**Comment by ZwwWayne** [comment]
What is your compilation command? Please use the error template.

**Comment by chenyc1601** [comment]
@ZwwWayne 
> What is your compilation command? Please use the error template.

I followed exactly the "Build MMCV from source" instruction in the documentation:
1. Setup Python Environment
```bash
conda create --name mmcv python=3.7
conda activate mmcv
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge # this step is copied from pytorch.org
cd mmcv-master # I downloaded the repository instead of pulling it from git
pip3 install -r requirements.txt
```
2. Build and install MMCV
- Add `C:\Program` Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\Hostx86\x64` to PATH; 
- `ls env:` shows the following result: 
```bash
Name                           Value
----                           -----
<... omit some lines ...>
CUDA_PATH                      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
CUDA_PATH_V10_2                C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
CUDA_PATH_V11_1                C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
<... omit some lines ...>
```
- Set CUDA target arch 
```bash
$env:TORCH_CUDA_ARCH_LIST="8.6" # for RTX 3090
```
- Launch compiling
```bash
$env:MMCV_WITH_OPS = 1
$env:MAX_JOBS = 8  # I use a 16-core CPU
python setup.py build_ext
```

Then it failed with the result shown before.

**Comment by jshilong** [comment]
Seems there is a similar issue， you can refer to `windows 10 install mmcv-full error` #789

**Comment by zhouzaida** [comment]
closed for no response
