### ISSUE TITLE
examples/train_cifar10.py can't train

### ISSUE THREAD

**Issue by Physu** [open-mmlab/mmcv#1054]
I notice the example files in example/train_cifar10.py can't train actually.
`Traceback (most recent call last):
  File "/home/lhy/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/lhy/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "examples/train_cifar10.py", line 177, in <module>
    main()
  File "examples/train_cifar10.py", line 157, in main
    log_level=cfg.log_level)
  File "/mnt/disk7/lhy/waymo/mmcv/mmcv/runner/epoch_based_runner.py", line 182, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'log_level'
python-BaseException
`
In order to solve this question, I change "log_level=cfg.log_level" to "logger=cfg.log_level".

But  I got another fault:
`Traceback (most recent call last):
  File "/home/lhy/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/lhy/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "examples/train_cifar10.py", line 177, in <module>
    main()
  File "examples/train_cifar10.py", line 157, in main
    logger=cfg.log_level)
  File "/mnt/disk7/lhy/waymo/mmcv/mmcv/runner/epoch_based_runner.py", line 182, in __init__
    super().__init__(*args, **kwargs)
  File "/mnt/disk7/lhy/waymo/mmcv/mmcv/runner/base_runner.py", line 84, in __init__
    f'optimizer must be a dict of torch.optim.Optimizers, '
TypeError: optimizer must be a dict of torch.optim.Optimizers, but optimizer["type"] is a <class 'str'>
python-BaseException`

In examples/config_cifar10.py we get Optimizer definition, but in examples/train_cifar10.py, I didn't see the initialization of Optimizer, so the Orderdict type data sended to mmcv/runner/epoch_based_runner.py, it is not the "torch.optim.Optimizer" type object.

Could you please tell me how I can fix it and make it work?
Thanks~

**Comment by zhouzaida** [comment]
hi @Physu , thanks for your feedback, I will update it today or tomorrow.

**Comment by Physu** [comment]
Thanks for your attention, thumb up!

**Comment by zhouzaida** [comment]
hi @Physu , please refer to https://github.com/zhouzaida/mmcv/tree/fix-example

**Comment by Physu** [comment]
Thanks a lot, got it!
