### ISSUE TITLE
soft_nms.h:3:10: fatal error: onnxruntime_cxx_api.h: No such file or directory

### ISSUE THREAD

**Issue by BChunlei** [open-mmlab/mmcv#1118]
when i use the command 'MMCV_WITH_OPS=1 MMCV_WITH_ORT=1 MMCV_WITH_TRT=1 pip install -e .' to install mmcv，error occurs:
ERROR: Command errored out with exit status 1:
     command: /root/anaconda3/envs/bcl/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/downloads/mmcv/setup.py'"'"'; __file__='"'"'/root/downloads/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /root/downloads/mmcv/
    Complete output (117 lines):
    running develop
    running egg_info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext_trt' extension
    Emitting ninja build file /root/downloads/mmcv/build/temp.linux-x86_64-3.8/build.ninja...
    Compiling objects...
    Using envvar MAX_JOBS (4) as the number of workers...
    ninja: no work to do.
    g++ -pthread -shared -B /root/anaconda3/envs/bcl/compiler_compat -L/root/anaconda3/envs/bcl/lib -Wl,-rpath=/root/anaconda3/envs/bcl/lib -Wl,--no-as-needed -Wl,--sysroot=/ /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_plugin.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_nms_kernel.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_cummaxmin_kernel.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_modulated_deform_conv.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_deform_conv_kernel.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_cuda_helper.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_scatternd_kernel.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_roi_align.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_instance_norm.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_grid_sampler.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_grid_sampler_kernel.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_cummaxmin.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_roi_align_kernel.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_scatternd.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_nms.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_modulated_deform_conv_kernel.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/tensorrt/plugins/trt_deform_conv.o -L/root/downloads/TensorRT-7.2.3.4/targets/x86_64-linux-gnu/lib -L/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda-10.2/lib64 -lnvinfer -lnvparsers -lnvinfer_plugin -lcudart -o build/lib.linux-x86_64-3.8/mmcv/_ext_trt.cpython-38-x86_64-linux-gnu.so
    building 'mmcv._ext' extension
    Emitting ninja build file /root/downloads/mmcv/build/temp.linux-x86_64-3.8/build.ninja...
    Compiling objects...
    Using envvar MAX_JOBS (4) as the number of workers...
    ninja: no work to do.
    g++ -pthread -shared -B /root/anaconda3/envs/bcl/compiler_compat -L/root/anaconda3/envs/bcl/lib -Wl,-rpath=/root/anaconda3/envs/bcl/lib -Wl,--no-as-needed -Wl,--sysroot=/ /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/modulated_deform_conv_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/nms_rotated.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/pixel_group.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/box_iou_rotated.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/deform_conv_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/deform_conv.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/roi_align_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/nms_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/pybind.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/upfirdn2d.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/nms_rotated_cpu.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/sync_bn_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/carafe.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/tin_shift.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/roi_align_rotated_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/cc_attention.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/border_align.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/roi_pool.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/fused_bias_leakyrelu_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/roi_pool_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/upfirdn2d_kernel.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/carafe_naive.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/cc_attention_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/nms.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/modulated_deform_conv.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/roi_align_cpu.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/carafe_naive_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/focal_loss_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/masked_conv2d.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/ms_deform_attn.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/roi_align_rotated_cpu.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/contour_expand.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/border_align_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/ms_deform_attn_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/carafe_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/corner_pool.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/sync_bn.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/tin_shift_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/box_iou_rotated_cpu.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/focal_loss.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/psamask.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/fused_bias_leakyrelu.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/deform_roi_pool_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/info.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/roi_align_rotated.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/nms_rotated_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/masked_conv2d_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/psamask_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/deform_roi_pool.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/box_iou_rotated_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/roi_align.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/bbox_overlaps_cuda.o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/./mmcv/ops/csrc/pytorch/bbox_overlaps.o -L/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda-10.2/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.8/mmcv/_ext.cpython-38-x86_64-linux-gnu.so
    building 'mmcv._ext_ort' extension
    Emitting ninja build file /root/downloads/mmcv/build/temp.linux-x86_64-3.8/build.ninja...
    Compiling objects...
    Using envvar MAX_JOBS (4) as the number of workers...
    [1/8] c++ -MMD -MF /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/soft_nms.o.d -pthread -B /root/anaconda3/envs/bcl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/downloads/mmcv/mmcv/ops/csrc/onnxruntime -I0/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/THC -I/root/anaconda3/envs/bcl/include/python3.8 -c -c /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/cpu/soft_nms.cpp -o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/soft_nms.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext_ort -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/soft_nms.o
    c++ -MMD -MF /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/soft_nms.o.d -pthread -B /root/anaconda3/envs/bcl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/downloads/mmcv/mmcv/ops/csrc/onnxruntime -I0/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/THC -I/root/anaconda3/envs/bcl/include/python3.8 -c -c /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/cpu/soft_nms.cpp -o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/soft_nms.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext_ort -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/cpu/soft_nms.cpp:1:0:
    /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/soft_nms.h:3:10: fatal error: onnxruntime_cxx_api.h: No such file or directory
     #include <onnxruntime_cxx_api.h>
              ^~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    [2/8] c++ -MMD -MF /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/nms.o.d -pthread -B /root/anaconda3/envs/bcl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/downloads/mmcv/mmcv/ops/csrc/onnxruntime -I0/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/THC -I/root/anaconda3/envs/bcl/include/python3.8 -c -c /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/cpu/nms.cpp -o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/nms.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext_ort -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/nms.o
    c++ -MMD -MF /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/nms.o.d -pthread -B /root/anaconda3/envs/bcl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/downloads/mmcv/mmcv/ops/csrc/onnxruntime -I0/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/THC -I/root/anaconda3/envs/bcl/include/python3.8 -c -c /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/cpu/nms.cpp -o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/nms.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext_ort -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/cpu/nms.cpp:1:0:
    /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/nms.h:4:10: fatal error: onnxruntime_cxx_api.h: No such file or directory
     #include <onnxruntime_cxx_api.h>
              ^~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    [3/8] c++ -MMD -MF /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.o.d -pthread -B /root/anaconda3/envs/bcl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/downloads/mmcv/mmcv/ops/csrc/onnxruntime -I0/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/THC -I/root/anaconda3/envs/bcl/include/python3.8 -c -c /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.cpp -o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext_ort -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.o
    c++ -MMD -MF /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.o.d -pthread -B /root/anaconda3/envs/bcl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/downloads/mmcv/mmcv/ops/csrc/onnxruntime -I0/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/THC -I/root/anaconda3/envs/bcl/include/python3.8 -c -c /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.cpp -o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext_ort -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/cpu/onnxruntime_register.cpp:1:0:
    /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/onnxruntime_register.h:3:10: fatal error: onnxruntime_c_api.h: No such file or directory
     #include <onnxruntime_c_api.h>
              ^~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    [4/8] c++ -MMD -MF /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/corner_pool.o.d -pthread -B /root/anaconda3/envs/bcl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/downloads/mmcv/mmcv/ops/csrc/onnxruntime -I0/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/THC -I/root/anaconda3/envs/bcl/include/python3.8 -c -c /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/cpu/corner_pool.cpp -o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/corner_pool.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext_ort -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/corner_pool.o
    c++ -MMD -MF /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/corner_pool.o.d -pthread -B /root/anaconda3/envs/bcl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/downloads/mmcv/mmcv/ops/csrc/onnxruntime -I0/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/TH -I/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/include/THC -I/root/anaconda3/envs/bcl/include/python3.8 -c -c /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/cpu/corner_pool.cpp -o /root/downloads/mmcv/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/onnxruntime/cpu/corner_pool.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext_ort -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/cpu/corner_pool.cpp:1:0:
    /root/downloads/mmcv/mmcv/ops/csrc/onnxruntime/corner_pool.h:5:10: fatal error: onnxruntime_cxx_api.h: No such file or directory
     #include <onnxruntime_cxx_api.h>
              ^~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
        subprocess.run(
      File "/root/anaconda3/envs/bcl/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/downloads/mmcv/setup.py", line 292, in <module>
        setup(
      File "/root/anaconda3/envs/bcl/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/root/anaconda3/envs/bcl/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/root/anaconda3/envs/bcl/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/root/anaconda3/envs/bcl/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/root/anaconda3/envs/bcl/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/root/anaconda3/envs/bcl/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/root/anaconda3/envs/bcl/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/root/anaconda3/envs/bcl/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/root/anaconda3/envs/bcl/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/root/anaconda3/envs/bcl/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/root/anaconda3/envs/bcl/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
        build_ext.build_extensions(self)
      File "/root/anaconda3/envs/bcl/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/root/anaconda3/envs/bcl/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/root/anaconda3/envs/bcl/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/root/anaconda3/envs/bcl/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/root/anaconda3/envs/bcl/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 491, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/root/anaconda3/envs/bcl/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/anaconda3/envs/bcl/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/downloads/mmcv/setup.py'"'"'; __file__='"'"'/root/downloads/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

ubuntu 16.04

**Comment by RunningLeon** [comment]
@BChunlei Hi, did you follow the instruction in the doc and download the tar file for onnxruntime?
https://github.com/open-mmlab/mmcv/blob/master/docs/onnxruntime_op.md#prerequisite

**Comment by BChunlei** [comment]
> @BChunlei Hi, did you follow the instruction in the doc and download the tar file for onnxruntime?
> https://github.com/open-mmlab/mmcv/blob/master/docs/onnxruntime_op.md#prerequisite

It works! But when i convert yolov3.onnx to trt model, it errors: 
RuntimeError: parse onnx failed:
In node -1 (convertAxis): UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims

I get the onnx file by tools/deployment/pytorch2onnx.py tool.
I tested with Pytorch==1.7.1, onnx==1.7.0 and TensorRT-7.2.3.4.Ubuntu-16.04.x86_64-gnu.cuda-10.2

**Comment by RunningLeon** [comment]
@BChunlei Could try with PyTorch==1.6.0? We did not fully test this feature on other versions.
BTW, you could check the note in the doc: https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/onnx2tensorrt.md#list-of-supported-models-convertable-to-tensorrt
All models above are tested with Pytorch==1.6.0, onnx==1.7.0 and TensorRT-7.2.1.6.Ubuntu-16.04.x86_64-gnu.cuda-10.2.cudnn8.0
