### ISSUE TITLE
mmcv for torch1.9

### ISSUE THREAD

**Issue by kentaroy47** [open-mmlab/mmcv#1122]
**Motivation**
Since google colab has upgraded to torch 1.9, it would be great if mmcv can provide pre-built packages for torch 1.9.

Thanks!

**Comment by zhouzaida** [comment]
hi @kentaroy47 , we are resolving the incompatibility between mmcv and torch1.9

**Comment by kentaroy47** [comment]
@zhouzaida thanks for the fast answers.
great to know that it's on your list!

**Comment by NielsRogge** [comment]
Yes, me too, getting the following error right now:

```
Traceback (most recent call last):
  File "tools/test.py", line 10, in <module>
    from mmseg.apis import multi_gpu_test, single_gpu_test
  File "/content/SegFormer/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/content/SegFormer/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/content/SegFormer/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/content/SegFormer/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/content/SegFormer/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/content/SegFormer/mmseg/models/decode_heads/__init__.py", line 4, in <module>
    from .cc_head import CCHead
  File "/content/SegFormer/mmseg/models/decode_heads/cc_head.py", line 7, in <module>
    from mmcv.ops import CrissCrossAttention
  File "/usr/local/lib/python3.7/dist-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/usr/local/lib/python3.7/dist-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/local/lib/python3.7/dist-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv
```

**Comment by zhouzaida** [comment]
> Yes, me too, getting the following error right now:
> 
> ```
> Traceback (most recent call last):
>   File "tools/test.py", line 10, in <module>
>     from mmseg.apis import multi_gpu_test, single_gpu_test
>   File "/content/SegFormer/mmseg/apis/__init__.py", line 1, in <module>
>     from .inference import inference_segmentor, init_segmentor, show_result_pyplot
>   File "/content/SegFormer/mmseg/apis/inference.py", line 8, in <module>
>     from mmseg.models import build_segmentor
>   File "/content/SegFormer/mmseg/models/__init__.py", line 1, in <module>
>     from .backbones import *  # noqa: F401,F403
>   File "/content/SegFormer/mmseg/models/backbones/__init__.py", line 2, in <module>
>     from .fast_scnn import FastSCNN
>   File "/content/SegFormer/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
>     from mmseg.models.decode_heads.psp_head import PPM
>   File "/content/SegFormer/mmseg/models/decode_heads/__init__.py", line 4, in <module>
>     from .cc_head import CCHead
>   File "/content/SegFormer/mmseg/models/decode_heads/cc_head.py", line 7, in <module>
>     from mmcv.ops import CrissCrossAttention
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/ops/__init__.py", line 1, in <module>
>     from .bbox import bbox_overlaps
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/ops/bbox.py", line 3, in <module>
>     ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
>     ext = importlib.import_module('mmcv.' + name)
>   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: /usr/local/lib/python3.7/dist-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv
> ```

hi @NielsRogge , you can degrade your torch version to 1.8.0. And the support of 1.9.0 is in our plan.

**Comment by CodingWZP** [comment]
I encountered a problem when i use customized chinese label. Please help me slove this problem.

2021-06-23 11:38:13,747 - mmcls - INFO - Start running, host: codingwzp@UbuntuOfWZP, work_dir: /home/codingwzp/CodesOfUbuntu/Work/ShuyeqiClassification/code_mmcls/work_dirs/mobilenet_v2_b32x8_imagenet
2021-06-23 11:38:13,747 - mmcls - INFO - workflow: [('train', 1)], max: 300 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 212/212, 89.7 task/s, elapsed: 2s, ETA:     0s2021-06-23 11:38:43,749 - mmcls - INFO - Saving checkpoint at 1 epochs
Traceback (most recent call last):
  File "/home/codingwzp/CodesOfUbuntu/Work/ShuyeqiClassification/code_mmcls/train.py", line 157, in <module>
    main()
  File "/home/codingwzp/CodesOfUbuntu/Work/ShuyeqiClassification/code_mmcls/train.py", line 153, in main
    meta=meta)
  File "/home/codingwzp/CodesOfUbuntu/Work/ShuyeqiClassification/mmclassification/mmcls/apis/train.py", line 159, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/checkpoint.py", line 69, in after_train_epoch
    self._save_checkpoint(runner)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/checkpoint.py", line 75, in _save_checkpoint
    self.out_dir, save_optimizer=self.save_optimizer, **self.args)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 164, in save_checkpoint
    save_checkpoint(self.model, filepath, optimizer=optimizer, meta=meta)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 671, in save_checkpoint
    torch.save(checkpoint, f)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 372, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/codingwzp/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 476, in _save
    pickler.dump(obj)
TypeError: can't pickle dict_values objects

Process finished with exit code 1

**Comment by zhouzaida** [comment]
hi all, we provide pre-built mmcv for pytorch1.9
