### ISSUE TITLE
How to pass lambda func through the config py file?

### ISSUE THREAD

**Issue by JiYuanFeng** [open-mmlab/mmcv#1174]
Hi, thanks for your nice work.  I try to use mmcv to re-construct my codebase. However, I found it fails to pass the lambda func via the config py file.
 
For example:
`dict(type="LoadImage", keys=keyword, reader="PILReader", converter=lambda image: image.convert("L"))`

But fails and get:
`Traceback (most recent call last):
  File "/root/anaconda3/envs/pt/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/root/anaconda3/envs/pt/lib/python3.7/lib2to3/pgen2/driver.py", line 104, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/root/anaconda3/envs/pt/lib/python3.7/lib2to3/pgen2/driver.py", line 72, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/root/anaconda3/envs/pt/lib/python3.7/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (40, 18))`

It seems that the mmcv config unable to parse the customed lambda func in the config py file.

At your convenience, can you provide some guidance on passing the lambda function via the mmcv config? Thank you!

**Comment by JiYuanFeng** [comment]
it seems unable to compile the func.   thanks and close the issue.
