### ISSUE TITLE
cu111 pytorch 1.9.0 mmcv_full-1.3.10-cp37-cp37m-manylinux1_x86_64.whl looks for cuda 10.2 instead of cuda 11.1

### ISSUE THREAD

**Issue by zwfcrazy** [open-mmlab/mmcv#1224]
**Describe the Issue**
I installed mmcv via
```bash
python3 -m pip install mmcv-full \
    -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
```
and pip automatically installed version 1.3.10 for me.
But when I try to do
```python
from mmcv.ops import *
```
it throws
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/opt/conda/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 12, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

The [1.3.9 wheel](https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/mmcv_full-1.3.9-cp37-cp37m-manylinux1_x86_64.whl) does not have this issue.

**Reproduction**

```python
from mmcv.ops import *
```

2. Did you make any modifications on the code? Did you understand what you have modified?

No

**Environment**
In docker container pytorch/pytorch:1.9.0-cuda11.1-cudnn8-devel.

If I run `python -c "from mmcv.utils import collect_env; print(collect_env())"` , it throws the same error.

**Error traceback**
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/opt/conda/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 12, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

**Comment by zhouzaida** [comment]
hi @zwfcrazy , thanks for your feedback. I am recompiling mmcv-full.

**Comment by zhouzaida** [comment]
hi @zwfcrazy, we have re-uploaded prebuild packages.
