### ISSUE TITLE
AttributeError: 'Version' object has no attribute 'release'

### ISSUE THREAD

**Issue by zjbthomas** [open-mmlab/mmcv#1230]
Hi Team.

I want to install mmcv-full through the requirements.txt in mmediting while I got error `AttributeError: 'Version' object has no attribute 'release'`.

I also tried install the package alone using `pip install mmcv-full` but I still got the same error.

Could you please provide some suggestions to solve the issue? Thank you.

```
Collecting mmcv-full>=1.2.0 (from -r requirements/runtime.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/0c/35/e3c775d3fbe931d1b1d7b354e638dd7ec007120cdc52d1312421587d34ac/mmcv-full-1.3.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-feq3d06i/mmcv-full/setup.py", line 320, in <module>
        version=get_version(),
      File "/tmp/pip-install-feq3d06i/mmcv-full/setup.py", line 37, in get_version
        exec(compile(f.read(), version_file, 'exec'))
      File "mmcv/version.py", line 35, in <module>
        version_info = parse_version_info(__version__)
      File "mmcv/version.py", line 21, in parse_version_info
        assert version.release, f'failed to parse version {version_str}'
    AttributeError: 'Version' object has no attribute 'release'
```

**Checklist**

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. I have read the FAQ documentation but cannot get the expected help.

**Comment by zhouzaida** [comment]
hi, please upgrade your setuptools by `pip install -U setuptools`

**Comment by zjbthomas** [comment]
It workds and thanks!
