### ISSUE TITLE
[Bug] #1252 seems causing `KeyError: 'data_time'` when evaluation interval is a multiple of logging interval

### ISSUE THREAD

**Issue by haotian-liu** [open-mmlab/mmcv#1261]
By default, `log_config.interval=50`.
When `evaluation.interval={50,200}`, there is an error _KeyError: 'data_time'_ (error log pasted below).
When `evaluation.interval=120`, the error does not occur at first several iterations (because the evaluation is quite long, I was unable to try testing when it reaches iteration 600, but I guess that it might trigger the error when it reaches there).
Not sure if there is anything that I am not doing correctly. Thank you for your great work and effort in maintaining this!

```
  File "/home/haotian/code/mmcv/mmcv/runner/hooks/logger/text.py", line 96, in _log_info
    log_str += f'time: {log_dict["time"]:.3f}, ' \
KeyError: 'data_time'
Traceback (most recent call last):
  File "./tools/train.py", line 223, in <module>
    main()
  File "./tools/train.py", line 219, in main
    meta=meta)
  File "/home/haotian/code/mmdetection3d/mmdet3d/apis/train.py", line 25, in train_model
    meta=meta)
  File "/home/haotian/code/mmsegmentation/mmseg/apis/train.py", line 116, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/haotian/code/mmcv/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/haotian/code/mmcv/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/home/haotian/code/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/haotian/code/mmcv/mmcv/runner/hooks/logger/base.py", line 152, in after_train_iter
    self.log(runner)
  File "/home/haotian/code/mmcv/mmcv/runner/hooks/logger/text.py", line 177, in log
    self._log_info(log_dict, runner)
  File "/home/haotian/code/mmcv/mmcv/runner/hooks/logger/text.py", line 96, in _log_info
    log_str += f'time: {log_dict["time"]:.3f}, ' \
```

**Comment by haotian-liu** [comment]
This seems to happen when #1252 is pushed to master branch by @zhouzaida. It would be really helpful if Zaida could kindly take a look. Thanks!

**Comment by zhouzaida** [comment]
Maybe I should remind you. Anyway, thanks for your feedback.

**Comment by haotian-liu** [comment]
@zhouzaida Thanks. Btw, should we also make the same modification for [mmdet](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L150)?

**Comment by zhouzaida** [comment]
In fact, it has no effect on EpochBasedRunner because its `evalhook` is triggered in after_train_epoch

**Comment by haotian-liu** [comment]
But I think there are models using IterBasedRunner in mmdet, e.g., yolof.

**Comment by zhouzaida** [comment]
got it, you are right. Maybe you can create a pull request to fix it in mmdet

**Comment by haotian-liu** [comment]
Thanks, I have opened the pull request: https://github.com/open-mmlab/mmdetection/pull/5882.
