### ISSUE TITLE
What are the best cuda, pytorch and mmcv version to run scfd? (undefined symbol: _ZN3c104cuda12device_countEv)

### ISSUE THREAD

**Issue by kevinzezel** [open-mmlab/mmcv#1288]
Hi,

Nice work!!

Please, what are the best cuda, pytorch and mmcv version to run scrfd?

I have a docker with pytorch 1.7.0, mmcv 1.3.3. and cuda 11.0.

I got this error:

root@c54294f6a9b0:/dados/demo# CUDA_VISIBLE_DEVICES=0 python image_demo.py --img President_Barack_Obama.jpg --config ../configs/scrfd/scrfd_10g_bnkps.py --checkpoint SCRFD_10G_KPS.pth
Traceback (most recent call last):
  File "image_demo.py", line 3, in <module>
    from mmdet.apis import inference_detector, init_detector, show_result_pyplot
  File "/dados/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/dados/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/opt/conda/lib/python3.6/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/opt/conda/lib/python3.6/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/opt/conda/lib/python3.6/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /opt/conda/lib/python3.6/site-packages/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda12device_countEv

**Comment by zhouzaida** [comment]
hi, please provide the command you install mmcv-full

**Comment by zhouzaida** [comment]
It is very likely that your MMCV is compiled in an environment but ran in another environment.
