### ISSUE TITLE
MMCVModulatedDeformConv2d 转Tensorrt时候出错

### ISSUE THREAD

**Issue by 606BlueStar** [open-mmlab/mmcv#1307]
您好，我在把MMCVModulatedDeformConv2d的onnx格式转为tensorrt时候出错了，麻烦MM的大佬们帮忙看一下，万分感谢！

代码如下：
```
import torch
import onnx

from mmcv.tensorrt import (TRTWrapper, onnx2trt, save_trt_engine,
                                   is_tensorrt_plugin_loaded)

# assert is_tensorrt_plugin_loaded(), 'Requires to complie TensorRT plugins in mmcv'

onnx_file = '/xx_backbone.onnx'
trt_file = 'sample.trt'
onnx_model = onnx.load(onnx_file)

# Model input
inputs = torch.rand(1, 3, 288, 288).cuda()
# Model input shape info
opt_shape_dict = {
    'input': [list(inputs.shape),
              list(inputs.shape),
              list(inputs.shape)]
}

# Create TensorRT engine
max_workspace_size = 1 << 30
trt_engine = onnx2trt(
    onnx_model,
    opt_shape_dict,
    max_workspace_size=max_workspace_size)

# Save TensorRT engine
save_trt_engine(trt_engine, trt_file)

# Run inference with TensorRT
trt_model = TRTWrapper(trt_file, ['input'], ['output'])

with torch.no_grad():
    trt_outputs = trt_model({'input': inputs})
    output = trt_outputs['output']
```
Tensorrt的版本跟mmcv文档中要求的是一致的：TensorRT-7.2.1.6

**Comment by grimoire** [comment]
Hi
The code works on my device(with different `onnx_file`).
Can you provide the error log?

**Comment by 606BlueStar** [comment]
> Hi
> The code works on my device(with different `onnx_file`).
> Can you provide the error log?

```
/home/hicourt1/.local/lib/python3.7/site-packages/torch/cuda/__init__.py:106: UserWarning: 
GeForce RTX 3070 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the GeForce RTX 3070 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin MMCVModulatedDeformConv2d version 1
Traceback (most recent call last):
  File "scripts/demo_moc_backbone.py", line 133, in <module>
    max_workspace_size=max_workspace_size)
  File "/home/hicourt1/.local/lib/python3.7/site-packages/mmcv/tensorrt/tensorrt_utils.py", line 62, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node -1 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "scripts/demo_moc_backbone.py", line 133, in <module>
    max_workspace_size=max_workspace_size)
  File "/home/hicourt1/.local/lib/python3.7/site-packages/mmcv/tensorrt/tensorrt_utils.py", line 62, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node -1 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
```

**Comment by grimoire** [comment]
Have you built the TensorRT plugin follow [the documentation](https://github.com/open-mmlab/mmcv/blob/master/docs/deployment/tensorrt_plugin.md)?
Please check if  `mmcv/_ext_trt.cpython-37m-x86_64-linux-gnu.so` exists. (The name might be slightly different depends on your environment).
If the file exists. Try:

```bash
objdump -t _ext_trt.cpython-37m-x86_64-linux-gnu.so |grep modulated
```

And see if there is any logs like:

```
0000000000000000 l    df *ABS*	0000000000000000              trt_modulated_deform_conv.cpp
0000000000020870 l     F .text	000000000000005f              _GLOBAL__sub_I_trt_modulated_deform_conv.cpp
0000000000000000 l    df *ABS*	0000000000000000              tmpxft_000074ae_00000000-6_trt_modulated_deform_conv_kernel.cudafe1.cpp
000000000018f800 l     O .bss	0000000000000008              _ZZL91__device_stub__Z38modulated_deformable_im2col_gpu_kernelIfEviPKT_S2_S2_iiiiiiiiiiiiiiiiPS0_iPKfS0_S0_iiiiiiiiiiiiiiiiPfE3__f
00000000000567b2 l     F .text	00000000000003f2              _ZL91__device_stub__Z38modulated_deformable_im2col_gpu_kernelIfEviPKT_S2_S2_iiiiiiiiiiiiiiiiPS0_iPKfS0_S0_iiiiiiiiiiiiiiiiPf
0000000000056ba4 l     F .text	0000000000000120              _Z61__wrapper__device_stub_modulated_deformable_im2col_gpu_kernelIfEvRKiRPKT_S5_S5_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_RPS2_
00000000000576de  w    F .text	0000000000000188              _Z31trt_modulated_deformable_im2colIfEvPKT_S2_S2_iiiiiiiiiiiiiiiPS0_P11CUstream_st
0000000000057608  w    F .text	0000000000000098              _Z38modulated_deformable_im2col_gpu_kernelIfEviPKT_S2_S2_iiiiiiiiiiiiiiiiPS0_
```

If there is no such log. Please rebuild the plugin and try again.

**Comment by 606BlueStar** [comment]
您好，这个文件是存在的，
`0000000000000000 l    df *ABS*  0000000000000000              trt_modulated_deform_conv.cpp
000000000001cdd0 l     F .text  000000000000005f              _GLOBAL__sub_I_trt_modulated_deform_conv.cpp
0000000000000000 l    df *ABS*  0000000000000000              tmpxft_00007a48_00000000-6_trt_modulated_deform_conv_kernel.cudafe1.cpp
000000000038db78 l     O .bss   0000000000000008              _ZZL91__device_stub__Z38modulated_deformable_im2col_gpu_kernelIfEviPKT_S2_S2_iiiiiiiiiiiiiiiiPS0_iPKfS0_S0_iiiiiiiiiiiiiiiiPfE3__f
0000000000047f49 l     F .text  00000000000003f2              _ZL91__device_stub__Z38modulated_deformable_im2col_gpu_kernelIfEviPKT_S2_S2_iiiiiiiiiiiiiiiiPS0_iPKfS0_S0_iiiiiiiiiiiiiiiiPf
000000000004833b l     F .text  0000000000000120              _Z61__wrapper__device_stub_modulated_deformable_im2col_gpu_kernelIfEvRKiRPKT_S5_S5_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_RPS2_
0000000000048e75  w    F .text  0000000000000188              _Z31trt_modulated_deformable_im2colIfEvPKT_S2_S2_iiiiiiiiiiiiiiiPS0_P11CUstream_st
0000000000048d9f  w    F .text  0000000000000098              _Z38modulated_deformable_im2col_gpu_kernelIfEviPKT_S2_S2_iiiiiiiiiiiiiiiiPS0_`

**Comment by 606BlueStar** [comment]
您好，
`0000000000000000 l    df *ABS*  0000000000000000              trt_modulated_deform_conv.cpp
000000000001cdd0 l     F .text  000000000000005f              _GLOBAL__sub_I_trt_modulated_deform_conv.cpp
0000000000000000 l    df *ABS*  0000000000000000              tmpxft_00007a48_00000000-6_trt_modulated_deform_conv_kernel.cudafe1.cpp
000000000038db78 l     O .bss   0000000000000008              _ZZL91__device_stub__Z38modulated_deformable_im2col_gpu_kernelIfEviPKT_S2_S2_iiiiiiiiiiiiiiiiPS0_iPKfS0_S0_iiiiiiiiiiiiiiiiPfE3__f
0000000000047f49 l     F .text  00000000000003f2              _ZL91__device_stub__Z38modulated_deformable_im2col_gpu_kernelIfEviPKT_S2_S2_iiiiiiiiiiiiiiiiPS0_iPKfS0_S0_iiiiiiiiiiiiiiiiPf
000000000004833b l     F .text  0000000000000120              _Z61__wrapper__device_stub_modulated_deformable_im2col_gpu_kernelIfEvRKiRPKT_S5_S5_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_RPS2_
0000000000048e75  w    F .text  0000000000000188              _Z31trt_modulated_deformable_im2colIfEvPKT_S2_S2_iiiiiiiiiiiiiiiPS0_P11CUstream_st
0000000000048d9f  w    F .text  0000000000000098              _Z38modulated_deformable_im2col_gpu_kernelIfEviPKT_S2_S2_iiiiiiiiiiiiiiiiPS0_`

**Comment by 606BlueStar** [comment]
![image](https://user-images.githubusercontent.com/42855446/131456794-11fcc424-778c-4332-8c4b-20a0b58e6dcc.png)

**Comment by grimoire** [comment]
Why do you comment the assertion?

```python
# assert is_tensorrt_plugin_loaded(), 'Requires to complie TensorRT plugins in mmcv'
```

If `is_tensorrt_plugin_loaded()` is False, please check if `get_tensorrt_op_path()` give you the right path (should be the path to `_ext_trt.xxxxx.so`)

**Comment by 606BlueStar** [comment]
您好，感谢回复，我已经按照mmcv的官方文档进行编译了，这句代码解除注释了还是不行。。。
![image](https://user-images.githubusercontent.com/42855446/131459828-6881fab6-f3ca-4ade-95e4-62fe1a74bc4f.png)

**Comment by 606BlueStar** [comment]
get_tensorrt_op_path()
这个函数，您可以给一个使用示例嘛？谢谢

**Comment by grimoire** [comment]
I believe you have built the plugin successfully since `objdump` can print the symbol about modulated_deformable_conv.
Let's make sure if there is something wrong when loading the plugin. Try the code below.

```python
import tensorrt as trt
from mmcv.tensorrt import load_tensorrt_plugin
from mmcv.tensorrt.init_plugins import get_tensorrt_op_path

print('The plugin path: {}'.format(get_tensorrt_op_path()))
load_tensorrt_plugin()
registry = trt.get_plugin_registry()
creators = registry.plugin_creator_list
for creator in creators:
    print(creator.name)
```

This code snippet will give you all the supported plugin names. See if  you can found `MMCVModulatedDeformConv2d` or not.

**Comment by 606BlueStar** [comment]
您好，下面是这段代码的输出，没有bug，您看下，非常感谢
![image](https://user-images.githubusercontent.com/42855446/131462516-c0e0289b-05fc-4404-8e53-78799119c2cc.png)

**Comment by 606BlueStar** [comment]
没有找到MMCVModulatedDeformConv2d。。。

**Comment by grimoire** [comment]
That's it. The plugin path is None, so it has not been loaded.

```python
from mmcv.tensorrt.init_plugins import get_tensorrt_op_path
print('The plugin path: {}'.format(get_tensorrt_op_path()))
```

This code snippet should give you the `_ext_trt` path. Please do some debug in [init_plugins.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/tensorrt/init_plugins.py) and find out why the plugin path is empty.

**Comment by 606BlueStar** [comment]
谢谢回复，当我执行：
`from mmcv.tensorrt.init_plugins import get_tensorrt_op_path
print('The plugin path: {}'.format(get_tensorrt_op_path()))`
这段代码的时候，输出为空。。

**Comment by 606BlueStar** [comment]
对照您发的init_plugins.py 中，这是我的目录结构，看起来应该没问题：
![image](https://user-images.githubusercontent.com/42855446/131464120-4730ea48-83da-460e-99d7-ad32df04d966.png)

**Comment by Z-XQ** [comment]
same problem.

cmd code: 
trtexec.exe --onnx=D:\code\python\mmocr\tools\deployment\tmp.onnx --saveEngine=D:\code\python\mmocr\tools\deployment\tmp.trt

error info:
[04/19/2022-17:31:31] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[04/19/2022-17:31:31] [I] [TRT] ModelImporter.cpp:135: **No importer registered for op: MMCVModulatedDeformConv2d**. Attempting to import as plugin.
[04/19/2022-17:31:31] [I] [TRT] builtin_op_importers.cpp:3771: Searching for plugin: MMCVModulatedDeformConv2d, plugin_version: 1, plugin_namespace:
[04/19/2022-17:31:31] [E] [TRT] INVALID_ARGUMENT: getPluginCreator could not find plugin MMCVModulatedDeformConv2d version 1
ERROR: builtin_op_importers.cpp:3773 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
[04/19/2022-17:31:31] [E] Failed to parse onnx file
[04/19/2022-17:31:31] [E] Parsing model failed
[04/19/2022-17:31:31] [E] Engine creation failed
[04/19/2022-17:31:31] [E] Engine set up failed

**Comment by grimoire** [comment]
@Z-XQ Please note that the support of model deployment has been moved to [MMDeploy](https://github.com/open-mmlab/mmdeploy). Please have a try.

**Comment by Z-XQ** [comment]
> @Z-XQ Please note that the support of model deployment has been moved to [MMDeploy](https://github.com/open-mmlab/mmdeploy). Please have a try.
Thank you for your relpy! MMDeploy is vary diffcult for me to setup and use on windows system. 

I just want to convert dbnet.onnx to dbnet.trt. Then I could deploy the trt model on windows platform by using c++ code.

**Comment by Ricardosuzaku** [comment]
> ```python
> print('The plugin path: {}'.format(get_tensorrt_op_path()))
> load_tensorrt_plugin()
> registry = trt.get_plugin_registry()
> creators = registry.plugin_creator_list
> for creator in creators:
>     print(creator.name)
> ```

Oo how do you solve the problem, I meet the same now.

**Comment by HerrYu123** [comment]
Excuse me, I meet the same problem now.

**Comment by kilikto** [comment]
After the PT model is converted to the ONNX model, the error onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError]: 1: FAIL: Load model from smoke_fire_pro.onnx failed:Fatal error: mmcv:MMCVModulatedDeformConv2d(-1) is not a registered function/op is reported when the ONNX model is used for object detection.

**Comment by kilikto** [comment]
what should i do?help me .

**Comment by hub-dsj** [comment]
哥们就是这个问题就是因为你的tensorrt plugin库里没有这个算子。
