### ISSUE TITLE
Getting unexpected key-error while installing

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [open-mmlab/mmcv#1352]
I tried to install mmcv-full using the bellow command

```
pip install mmcv-full==1.3.9 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html
```

and got a unexpected error
`KeyError: 'mmcv-full'`

my pip >= 20.3. 
how to solve this???

**Comment by zhouzaida** [comment]
what is your python version?

**Comment by Thevakumar-Luheerathan** [comment]
python 3.7.11

This is the error I got
```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'mmcv-full'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 317, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 82, in from_requirement
    if not cands:
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
    return any(self)
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 38, in _iter_built
    candidate = func()
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 169, in _make_candidate_from_link
    name=name, version=version,
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
    version=version,
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__
    self.dist = self._prepare()
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 312, in _prepare_distribution
    self._ireq, parallel_builds=True,
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 457, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 501, in _prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 67, in _get_prepared_distribution
    return abstract_dist.get_pkg_resources_distribution()
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/pip/_internal/distributions/wheel.py", line 30, in get_pkg_resources_distribution
    with ZipFile(self.req.local_file_path, allowZip64=True) as z:
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

```

**Comment by zhouzaida** [comment]
Is it possible to upgrade your pip version?

**Comment by Thevakumar-Luheerathan** [comment]
Sorry for the late response. I tried another way without changing pip. **I download the .wheel file and tried offline installation. It worked fine.** Thanks for support. These kind of quick responses really appreciable...

**Comment by DIYer22** [comment]
Fix same issue by
```
pip install --no-cache-dir -U pip wheel setuptools 
```
