### ISSUE TITLE
Can't install MMCV on Archlinux.

### ISSUE THREAD

**Issue by Beau-Yang** [open-mmlab/mmcv#1363]
Hello, I'm confronted with a problem when trying to install the mmdetection on Archlinux.
At first, I follow the tutorial and successfully run the following command:
```bash
conda create -n OD python
conda activate OD
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
pip install openmim
```
Then I try to install the mmdetection:
```bash
mim install mmdet
```
That results in a long error info. I think the key info is:
```
!! WARNING !!
  
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Your compiler (c++) is not compatible with the compiler Pytorch was
  built with for this platform, which is g++ on linux. Please
  use g++ to to compile your extension. Alternatively, you may
  compile PyTorch from source using c++, and then you can also use
  c++ to compile your extension.
  
  See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
  with compiling PyTorch from source.
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
So I try to install  install MMDetection manually instead. I need install mmcv first:
```
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
```
That generates  a similar error report. After that I try to install the mmcv manually but the result is the same.
I know that the error message may give the solutions but I'm not very familar with linux so I don't know what I should do to solve the problem. I notice that there are some similiar problems in the issues but they seem to be no help.

Thanks in advance.

####################################
Detailed information:

Operating System: Arch Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.14.6-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7.6 GiB of RAM
Graphics Processor: llvmpipe

g++ (GCC) 11.1.0
c++ (GCC) 11.1.0
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Aug_15_21:14:11_PDT_2021
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0

**Comment by zhouzaida** [comment]
hi, what is your python version?

**Comment by Beau-Yang** [comment]
python 3.9.7

**Comment by zhouzaida** [comment]
I am sorry to say that although mmcv supports python3.9 it has not provided a pre-built package for python3.9 and we should build it from source. In fact, the following warning shows the compiler is compiling the mmcv from source
```
!! WARNING !!
  
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Your compiler (c++) is not compatible with the compiler Pytorch was
  built with for this platform, which is g++ on linux. Please
  use g++ to to compile your extension. Alternatively, you may
  compile PyTorch from source using c++, and then you can also use
  c++ to compile your extension.
  
  See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
  with compiling PyTorch from source.
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by Beau-Yang** [comment]
I have tried to compile the mmcv from source as the instruction says:
```bash
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
MMCV_WITH_OPS=1 pip install -e .
```
But as mentioned above, the result remains the same. 
In addition, I notice that some environment variables are required on MacOS. Are those variables required on Archlinux?

**Comment by zhouzaida** [comment]
We can ignore the warning information.
Maybe you can replace `MMCV_WITH_OPS=1 pip install -e .` with `MMCV_WITH_OPS=1 python setup.py develop` to print the compiling log.

**Comment by Beau-Yang** [comment]
The error seems to remain the same. Part of the log are as follows:

```bash
                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!! WARNING !!

  warnings.warn(WRONG_COMPILER_WARNING.format(
Emitting ninja build file /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/build.ninja...
Compiling objects...
Using envvar MAX_JOBS (4) as the number of workers...
[1/45] /opt/cuda/bin/nvcc  -DMMCV_WITH_CUDA -I/home/beauyang/mmcv/mmcv/ops/csrc/common -I/home/beauyang/mmcv/mmcv/ops/csrc/common/cuda -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/TH -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/THC -I/opt/cuda/include -I/home/beauyang/.conda/envs/OD/include/python3.9 -c -c /home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/bbox_overlaps_cuda.cu -o /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/bbox_overlaps_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
```
```bash
RuntimeError: Error compiling objects for extension 
```

**Comment by zhouzaida** [comment]
please provide the full log

**Comment by Beau-Yang** [comment]
```bash
> MMCV_WITH_OPS=1 python setup.py develop
running develop
running egg_info
writing mmcv_full.egg-info/PKG-INFO
writing dependency_links to mmcv_full.egg-info/dependency_links.txt
writing requirements to mmcv_full.egg-info/requires.txt
writing top-level names to mmcv_full.egg-info/top_level.txt
reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
adding license file 'LICENSES.md'
writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
running build_ext
building 'mmcv._ext' extension
/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/utils/cpp_extension.py:284: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(WRONG_COMPILER_WARNING.format(
Emitting ninja build file /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/build.ninja...
Compiling objects...
Using envvar MAX_JOBS (4) as the number of workers...
[1/45] /opt/cuda/bin/nvcc  -DMMCV_WITH_CUDA -I/home/beauyang/mmcv/mmcv/ops/csrc/common -I/home/beauyang/mmcv/mmcv/ops/csrc/common/cuda -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/TH -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/THC -I/opt/cuda/include -I/home/beauyang/.conda/envs/OD/include/python3.9 -c -c /home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/box_iou_rotated_cuda.cu -o /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/box_iou_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/box_iou_rotated_cuda.o
/opt/cuda/bin/nvcc  -DMMCV_WITH_CUDA -I/home/beauyang/mmcv/mmcv/ops/csrc/common -I/home/beauyang/mmcv/mmcv/ops/csrc/common/cuda -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/TH -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/THC -I/opt/cuda/include -I/home/beauyang/.conda/envs/OD/include/python3.9 -c -c /home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/box_iou_rotated_cuda.cu -o /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/box_iou_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/c10/core/TensorImpl.h(2179): error: static assertion failed with "You changed the size of TensorImpl on 64-bit arch.See Note [TensorImpl size constraints] on how to proceed."

1 error detected in the compilation of "/home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/box_iou_rotated_cuda.cu".
[2/45] /opt/cuda/bin/nvcc  -DMMCV_WITH_CUDA -I/home/beauyang/mmcv/mmcv/ops/csrc/common -I/home/beauyang/mmcv/mmcv/ops/csrc/common/cuda -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/TH -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/THC -I/opt/cuda/include -I/home/beauyang/.conda/envs/OD/include/python3.9 -c -c /home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/carafe_cuda.cu -o /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/carafe_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/carafe_cuda.o
/opt/cuda/bin/nvcc  -DMMCV_WITH_CUDA -I/home/beauyang/mmcv/mmcv/ops/csrc/common -I/home/beauyang/mmcv/mmcv/ops/csrc/common/cuda -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/TH -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/THC -I/opt/cuda/include -I/home/beauyang/.conda/envs/OD/include/python3.9 -c -c /home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/carafe_cuda.cu -o /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/carafe_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/c10/core/TensorImpl.h(2179): error: static assertion failed with "You changed the size of TensorImpl on 64-bit arch.See Note [TensorImpl size constraints] on how to proceed."

1 error detected in the compilation of "/home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/carafe_cuda.cu".
[3/45] /opt/cuda/bin/nvcc  -DMMCV_WITH_CUDA -I/home/beauyang/mmcv/mmcv/ops/csrc/common -I/home/beauyang/mmcv/mmcv/ops/csrc/common/cuda -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/TH -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/THC -I/opt/cuda/include -I/home/beauyang/.conda/envs/OD/include/python3.9 -c -c /home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/border_align_cuda.cu -o /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/border_align_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/border_align_cuda.o
/opt/cuda/bin/nvcc  -DMMCV_WITH_CUDA -I/home/beauyang/mmcv/mmcv/ops/csrc/common -I/home/beauyang/mmcv/mmcv/ops/csrc/common/cuda -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/TH -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/THC -I/opt/cuda/include -I/home/beauyang/.conda/envs/OD/include/python3.9 -c -c /home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/border_align_cuda.cu -o /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/border_align_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/c10/core/TensorImpl.h(2179): error: static assertion failed with "You changed the size of TensorImpl on 64-bit arch.See Note [TensorImpl size constraints] on how to proceed."

1 error detected in the compilation of "/home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/border_align_cuda.cu".
[4/45] /opt/cuda/bin/nvcc  -DMMCV_WITH_CUDA -I/home/beauyang/mmcv/mmcv/ops/csrc/common -I/home/beauyang/mmcv/mmcv/ops/csrc/common/cuda -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/TH -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/THC -I/opt/cuda/include -I/home/beauyang/.conda/envs/OD/include/python3.9 -c -c /home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/bbox_overlaps_cuda.cu -o /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/bbox_overlaps_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/bbox_overlaps_cuda.o
/opt/cuda/bin/nvcc  -DMMCV_WITH_CUDA -I/home/beauyang/mmcv/mmcv/ops/csrc/common -I/home/beauyang/mmcv/mmcv/ops/csrc/common/cuda -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/TH -I/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/THC -I/opt/cuda/include -I/home/beauyang/.conda/envs/OD/include/python3.9 -c -c /home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/bbox_overlaps_cuda.cu -o /home/beauyang/mmcv/build/temp.linux-x86_64-3.9/mmcv/ops/csrc/pytorch/cuda/bbox_overlaps_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/include/c10/core/TensorImpl.h(2179): error: static assertion failed with "You changed the size of TensorImpl on 64-bit arch.See Note [TensorImpl size constraints] on how to proceed."

1 error detected in the compilation of "/home/beauyang/mmcv/mmcv/ops/csrc/pytorch/cuda/bbox_overlaps_cuda.cu".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/beauyang/mmcv/setup.py", line 323, in <module>
    setup(
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 530, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/beauyang/.conda/envs/OD/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

```
