### ISSUE TITLE
windows mmcv==v1.3.14 build ext fail

### ISSUE THREAD

**Issue by xiexinch** [open-mmlab/mmcv#1397]
I can compile and install v1.3.13 successfully，but v1.3.14 fail.

**env**
```shell
#nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:41:42_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```

```shell
# python -V
Python 3.8.8
###
torch 1.8.1
```

**Before compiling**

```shell
$env:CUDA_HOME = $env:CUDA_PATH_V11_3
$env:MMCV_WITH_OPS = 1
$env:MAX_JOBS = 8
```

**command**
```shell
python setup.py build_ext
```

**error**

```shell
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\xiexinchen\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "C:\Users\xiexinchen\anaconda3\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '8']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\setup.py", line 323, in <module>
    setup(
  File "C:\Users\xiexinchen\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\xiexinchen\anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\xiexinchen\anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\xiexinchen\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\xiexinchen\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\xiexinchen\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\xiexinchen\anaconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\xiexinchen\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\xiexinchen\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\xiexinchen\anaconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\xiexinchen\anaconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\xiexinchen\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\xiexinchen\anaconda3\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\Users\xiexinchen\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 681, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\xiexinchen\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\xiexinchen\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by zhouzaida** [comment]
hi, I am sorry to find any useful information in the log provided by you. Please provide the log that reported the error at the beginning

**Comment by xiexinch** [comment]
Hi @Creyentez, now it could use `MIM` to install mmcv-full on Windows.
```shell
pip install openmim
mim install mmcv-full
```
