### ISSUE TITLE
Config can not be used in python multiprocessing spawn context

### ISSUE THREAD

**Issue by auroua** [open-mmlab/mmcv#147]
The following code can cause the error.
```
from multiprocessing import Process
from mmcv import Config
import multiprocessing as mp


def f(cfg):
    print(cfg)


if __name__ == '__main__':
    mp.set_start_method('spawn')
    cfgs = Config(dict(a=1, b=dict(b1=[0, 1])))
    process_list = []
    for _ in range(3):
        p = Process(target=f, args=(cfgs, ))
        p.start()
        process_list.append(p)
    for p in process_list:
        p.join()

```

Running this code cause the following error:
```
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/albert/Softwares/anaconda3/envs/py36/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
  File "/home/albert/Softwares/anaconda3/envs/py36/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
  File "/home/albert/Softwares/anaconda3/envs/py36/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
    exitcode = _main(fd)
  File "/home/albert/Softwares/anaconda3/envs/py36/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
  File "/home/albert/Softwares/anaconda3/envs/py36/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    exitcode = _main(fd)
  File "/home/albert/Softwares/anaconda3/envs/py36/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
    self = reduction.pickle.load(from_parent)
  File "/home/albert/Softwares/mmcv-0.2.14/mmcv/utils/config.py", line 143, in __getattr__
  File "/home/albert/Softwares/mmcv-0.2.14/mmcv/utils/config.py", line 143, in __getattr__
    self = reduction.pickle.load(from_parent)
  File "/home/albert/Softwares/mmcv-0.2.14/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
    return getattr(self._cfg_dict, name)
  File "/home/albert/Softwares/mmcv-0.2.14/mmcv/utils/config.py", line 143, in __getattr__
  File "/home/albert/Softwares/mmcv-0.2.14/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/albert/Softwares/mmcv-0.2.14/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
    return getattr(self._cfg_dict, name)
  File "/home/albert/Softwares/mmcv-0.2.14/mmcv/utils/config.py", line 143, in __getattr__
  File "/home/albert/Softwares/mmcv-0.2.14/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/albert/Softwares/mmcv-0.2.14/mmcv/utils/config.py", line 143, in __getattr__
    return getattr(self._cfg_dict, name)
    return getattr(self._cfg_dict, name)
  [Previous line repeated 329 more times]
  [Previous line repeated 329 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
    return getattr(self._cfg_dict, name)
  [Previous line repeated 329 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by NotF404** [comment]
hi,
 i got same problem, how do u solve this

**Comment by mitsuix** [comment]
I met the same problem.How did you solve this problem?
@NotF404 @auroua

**Comment by LightningChan** [comment]
I also got this problem, anyone know how to solve?

**Comment by mitsuix** [comment]
upgrade mmcv...
