### ISSUE TITLE
cpu/gpu compatiblity of example/train.py 

### ISSUE THREAD

**Issue by bladrome** [open-mmlab/mmcv#1470]
**demo example ought to be run out of box.**

**Reproduction**

1. What command, code, or script did you run?

```bash
python example/train.py
```

2. Did you make any modifications on the code? Did you understand what you have modified?
```bash
yes
```
**Environment**

1. Please run `python -c "from mmcv.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
```bash
python -c "from mmcv.utils import collect_env; import pprint; pprint.pprint(collect_env())"
{'CUDA available': True,
 'CUDA_HOME': '/usr/local/cuda-10.2',
 'GCC': 'gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010',
 'GPU 0,1': 'NVIDIA TITAN RTX',
 'MMCV': '1.3.16',
 'MMCV CUDA Compiler': '10.2',
 'MMCV Compiler': 'GCC 7.3',
 'NVCC': 'Cuda compilation tools, release 10.2, V10.2.89',
 'OpenCV': '4.5.4-dev',
 'PyTorch': '1.9.1',
 'PyTorch compiling details': 'PyTorch built with:\n'
                              '  - GCC 7.3\n'
                              '  - C++ Version: 201402\n'
                              '  - Intel(R) oneAPI Math Kernel Library Version '
                              '2021.3-Product Build 20210617 for Intel(R) 64 '
                              'architecture applications\n'
                              '  - Intel(R) MKL-DNN v2.1.2 (Git Hash '
                              '98be7e8afa711dc9b66c8ff3504129cb82013cdb)\n'
                              '  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n'
                              '  - NNPACK is enabled\n'
                              '  - CPU capability usage: AVX2\n'
                              '  - CUDA Runtime 10.2\n'
                              '  - NVCC architecture flags: '
                              '-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37\n'
                              '  - CuDNN 7.6.5\n'
                              '  - Magma 2.5.2\n'
                              '  - Build settings: BLAS_INFO=mkl, '
                              'BUILD_TYPE=Release, CUDA_VERSION=10.2, '
                              'CUDNN_VERSION=7.6.5, '
                              'CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, '
                              'CXX_FLAGS= -Wno-deprecated '
                              '-fvisibility-inlines-hidden -DUSE_PTHREADPOOL '
                              '-fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM '
                              '-DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK '
                              '-DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE '
                              '-O2 -fPIC -Wno-narrowing -Wall -Wextra '
                              '-Werror=return-type '
                              '-Wno-missing-field-initializers '
                              '-Wno-type-limits -Wno-array-bounds '
                              '-Wno-unknown-pragmas -Wno-sign-compare '
                              '-Wno-unused-parameter -Wno-unused-variable '
                              '-Wno-unused-function -Wno-unused-result '
                              '-Wno-unused-local-typedefs -Wno-strict-overflow '
                              '-Wno-strict-aliasing '
                              '-Wno-error=deprecated-declarations '
                              '-Wno-stringop-overflow -Wno-psabi '
                              '-Wno-error=pedantic -Wno-error=redundant-decls '
                              '-Wno-error=old-style-cast '
                              '-fdiagnostics-color=always -faligned-new '
                              '-Wno-unused-but-set-variable '
                              '-Wno-maybe-uninitialized -fno-math-errno '
                              '-fno-trapping-math -Werror=format '
                              '-Wno-stringop-overflow, LAPACK_INFO=mkl, '
                              'PERF_WITH_AVX=1, PERF_WITH_AVX2=1, '
                              'PERF_WITH_AVX512=1, TORCH_VERSION=1.9.1, '
                              'USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, '
                              'USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, '
                              'USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, '
                              'USE_NNPACK=ON, USE_OPENMP=ON, \n',
 'Python': '3.7.10 | packaged by conda-forge | (default, Oct 13 2021, '
           '21:01:18) [GCC 9.4.0]',
 'TorchVision': '0.10.1',
 'sys.platform': 'linux'}
```
**Error traceback**
```bash
run `python example/train.py`
```
```none

 Traceback (most recent call last):
  File "train.py", line 82, in <module>
    runner.run([trainloader], [('train', 1)])
  File "/home/jack/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jack/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/jack/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/jack/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 55, in train_step
    ('MMDataParallel only supports single GPU training, if you need to'
AssertionError: MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MMDistributedDataParallelinstead.

```
When I change `model = MMDataParallel(model.cuda())` to `model = model.cuda()`:
```none

Traceback (most recent call last):
  File "train.py", line 83, in <module>
    runner.run([trainloader], [('train', 1)])
  File "/home/jack/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jack/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/jack/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "train.py", line 37, in train_step
    predicts = self(images)  # -> self.__call__() -> self.forward()
  File "/home/jack/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "train.py", line 27, in forward
    x = self.pool(F.relu(self.conv1(x)))
  File "/home/jack/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jack/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/jack/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 440, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

```

**Bug fix**

https://github.com/open-mmlab/mmcv/blob/792473c960ed91e334164debc6877a96fdac9558/examples/train.py#L36
```python
images, labels = images.cuda(), labels.cuda()
```
https://github.com/open-mmlab/mmcv/blob/792473c960ed91e334164debc6877a96fdac9558/examples/train.py#L45
```python
model = model.cuda()
```
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by teamwong111** [comment]
Hi, @bladrome, thank you for your issue. Actually, wo hope users to use MMDataParallel becuse it supports a custom type :class:`DataContainer` which allows more flexible control of input data during both GPU and CPU inference. In addition, according to the Error traceback, if you need to train with multiple GPUs, please use MMDistributedDataParallel instead.

**Comment by bladrome** [comment]
Yes, the default code works fine on CPU. Actually I want to test the example/train.py on single GPU, but maybe mmcv detect there are 2 GPUs on my machine.  It does NOT fit the expect condition.
It doesn't work even though 
```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = "0"
```
and 
```python
model = MMDataParallel(model.cuda())
```

**Comment by teamwong111** [comment]
Actually Pytorch detects how many GPUs are in your machine. Since MMDataParallel is inherited from Pytorch's DataParallel, and DataParallel gets device_ids, the value of device_ids cannot be changed even if the environment variable is set. So, if you need to use single GPU testing, please modify code like this.
```
model = MMDataParallel(model.cuda(), [0])
```
Also, thank you very much for your question, and we will discuss how to solve this problem later!

**Comment by teamwong111** [comment]
Actually Pytorch detects how many GPUs are in your machine. Since MMDataParallel is inherited from Pytorch's DataParallel, and DataParallel gets device_ids, the value of device_ids cannot be changed even if the environment variable is set. So, if you need to use single GPU testing, please modify code like this.
```
model = MMDataParallel(model.cuda(), [0])
```
Also, thank you very much for your question, and we will discuss how to solve this problem later!

**Comment by bladrome** [comment]
Great, it's what I want.
