### ISSUE TITLE
Failed building wheel for opencv-python with error message - No such file or directory: 'scripts/__init__.py'

### ISSUE THREAD

**Issue by dasabir** [open-mmlab/mmcv#1487]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

while building mmcv from source (by using "MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install -e .") in RHEL Server 7.6, with python 3.7.3, gcc 7.3.0, pytorch 1.7.1 and cuda 10.2, I am encountering an error "_ERROR: Could not build wheels for opencv-python, which is required to install pyproject.toml-based projects_". Last few lines of the traceback says -
```
File "setup.py", line 289, in main
      cmake_source_dir=cmake_source_dir,
    File "/tmp/pip-build-env-_w_vgir1/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 629, in setup
      cmake_source_dir, skbuild_kw['cmake_install_dir'])
    File "setup.py", line 381, in _classify_installed_files_override
      with open('scripts/__init__.py', 'r') as custom_init:
  FileNotFoundError: [Errno 2] No such file or directory: 'scripts/__init__.py'
  ----------------
  ERROR: Failed building wheel for opencv-python
```

I think this is related to a [very recent bugfix in opencv](https://github.com/opencv/opencv-python/pull/577/commits/9a7af2aa4090d40a981cf91ef2b3c4c363e356de)
Exactly line 381 in setup.py (where the installation is facing the error in the traceback) has a change in the above commit of opencv. Can you please help?

**Comment by zhouzaida** [comment]
Hi @dasabir , you can try to upgrade your pip, setuptools and wheel using the following command
```
pip install --upgrade pip setuptools wheel
```

**Comment by dasabir** [comment]
> Hi @dasabir , you can try to upgrade your pip, setuptools and wheel using the following command
> 
> ```
> pip install --upgrade pip setuptools wheel
> ```

No luck. Same error. I did upgrade pip and setuptools earlier (before messaging here). This time I upgraded wheel too. But same error is coming.

**Comment by zhouzaida** [comment]
`pip install opencv-python==4.5.2.52`

**Comment by dasabir** [comment]
> opencv-python==4.5.2.52

Thanks @zhouzaida . I installed (using pip) opencv-python==4.5.3.56 [opencv-python==4.5.**2.52** is not available, so I installed 4.5.**3.56** as mentioned in the issue you linked]. Before that I upgraded pytorch to **1.9.0**. Everything else remains same - i.e., RHEL Server 7.6, with python 3.7.3, gcc 7.3.0 and cuda 10.2. Now after installing opencv-python==4.5.3.56, if I try to install mmcv-full by using _MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install -e ._, I am getting something related to c++ and g++ conflict. I am pasting the last few lines of the error log. The recurring lines seems to be - *cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++*
```
[7/85] c++ -MMD -MF /nobackup/users/dasabir/workspace/mmcv/build/temp.linux-ppc64le-3.7/mmcv/ops/csrc/pytorch/info.o.d -pthread -B /nobackup/users/dasabir/anaconda3/envs/mmaction_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common -I/nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common/cuda -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/TH -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/include/python3.7m -c -c /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/info.cpp -o /nobackup/users/dasabir/workspace/mmcv/build/temp.linux-ppc64le-3.7/mmcv/ops/csrc/pytorch/info.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
    FAILED: /nobackup/users/dasabir/workspace/mmcv/build/temp.linux-ppc64le-3.7/mmcv/ops/csrc/pytorch/info.o
    c++ -MMD -MF /nobackup/users/dasabir/workspace/mmcv/build/temp.linux-ppc64le-3.7/mmcv/ops/csrc/pytorch/info.o.d -pthread -B /nobackup/users/dasabir/anaconda3/envs/mmaction_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common -I/nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common/cuda -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/TH -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/include/python3.7m -c -c /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/info.cpp -o /nobackup/users/dasabir/workspace/mmcv/build/temp.linux-ppc64le-3.7/mmcv/ops/csrc/pytorch/info.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:140:0,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                     from /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common/pytorch_cpp_helper.hpp:3,
                     from /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/info.cpp:4:
    /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:87:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for if ((end - begin) >= grain_size)
    
    /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/info.cpp:8:10: fatal error: cuda_runtime_api.h: No such file or directory
     #include <cuda_runtime_api.h>
              ^~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    [8/85] c++ -MMD -MF /nobackup/users/dasabir/workspace/mmcv/build/temp.linux-ppc64le-3.7/mmcv/ops/csrc/pytorch/roi_align_cpu.o.d -pthread -B /nobackup/users/dasabir/anaconda3/envs/mmaction_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common -I/nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common/cuda -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/TH -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/include/python3.7m -c -c /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/roi_align_cpu.cpp -o /nobackup/users/dasabir/workspace/mmcv/build/temp.linux-ppc64le-3.7/mmcv/ops/csrc/pytorch/roi_align_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:140:0,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                     from /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common/pytorch_cpp_helper.hpp:3,
                     from /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/roi_align_cpu.cpp:7:
    /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:87:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for if ((end - begin) >= grain_size)
    
    [9/85] c++ -MMD -MF /nobackup/users/dasabir/workspace/mmcv/build/temp.linux-ppc64le-3.7/mmcv/ops/csrc/pytorch/corner_pool.o.d -pthread -B /nobackup/users/dasabir/anaconda3/envs/mmaction_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common -I/nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common/cuda -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/TH -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/include/python3.7m -c -c /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/corner_pool.cpp -o /nobackup/users/dasabir/workspace/mmcv/build/temp.linux-ppc64le-3.7/mmcv/ops/csrc/pytorch/corner_pool.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:140:0,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                     from /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common/pytorch_cpp_helper.hpp:3,
                     from /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/corner_pool.cpp:4:
    /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:87:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for if ((end - begin) >= grain_size)
    
    [10/85] c++ -MMD -MF /nobackup/users/dasabir/workspace/mmcv/build/temp.linux-ppc64le-3.7/mmcv/ops/csrc/pytorch/nms.o.d -pthread -B /nobackup/users/dasabir/anaconda3/envs/mmaction_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common -I/nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common/cuda -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/TH -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/nobackup/users/dasabir/anaconda3/envs/mmaction_env/include/python3.7m -c -c /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/nms.cpp -o /nobackup/users/dasabir/workspace/mmcv/build/temp.linux-ppc64le-3.7/mmcv/ops/csrc/pytorch/nms.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:140:0,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                     from /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                     from /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/common/pytorch_cpp_helper.hpp:3,
                     from /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/nms.cpp:2:
    /nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:87:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for if ((end - begin) >= grain_size)
    
    /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/nms.cpp: In function 'std::vector<std::vector<int, std::allocator<int> > > nms_match_cpu(at::Tensor, float)':
    /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/nms.cpp:250:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i = 0; i < keep.size(); i++)
                       ~~^~~~~~~~~~~~~
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1679, in _run_ninja_build
        env=env)
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/nobackup/users/dasabir/workspace/mmcv/setup.py", line 349, in <module>
        zip_safe=False)
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/setuptools/__init__.py", line 159, in setup
        return distutils.core.setup(**attrs)
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 716, in build_extensions
        build_ext.build_extensions(self)
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 546, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1367, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/nobackup/users/dasabir/anaconda3/envs/mmaction_env/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1689, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /nobackup/users/dasabir/anaconda3/envs/mmaction_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/nobackup/users/dasabir/workspace/mmcv/setup.py'"'"'; __file__='"'"'/nobackup/users/dasabir/workspace/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

Not sure, if it has to do anything with a warning I am getting early in the log which says
```
!! WARNING !!
    
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Your compiler (c++) is not compatible with the compiler Pytorch was
    built with for this platform, which is g++ on linux. Please
    use g++ to to compile your extension. Alternatively, you may
    compile PyTorch from source using c++, and then you can also use
    c++ to compile your extension.
    
    See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
    with compiling PyTorch from source.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    
                                  !! WARNING !!
```

Any help will be highly appreciated.

**Comment by zhouzaida** [comment]
> /nobackup/users/dasabir/workspace/mmcv/mmcv/ops/csrc/pytorch/info.cpp:8:10: fatal error: cuda_runtime_api.h: No such file or directory

Please check whether `LD_LIBRARY_PATH` has been set correctly.

**Comment by zhouzaida** [comment]
In fact, you can install `mmcv-full` with the following command
```
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.7.0/index.html
```

**Comment by zhouzaida** [comment]
Hi @dasabir , is there any progress?

**Comment by dasabir** [comment]
> Hi @dasabir , is there any progress?

Hi @zhouzaida . Yes, I was just going to post. Finally I could manage to install mmcv. The issue was with the right LD_LIBRARY_PATH and one more env variable CPATH. CPATH was somehow not set. When I exported the cuda/10.2/include path to CPATH and build from source, it compiled successfully. You can close the issue. Thanks a lot for the pointers.
