### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'data'

### ISSUE THREAD

**Issue by little-rice-2020** [open-mmlab/mmcv#1529]
python tools/test.py configs/_base_/models/resnet50.py checkpoints/resnet50_batch256_imagenet_20200708-cfb998bf.pth
/home/user01/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer. UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_dattn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "tools/test.py", line 219, in <module>
    main()
  File "tools/test.py", line 126, in main
    cfg.data.test.test_mode = True
  File "/home/user01/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.pye 507, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/user01/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.pye 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'data'

**Comment by zhouzaida** [comment]
Hi, @little-rice-2020, could you provide the output of `pip list | grep mmcv`?
