### ISSUE TITLE
ModuleNotFoundError: No module named 'mc'

### ISSUE THREAD

**Issue by jinyummiao** [open-mmlab/mmcv#1608]
Hi, I have met some errors in using mmcv.

`Traceback (most recent call last):
  File "/home/jinyu/Documents/mmdetection/mmdet/.mim/tools/train.py", line 185, in <module>
    main()
  File "/home/jinyu/Documents/mmdetection/mmdet/.mim/tools/train.py", line 181, in main
    meta=meta)
  File "/home/jinyu/Documents/mmdetection/mmdet/apis/train.py", line 203, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/jinyu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jinyu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/jinyu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/jinyu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/jinyu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/jinyu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ImportError: Caught ImportError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jinyu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 428, in __init__
    import mc
ModuleNotFoundError: No module named 'mc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jinyu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jinyu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jinyu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jinyu/Documents/mmdetection/mmdet/datasets/dataset_wrappers.py", line 176, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/home/jinyu/Documents/mmdetection/mmdet/datasets/custom.py", line 216, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/jinyu/Documents/mmdetection/mmdet/datasets/custom.py", line 239, in prepare_train_img
    return self.pipeline(results)
  File "/home/jinyu/Documents/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/jinyu/Documents/mmdetection/mmdet/datasets/pipelines/loading.py", line 57, in __call__
    self.file_client = mmcv.FileClient(**self.file_client_args)
  File "/home/jinyu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 814, in __new__
    _instance.client = cls._backends[backend](**kwargs)
  File "/home/jinyu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 431, in __init__
    'Please install memcached to enable MemcachedBackend.')
ImportError: Please install memcached to enable MemcachedBackend.
`

It seems that **memcached** is not installed, but i have run `apt-get install mamcached` before and **mmcv-full** is installed successfully. Can you give me some advices? Thanks.

**Comment by zhouzaida** [comment]
Hi, @jinyummiao , the mc is our internal package.

**Comment by jinyummiao** [comment]
So how can i fix this error? I have installed 'mmcv-full' via 'mim'. The versions of pytorch, torchvision, mmcv are 1.6.0, 0.7.0, and 1.4.1.

**Comment by zhouzaida** [comment]
Could you provide your config?

**Comment by jinyummiao** [comment]
Thanks for your kindly reply. The error is fixed and it is probably caused by memcahced.

**Comment by kiofwind** [comment]
Hi, I also meet the same problem as you. Could you please share the key to solve this problem?Thanks!

**Comment by shisan-lang** [comment]
明明没解决，为什么还要说这个问题已经解决？
