### ISSUE TITLE
windows installation error with pre-compiled mmcv v1.4.1

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmcv#1619]
## steps to reproduce:

- in terminal:

```bash
conda create -n mmlab python=3.9 -y 
conda activate mmlab 

conda install pytorch=1.10.0 torchvision=0.11.1 cudatoolkit=11.3 -c pytorch -y
pip install mmcv-full==1.4.1 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html

python
```

- in python:

```python
from mmcv.ops import RoIPool
```

## error:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxxMiniconda3\envs\xxx\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "C:\Users\xxx\Miniconda3\envs\xxx\lib\site-packages\mmcv\ops\assign_score_withk.py", line 5, in <module>      
    ext_module = ext_loader.load_ext(
  File "C:\Users\xxx\Miniconda3\envs\xxx\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\xxx\Miniconda3\envs\xxx\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.
```

**Comment by del-zhenwu** [comment]
Thanks for your report, this issue could be re-produced, we will trace this issue and replace the lib-package after we fix it.

**Comment by del-zhenwu** [comment]
`v1.4.0` is OK, only exists with `v1.4.1`, maybe you can try `v1.4.0` temporary @fcakyon

**Comment by zhouzaida** [comment]
We have updated the pre-built packages. Please have a try.

**Comment by fcakyon** [comment]
@zhouzaida its fixed, thanks!
