### ISSUE TITLE
AssertionError: ca_forward miss in module _ext

### ISSUE THREAD

**Issue by ninghe0911** [open-mmlab/mmcv#1630]
hello,

The following error occurs when I run the `train.py` file.  Is it the MMCV problem ?

```
C:\Users\admin\Anaconda3\envs\pytorch_envs\python.exe C:/Users/admin/Desktop/pytorch/UperNet_Swin/tools/train.py
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/pytorch/UperNet_Swin/tools/train.py", line 13, in <module>
    from UperNet_Swin.mmseg.apis import set_random_seed, train_segmentor
  File "C:\Users\admin\Desktop\pytorch\UperNet_Swin\mmseg\apis\__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "C:\Users\admin\Desktop\pytorch\UperNet_Swin\mmseg\apis\inference.py", line 8, in <module>
    from UperNet_Swin.mmseg.models import build_segmentor
  File "C:\Users\admin\Desktop\pytorch\UperNet_Swin\mmseg\models\__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "C:\Users\admin\Desktop\pytorch\UperNet_Swin\mmseg\models\backbones\__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "C:\Users\admin\Desktop\pytorch\UperNet_Swin\mmseg\models\backbones\fast_scnn.py", line 7, in <module>
    from UperNet_Swin.mmseg.models.decode_heads.psp_head import PPM
  File "C:\Users\admin\Desktop\pytorch\UperNet_Swin\mmseg\models\decode_heads\__init__.py", line 4, in <module>
    from .cc_head import CCHead
  File "C:\Users\admin\Desktop\pytorch\UperNet_Swin\mmseg\models\decode_heads\cc_head.py", line 7, in <module>
    from mmcv.ops import CrissCrossAttention
  File "C:\Users\admin\Anaconda3\envs\pytorch_envs\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .cc_attention import CrissCrossAttention
  File "C:\Users\admin\Anaconda3\envs\pytorch_envs\lib\site-packages\mmcv\ops\cc_attention.py", line 10, in <module>
    '_ext', ['ca_forward', 'ca_backward', 'ca_map_forward', 'ca_map_backward'])
  File "C:\Users\admin\Anaconda3\envs\pytorch_envs\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'  
AssertionError: ca_forward miss in module _ext

Process finished with exit code 1
```

Thanks

**Comment by zhouzaida** [comment]
What is your mmcv-full version?

**Comment by zhouzaida** [comment]
Hi @ninghe0911 , is there any progress?

**Comment by powlook** [comment]
Hi @zhouzaida,
I encounter this problem when trying to run mmcv. My mmcv-full version is 1.1.5

**Comment by zhouzaida** [comment]
> Hi @zhouzaida, I encounter this problem when trying to run mmcv. My mmcv-full version is 1.1.5

Hi @powlook , did you compile the mmcv-full with the CUDA environment?

**Comment by powlook** [comment]
Hi @zhouzaida,
I uninstall mmcv-full and reinstall again. It is working now.
Tks,
PL

**Comment by powlook** [comment]
Hi @zhouzaida,

File "/home/powlook/wda/lib/python3.8/site-packages/mmcv/utils/config.py", line 43, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'det_class'

I encountered the error above when it was running mmcv. I was told that it could be a version issue as older version of mmcv does not read det_class. I was at mmcv-full 1.1.5. I was asked to uninstall and re-install 1.2.7. I did this and the problem is still there. Is this a version problem and if any version can fix this issue?

Regards,
PL

**Comment by zhouzaida** [comment]
> 

Hi @powlook , please check your config whether it contains the attribute `det_class`.

**Comment by powlook** [comment]
Hi @zhouzaida,

My config does not have have the attribute det_class.

**Comment by liguopeng0923** [comment]
I encounter this question too, but I can't solve it  by this method

**Comment by zhouzaida** [comment]
Hi @zdasadsadadadsw , what is your mmcv-full version and what commands did you use to install mmcv-full?

**Comment by wwcc1107** [comment]
what is your mmcv-full verson,my prtorch == 1.3.0+cu100,and torchvision == 0.4.1+cu100,i meet the problem:AssertionError: ca_forward miss in module _ext

**Comment by wangyi84** [comment]
please check your pytorch version. My pytorch==1.6.0 torchvision==0.7.0 MMCV==1.2.0, and I solve the problem.
