### ISSUE TITLE
Successfully installed mmcv-full-1.3.9 but import mmcv with error: libwebp.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JunMa11** [open-mmlab/mmcv#1677]
Dear mmcv Team,

Thanks for the awesome work.

I successfully installed `mmcv` with 

> pip install mmcv-full==1.3.9 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html

```python
Building wheels for collected packages: mmcv-full
  Building wheel for mmcv-full (setup.py) ... done
  Created wheel for mmcv-full: filename=mmcv_full-1.3.9-cp38-cp38-linux_x86_64.whl size=21620199 sha256=daa5abadc7e47c9c27ee56d47f5efb0f373226208609018e898a5f6b9551cc41
  Stored in directory: /home/jma/.cache/pip/wheels/92/40/49/924b36c17271363271cb4c1dbf3fa726d207d3cdeb4749e09f
Successfully built mmcv-full
Installing collected packages: mmcv-full
Successfully installed mmcv-full-1.3.9
```

But the `import mmcv` failed.

```python
(mmseg1-8) [jma@cedar1 pathology]$ python
Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mmcv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jma/anaconda3/envs/mmseg1-8/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/jma/anaconda3/envs/mmseg1-8/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 4, in <module>
    from .io import dump, load, register_handler
  File "/home/jma/anaconda3/envs/mmseg1-8/lib/python3.8/site-packages/mmcv/fileio/io.py", line 4, in <module>
    from ..utils import is_list_of, is_str
  File "/home/jma/anaconda3/envs/mmseg1-8/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 39, in <module>
    from .env import collect_env
  File "/home/jma/anaconda3/envs/mmseg1-8/lib/python3.8/site-packages/mmcv/utils/env.py", line 8, in <module>
    import cv2
  File "/home/jma/anaconda3/envs/mmseg1-8/lib/python3.8/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libwebp.so.7: cannot open shared object file: No such file or directory
```

I'm sure that the cuda and torch versions are correct. 

> conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge -y

Could you guide me to fix this problem?

Thank you very much.

Kindest regards,
Jun

**Comment by JunMa11** [comment]
Hi @zhouzaida ,

It is `opencv-python     4.5.1.48`.

**Comment by zhouzaida** [comment]
It seems that the OpenCV was not installed correctly. Could you try to re-install it?

**Comment by JunMa11** [comment]
Hi @zhouzaida ,

Thanks for your help.
The reason is that conda does not work well on my server. I change to use `virtualenv` to manage the environment and it works!
