### ISSUE TITLE
'mmcv' has no attribute 'mkdir_or_exist'

### ISSUE THREAD

**Issue by ChenQX1** [open-mmlab/mmcv#1712]
```{python}
from mmpose.datasets import build_dataset
from mmpose.models import build_posenet
from mmpose.apis import train_model
import mmcv

datasets = [build_dataset(cfg.data.train)]
model = build_posenet(cfg.model)
mmcv.mkdir_or_exist(cfg.work_dir)
train_model(model, datasets, cfg, distributed=False, validate=True, meta=dict())
```
When executing the last line, the python throws an error.
Details are listed below:
```{shell}
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_937/240955681.py in <module>
     14 
     15 # train model
---> 16 train_model(
     17     model, datasets, cfg, distributed=False, validate=True, meta=dict())

~/a1/mmpose/mmpose/apis/train.py in train_model(model, dataset, cfg, distributed, validate, timestamp, meta)
    190     elif cfg.load_from:
    191         runner.load_checkpoint(cfg.load_from)
--> 192     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)

/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py in run(self, data_loaders, workflow, max_epochs, **kwargs)
    125                     if mode == 'train' and self.epoch >= self._max_epochs:
    126                         break
--> 127                     epoch_runner(data_loaders[i], **kwargs)
    128 
    129         time.sleep(1)  # wait for some hooks like loggers to finish

/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py in train(self, data_loader, **kwargs)
     52             self._iter += 1
     53 
---> 54         self.call_hook('after_train_epoch')
     55         self._epoch += 1
     56 

/opt/conda/lib/python3.8/site-packages/mmcv/runner/base_runner.py in call_hook(self, fn_name)
    305             fn_name (str): The function name in each hook to be called, such as
    306                 "before_train_epoch".
--> 307         """
    308         for hook in self._hooks:
    309             getattr(hook, fn_name)(self)

/opt/conda/lib/python3.8/site-packages/mmcv/runner/hooks/checkpoint.py in after_train_epoch(self, runner)
    114             if self.sync_buffer:
    115                 allreduce_params(runner.model.buffers())
--> 116             self._save_checkpoint(runner)
    117 
    118     @master_only

/opt/conda/lib/python3.8/site-packages/mmcv/runner/dist_utils.py in wrapper(*args, **kwargs)
     92         rank, _ = get_dist_info()
     93         if rank == 0:
---> 94             return func(*args, **kwargs)
     95 
     96     return wrapper

/opt/conda/lib/python3.8/site-packages/mmcv/runner/hooks/checkpoint.py in _save_checkpoint(self, runner)
    119     def _save_checkpoint(self, runner):
    120         """Save the current checkpoint and delete unwanted checkpoint."""
--> 121         runner.save_checkpoint(
    122             self.out_dir, save_optimizer=self.save_optimizer, **self.args)
    123         if runner.meta is not None:

/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py in save_checkpoint(self, out_dir, filename_tmpl, save_optimizer, meta, create_symlink)
    167         filepath = osp.join(out_dir, filename)
    168         optimizer = self.optimizer if save_optimizer else None
--> 169         save_checkpoint(self.model, filepath, optimizer=optimizer, meta=meta)
    170         # in some environments, `os.symlink` is not supported, you may need to
    171         # set `create_symlink` to False

/opt/conda/lib/python3.8/site-packages/mmcv/runner/checkpoint.py in save_checkpoint(model, filename, optimizer, meta, file_client_args)
    708         except exception.NodeNotFoundError:
    709             model = root.create_training_model(model_dir)
--> 710         with TemporaryDirectory() as tmp_dir:
    711             checkpoint_file = osp.join(tmp_dir, model_name)
    712             with open(checkpoint_file, 'wb') as f:

/opt/conda/lib/python3.8/site-packages/mmcv/fileio/file_client.py in put(self, obj, filepath)
   1016             obj (bytes): Data to be written.
   1017             filepath (str or Path): Path to write data.
-> 1018         """
   1019         self.client.put(obj, filepath)
   1020 

/opt/conda/lib/python3.8/site-packages/mmcv/fileio/file_client.py in put(self, obj, filepath)
    547             obj (bytes): Data to be written.
    548             filepath (str or Path): Path to write data.
--> 549         """
    550         mmcv.mkdir_or_exist(osp.dirname(filepath))
    551         with open(filepath, 'wb') as f:

AttributeError: module 'mmcv' has no attribute 'mkdir_or_exist'
```
What should I do to fix this?
By the way, I have reinstalled mmcv with this command
```{shell}
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html
```
The mmcv-full version is "1.4.4"

**Comment by HAOCHENYE** [comment]
Does your running directory contain a folder with the same name as mmcv?

**Comment by ChenQX1** [comment]
> 

Well, I found that my script changed the runtime directory so the error occurred. There is no problem now. thx.

**Comment by SSSilvester** [comment]
hello，I have also encountered this problem.Can you help me out？

Traceback (most recent call last):
  File "/10T/students/master/2024/yinrx/sese/ST-DASegNet-main/123242131.py", line 11, in <module>
    main()
  File "/10T/students/master/2024/yinrx/sese/ST-DASegNet-main/123242131.py", line 9, in main
    mmcv.mkdir_or_exist(osp.join(out_dir, 'img_dir', 'train'))
AttributeError: module 'mmcv' has no attribute 'mkdir_or_exist'

Process finished with exit code 1

**Comment by Serzhanov** [comment]
It's `from mmcv.utils.path import mkdir_or_exist`  I guess, depends on your mmcv version.Here is the documentation

[](https://mmcv.readthedocs.io/en/v1.3.7/_modules/mmcv/utils/path.html?highlight=mkdir_or_exist)
