### ISSUE TITLE
mmcv-full on Jetson Nano

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [open-mmlab/mmcv#1720]
```
Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/nano4g/mmcv/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
running develop
running egg_info
writing mmcv_full.egg-info/PKG-INFO
writing dependency_links to mmcv_full.egg-info/dependency_links.txt
writing requirements to mmcv_full.egg-info/requires.txt
writing top-level names to mmcv_full.egg-info/top_level.txt
reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
running build_ext
building 'mmcv._ext' extension
creating /home/nano4g/mmcv/build
creating /home/nano4g/mmcv/build/temp.linux-aarch64-3.6
creating /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv
creating /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops
creating /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc
creating /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch
creating /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/cpu
creating /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/cuda
Emitting ninja build file /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/build.ninja...
Compiling objects...
Using envvar MAX_JOBS (4) as the number of workers...
[1/102] c++ -MMD -MF /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/pybind.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DMMCV_WITH_CUDA -I/home/nano4g/mmcv/mmcv/ops/csrc/common -I/home/nano4g/mmcv/mmcv/ops/csrc/common/cuda -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/TH -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/nano4g/mmcv/mmcv/ops/csrc/pytorch/pybind.cpp -o /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/pybind.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1
FAILED: /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/pybind.o
c++ -MMD -MF /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/pybind.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DMMCV_WITH_CUDA -I/home/nano4g/mmcv/mmcv/ops/csrc/common -I/home/nano4g/mmcv/mmcv/ops/csrc/common/cuda -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/TH -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/nano4g/mmcv/mmcv/ops/csrc/pytorch/pybind.cpp -o /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/pybind.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
[2/102] c++ -MMD -MF /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/border_align.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DMMCV_WITH_CUDA -I/home/nano4g/mmcv/mmcv/ops/csrc/common -I/home/nano4g/mmcv/mmcv/ops/csrc/common/cuda -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/TH -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/nano4g/mmcv/mmcv/ops/csrc/pytorch/border_align.cpp -o /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/border_align.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1
FAILED: /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/border_align.o
c++ -MMD -MF /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/border_align.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DMMCV_WITH_CUDA -I/home/nano4g/mmcv/mmcv/ops/csrc/common -I/home/nano4g/mmcv/mmcv/ops/csrc/common/cuda -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/TH -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/nano4g/mmcv/mmcv/ops/csrc/pytorch/border_align.cpp -o /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/border_align.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
[3/102] c++ -MMD -MF /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/fused_bias_leakyrelu.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DMMCV_WITH_CUDA -I/home/nano4g/mmcv/mmcv/ops/csrc/common -I/home/nano4g/mmcv/mmcv/ops/csrc/common/cuda -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/TH -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/nano4g/mmcv/mmcv/ops/csrc/pytorch/fused_bias_leakyrelu.cpp -o /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/fused_bias_leakyrelu.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1
[4/102] c++ -MMD -MF /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/nms_rotated.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DMMCV_WITH_CUDA -I/home/nano4g/mmcv/mmcv/ops/csrc/common -I/home/nano4g/mmcv/mmcv/ops/csrc/common/cuda -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/TH -I/home/nano4g/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c -c /home/nano4g/mmcv/mmcv/ops/csrc/pytorch/nms_rotated.cpp -o /home/nano4g/mmcv/build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/nms_rotated.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/nano4g/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1723, in _run_ninja_build
    env=env)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nano4g/mmcv/setup.py", line 390, in <module>
    zip_safe=False)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 36, in run
    self.install_for_development()
  File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/home/nano4g/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/nano4g/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 735, in build_extensions
    build_ext.build_extensions(self)
  File "/home/nano4g/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/nano4g/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 565, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/nano4g/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1404, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/nano4g/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

----------------------------------------

```

I am trying to build mmcv on Jetson nano. I got above error while building. Some times it strucks at following window.

```
(fyp1) fyp@fyp-desktop:~/Desktop/Jetson install/mmcv$ MMCV_WITH_OPS=1 pip install -v -e .
Using pip 21.3.1 from /home/fyp/miniforge3/envs/fyp1/lib/python3.6/site-packages/pip (python 3.6)
Obtaining file:///home/fyp/Desktop/Jetson%20install/mmcv
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-yb77e_x2/mmcv_full.egg-info
  writing /tmp/pip-pip-egg-info-yb77e_x2/mmcv_full.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-yb77e_x2/mmcv_full.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-yb77e_x2/mmcv_full.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-yb77e_x2/mmcv_full.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-yb77e_x2/mmcv_full.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-yb77e_x2/mmcv_full.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  adding license file 'LICENSES.md'
  writing manifest file '/tmp/pip-pip-egg-info-yb77e_x2/mmcv_full.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in /home/fyp/miniforge3/envs/fyp1/lib/python3.6/site-packages (from mmcv-full==1.4.5) (2.4.0)
Requirement already satisfied: numpy in /home/fyp/miniforge3/envs/fyp1/lib/python3.6/site-packages (from mmcv-full==1.4.5) (1.19.5)
Requirement already satisfied: packaging in /home/fyp/miniforge3/envs/fyp1/lib/python3.6/site-packages (from mmcv-full==1.4.5) (21.3)
Requirement already satisfied: Pillow in /home/fyp/miniforge3/envs/fyp1/lib/python3.6/site-packages (from mmcv-full==1.4.5) (6.2.2)
Requirement already satisfied: pyyaml in /home/fyp/miniforge3/envs/fyp1/lib/python3.6/site-packages (from mmcv-full==1.4.5) (6.0)
Requirement already satisfied: yapf in /home/fyp/miniforge3/envs/fyp1/lib/python3.6/site-packages (from mmcv-full==1.4.5) (0.32.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/fyp/miniforge3/envs/fyp1/lib/python3.6/site-packages (from packaging->mmcv-full==1.4.5) (3.0.7)
Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full
    Running command /home/fyp/miniforge3/envs/fyp1/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/fyp/Desktop/Jetson install/mmcv/setup.py'"'"'; __file__='"'"'/home/fyp/Desktop/Jetson install/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    adding license file 'LICENSES.md'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext' extension
    Emitting ninja build file /home/fyp/Desktop/Jetson install/mmcv/build/temp.linux-aarch64-3.6/build.ninja...
    Compiling objects...
    Using envvar MAX_JOBS (4) as the number of workers...
```

How to solve above issue? otherwise, Is it possible to provide a precompiled package for Jetson nano (aarch64 architecture, python3.6, cuda 10.2)?

**Comment by Thevakumar-Luheerathan** [comment]
I solved this issue by removing ninja and compiling again. Installation took 1-1.5hrs of time to complete without ninja. Low memory devices may not be able to use ninja. As it uses all the memory to parallelise its operation. Someone who wants to install mmcv-full on Jetson nano try this. 

Limiting the MAX_JOBS may be also helpful. I did not try that. 
Thank you.

**Comment by 827346462** [comment]
hi, I use jetson XAvier NX .
jetpack:4.6.1
please you sloved this erro?

ERROR: Command errored out with exit status 1:
     command: /home/lcfc/archiconda3/envs/mmdeploy/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lcfc/Public/mmcv/setup.py'"'"'; __file__='"'"'/home/lcfc/Public/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/lcfc/Public/mmcv/
    Complete output (33 lines):
    running develop
    running egg_info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    adding license file 'LICENSES.md'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext' extension
    creating build
    creating build/temp.linux-aarch64-3.6
    creating build/temp.linux-aarch64-3.6/mmcv
    creating build/temp.linux-aarch64-3.6/mmcv/ops
    creating build/temp.linux-aarch64-3.6/mmcv/ops/csrc
    creating build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch
    creating build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/cpu
    creating build/temp.linux-aarch64-3.6/mmcv/ops/csrc/pytorch/cuda
    /home/lcfc/archiconda3/envs/mmdeploy/bin/aarch64-conda-linux-gnu-cc -DNDEBUG -fwrapv -O3 -Wall -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem /home/lcfc/archiconda3/envs/mmdeploy/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/lcfc/archiconda3/envs/mmdeploy/include -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem /home/lcfc/archiconda3/envs/mmdeploy/include -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/lcfc/archiconda3/envs/mmdeploy/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/lcfc/archiconda3/envs/mmdeploy/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/lcfc/archiconda3/envs/mmdeploy/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O3 -fPIC -DMMCV_WITH_CUDA -I/home/lcfc/Public/mmcv/mmcv/ops/csrc/common -I/home/lcfc/Public/mmcv/mmcv/ops/csrc/common/cuda -I/home/lcfc/.local/lib/python3.6/site-packages/torch/include -I/home/lcfc/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/lcfc/.local/lib/python3.6/site-packages/torch/include/TH -I/home/lcfc/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/lcfc/archiconda3/envs/mmdeploy/include/python3.6m -c ./mmcv/ops/csrc/pytorch/riroi_align_rotated.cpp -o build/temp.linux-aarch64-3.6/./mmcv/ops/csrc/pytorch/riroi_align_rotated.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1
    Assembler messages:
    Error: unknown architecture `nocona'

    Error: unrecognized option -march=nocona
    cc1plus: error: unknown value 'nocona' for '-march'
    cc1plus: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8-r native
    cc1plus: error: unknown value 'haswell' for '-mtune'
    cc1plus: note: valid arguments are: cortex-a34 cortex-a35 cortex-a53 cortex-a57 cortex-a72 cortex-a73 thunderx thunderxt88p1 thunderxt88 octeontx octeontx81 octeontx83 thunderxt81 thunderxt83 emag xgene1 falkor qdf24xx exynos-m1 phecda thunderx2t99p1 vulcan thunderx2t99 cortex-a55 cortex-a75 cortex-a76 cortex-a76ae cortex-a77 cortex-a78 cortex-a78ae cortex-a78c cortex-a65 cortex-a65ae cortex-x1 ares neoverse-n1 neoverse-e1 octeontx2 octeontx2t98 octeontx2t96 octeontx2t93 octeontx2f95 octeontx2f95n octeontx2f95mm a64fx tsv110 thunderx3t110 zeus neoverse-v1 saphira neoverse-n2 cortex-a57.cortex-a53 cortex-a72.cortex-a53 cortex-a73.cortex-a35 cortex-a73.cortex-a53 cortex-a75.cortex-a55 cortex-a76.cortex-a55 cortex-r82 generic
    /home/lcfc/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py:369: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    error: command '/home/lcfc/archiconda3/envs/mmdeploy/bin/aarch64-conda-linux-gnu-cc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/lcfc/archiconda3/envs/mmdeploy/bin/python3.6 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lcfc/Public/mmcv/setup.py'"'"'; __file__='"'"'/home/lcfc/Public/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
