### ISSUE TITLE
AttributeError: 'MMDistributedDataParallel' object has no attribute '_sync_params'

### ISSUE THREAD

**Issue by Arjung27** [open-mmlab/mmcv#1754]
I am trying to train a Detector using the latest mmcv version and torch 1.11. I installed mmcv simply by:

```
git clone https://github.com/open-mmlab/mmcv.git
pip install -r requirements/optional.txt
MMCV_WITH_OPS=1 pip install -e .
```
After launching the training script, I get an error:

```
Traceback (most recent call last):
  File "/workspace/Project/launch_training.py", line 190, in <module>
    main()
  File "/workspace/Project/launch_training.py", line 179, in main
    train_detector(
  File "/opt/conda/lib/python3.8/site-packages/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/opt/conda/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 48, in train_step
    self._sync_params()
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MMDistributedDataParallel' object has no attribute '_sync_params'
```
I did some digging into the issue and I found this PR here: https://github.com/pytorch/pytorch/pull/64514 which indicates that _sync_params is deprecated from PyTorch. Is there any plan to fix this issue soon or is there a workaround this?

**Comment by teamwong111** [comment]
Which version of PyTorch do you use? The latest stable PyTorch(1.10.2) still uses this function, as far as I know. We will handle this problem when PyTorch1.11.0 is released.

**Comment by Arjung27** [comment]
I am using PyTorch: 1.11.0

**Comment by LiuXiaoxuanPKU** [comment]
Any updates on this? I met the same problem, and currently, it seems not straightforward to install PyTorch 1.10 other than building from the source. Thanks!

**Comment by teamwong111** [comment]
> Any updates on this? I met the same problem, and currently, it seems not straightforward to install PyTorch 1.10 other than building from the source. Thanks!

We will fix it ASAP. I have submitted a pr.

**Comment by johnson-magic** [comment]
```
step1: uninstall torch
pip uninstall torch torchaudio torchvision

step2: install torch1.9.0
pip install torch==1.9.0+cu102 torchvision==0.10.0+cu102 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

step3:install and rebuild mmcv
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv/
MMCV_WITH_OPS=1 pip install -e .
```
