### ISSUE TITLE
uninstall mmcv

### ISSUE THREAD

**Issue by 54wb** [open-mmlab/mmcv#1820]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

while I have installed mmcv-full (1.3.14) and mmdetection(2.8.0),those is not match so i want to unintall mmcv and install mmcv for version 1.3.17 ,but when i use 
         pip uninstall mmcv-full
there have a error:

Found existing installation: mmcv-full 1.3.14
Uninstalling mmcv-full-1.3.14:
  Would remove:
    /disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/*
    /disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv_full-1.3.14.dist-info/*
Proceed (y/n)? y
ERROR: Exception:
Traceback (most recent call last):
  File "/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/' -> '/tmp/pip-uninstall-p1l1nv4d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/pip/_internal/commands/uninstall.py", line 88, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 658, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/pip/_internal/req/req_uninstall.py", line 400, in remove
    moved.stash(path)
  File "/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/pip/_internal/req/req_uninstall.py", line 289, in stash
    renames(path, new_path)
  File "/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 347, in renames
    shutil.move(old, new)
  File "/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/shutil.py", line 578, in move
    rmtree(src)
  File "/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/disk1/lqy/home/anaconda3/envs/openmmlab/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '__init__.py'

**Comment by HAOCHENYE** [comment]
Hi, it seems like a permission error. What's your system environment， WSL, docker, or normal Linux system? Can you pip uninstall other packages successfully?
