### ISSUE TITLE
key, val = kv.split('=', maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by LZYmixiu** [open-mmlab/mmcv#1840]
I defined a new config that attempt to train on my custom dataset (VOC format).
The command  I used is : python tools/train.py configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_mfdataset.py --options model.pretrained = checkpoints/swin_tiny_patch4_window7_224.pth  --gpus=1 --gpu-ids=1

The config I defined is:
```python
base_ = [
    '../_base_/models/upernet_swin.py', '../_base_/datasets/pascal_voc12.py',
    '../_base_/default_runtime.py', '../_base_/schedules/schedule_160k.py'
]
data_root ='/storage/zdxy01/dataset/dataset'
model = dict(
    backbone=dict(
        embed_dim=96,
        depths=[2, 2, 6, 2],
        num_heads=[3, 6, 12, 24],
        window_size=7,
        ape=False,
        drop_path_rate=0.3,
        patch_norm=True,
        use_checkpoint=False
    ),
    decode_head=dict(
        in_channels=[96, 192, 384, 768],
        num_classes=150
    ),
    auxiliary_head=dict(
        in_channels=384,
        num_classes=150
    ))

# AdamW optimizer, no weight decay for position embedding & layer norm in backbone
optimizer = dict(_delete_=True, type='AdamW', lr=0.00006, betas=(0.9, 0.999), weight_decay=0.01,
                 paramwise_cfg=dict(custom_keys={'absolute_pos_embed': dict(decay_mult=0.),
                                                 'relative_position_bias_table': dict(decay_mult=0.),
                                                 'norm': dict(decay_mult=0.)}))

lr_config = dict(_delete_=True, policy='poly',
                 warmup='linear',
                 warmup_iters=1500,
                 warmup_ratio=1e-6,
                 power=1.0, min_lr=0.0, by_epoch=False)

# By default, models are trained on 8 GPUs with 2 images per GPU
data=dict(samples_per_gpu=2,
    train=dict(

            data_root=data_root,
            img_dir='images',
            ann_dir='labels',
            split='train.txt'),
    val=dict(
        
        data_root=data_root,
        img_dir='images',
        ann_dir='labels',
        split='val.txt',
        ),
    test=dict(
        
        data_root=data_root,
        img_dir='images',
        ann_dir='labels',
        split='val.txt',
        ))
```

Is there have any problem?
Or there is have another way to train a VOC format dataset with swin？
Thank you for your concern!

**Comment by LZYmixiu** [comment]
This error encouraged by:
```python
mmcv/utils/config.py", line 457, in __call__
    key, val = kv.split('=', maxsplit=1)
```

**Comment by zhouzaida** [comment]
Hi, the command should be `python tools/train.py configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_mfdataset.py --cfg-options model.pretrained = checkpoints/swin_tiny_patch4_window7_224.pth --gpus=1 --gpu-ids=1`

**Comment by christian-hiebl** [comment]
Note that '--gpus=1' and '--gpu-ids=1' is no longer allowed and will return an argument error. Instead please use '--gpus' or '--gpu-ids' exclusively.

**Comment by imadalishah** [comment]
I am getting following error for this command in Google Colab:
!python tools/train.py configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_mfdataset.py --cfg-options model.pretrained = checkpoints/swin_tiny_patch4_window7_224.pth --gpus=1 --gpu-ids=1

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 87, in main
    args = parse_args()
  File "tools/train.py", line 71, in parse_args
    args = parser.parse_args()
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1886, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/config.py", line 739, in __call__
    key, val = kv.split('=', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

what is the issue, I've installed mmcv-full==1.3.17

**Comment by sammilei** [comment]
I got `not enough values to unpack` error too. The cause was the data path I gave was dir of dir. Once I gave the correct path of the img and label in the config file. This error was gone.

**Comment by yys-abu** [comment]
> This error encouraged by:
> 
> ```python
> mmcv/utils/config.py", line 457, in __call__
>     key, val = kv.split('=', maxsplit=1)
> ```

Have you found a solution yet？

**Comment by imadalishah** [comment]
Yes, I resolved the issue buts too old now for remembering the exact solution.
However, the issue was with the incompatibility issue of Python environment and the mmc. Try downgrade your Python environment.
<important> Check the version of mmc for supported in your current Python version

**Comment by yys-abu** [comment]
Hello，
I lowered the Python version to 3.7 and then installed mmcv and others according to the official installation of mmcv, resulting in the following error
C:\Anoconda\envs\mmcv\lib\site-packages\mmcv\arraymisc\quantization.py:4: UserWarning: The NumPy module was reloaded (imported a second time). This can in some cases result in small but subtle issues and is discouraged.
&nbsp; import numpy as np
Traceback (most recent call last):
&nbsp; File "C:/med/tools/train.py", line 12, in <module&gt;
&nbsp; &nbsp; from mmcls.apis import init_random_seed, set_random_seed, train_model
&nbsp; File "C:\Anoconda\envs\mmcv\lib\site-packages\mmcls\apis\__init__.py", line 2, in <module&gt;
&nbsp; &nbsp; from .inference import inference_model, init_model, show_result_pyplot
&nbsp; File "C:\Anoconda\envs\mmcv\lib\site-packages\mmcls\apis\inference.py", line 8, in <module&gt;
&nbsp; &nbsp; from mmcv.runner import load_checkpoint
&nbsp; File "C:\Anoconda\envs\mmcv\lib\site-packages\mmcv\runner\__init__.py", line 3, in <module&gt;
&nbsp; &nbsp; from .base_runner import BaseRunner
&nbsp; File "C:\Anoconda\envs\mmcv\lib\site-packages\mmcv\runner\base_runner.py", line 17, in <module&gt;
&nbsp; &nbsp; from .checkpoint import load_checkpoint
&nbsp; File "C:\Anoconda\envs\mmcv\lib\site-packages\mmcv\runner\checkpoint.py", line 17, in <module&gt;
&nbsp; &nbsp; import torchvision
&nbsp; File "C:\Anoconda\envs\mmcv\lib\site-packages\torchvision\__init__.py", line 7, in <module&gt;
&nbsp; &nbsp; from torchvision import datasets
&nbsp; File "C:\Anoconda\envs\mmcv\lib\site-packages\torchvision\datasets\__init__.py", line 1, in <module&gt;
&nbsp; &nbsp; from .lsun import LSUN, LSUNClass
&nbsp; File "C:\Anoconda\envs\mmcv\lib\site-packages\torchvision\datasets\lsun.py", line 2, in <module&gt;
&nbsp; &nbsp; from PIL import Image
&nbsp; File "C:\Anoconda\envs\mmcv\lib\site-packages\PIL\Image.py", line 100, in <module&gt;
&nbsp; &nbsp; from . import _imaging as core
ImportError: DLL load failed: 找不到指定的模块。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmcv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月9日(星期三) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmcv] key, val = kv.split('=', maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1) (Issue #1840)





 
Yes, I resolved the issue buts too old now for remembering the exact solution.
 However, the issue was with the incompatibility issue of Python environment and the mmc. Try downgrade your Python environment.
  Check the version of mmc for supported in your current Python version

**Comment by imadalishah** [comment]
can you share what commands are you using?
If you're using Google Colab then after downgrading the environment you require a restart. Also, ensure that the intended environment is active, before trying to install mmc.

One more important point, check the documentation for stable Python as well as mmc versions; install only those.

**Comment by yys-abu** [comment]
Hello,&nbsp;
I'm glad you could reply to me,I am using pycharm to run directly. I have reinstalled the virtual environment according to the official configuration, but there are still errors：

&nbsp; File "C:\Anaconda\envs\DL\lib\site-packages\mmcv\utils\config.py", line 739, in __call__
&nbsp; &nbsp; key, val = kv.split('=', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmcv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月10日(星期四) 凌晨2:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmcv] key, val = kv.split('=', maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1) (Issue #1840)





 
can you share what commands are you using?
 If you're using Google Colab then after downgrading the environment you require a restart. Also, ensure that the intended environment is active, before trying to install mmc.
 
One more important point, check the documentation for stable Python as well as mmc versions; install only those.

**Comment by yys-abu** [comment]
if I print kv，it will show:
C:\med\configs\vit-b16_vpt\in21k-vitb16_vpt1_bs4_lr6e-4_1-shot_chest.py




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmcv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月10日(星期四) 凌晨2:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmcv] key, val = kv.split('=', maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1) (Issue #1840)





 
can you share what commands are you using?
 If you're using Google Colab then after downgrading the environment you require a restart. Also, ensure that the intended environment is active, before trying to install mmc.
 
One more important point, check the documentation for stable Python as well as mmc versions; install only those.

**Comment by imadalishah** [comment]
> Hello,&nbsp; I'm glad you could reply to me,I am using pycharm to run directly. I have reinstalled the virtual environment according to the official configuration, but there are still errors： &nbsp; File "C:\Anaconda\envs\DL\lib\site-packages\mmcv\utils\config.py", line 739, in __call__ &nbsp; &nbsp; key, val = kv.split('=', maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "open-mmlab/mmcv" ***@***.***&gt;; 发送时间:&nbsp;2023年8月10日(星期四) 凌晨2:12 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [open-mmlab/mmcv] key, val = kv.split('=', maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1) (Issue #1840) can you share what commands are you using? If you're using Google Colab then after downgrading the environment you require a restart. Also, ensure that the intended environment is active, before trying to install mmc. One more important point, check the documentation for stable Python as well as mmc versions; install only those. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Error seems to be related to the way you are trying to split a string using the `split` function. The `split` function expects a string in the form of `"key=value"` and separates it into two parts based on the equal sign. The error message is indicating that the `split` function is not receiving the expected format with both a key and a value separated by an equal sign.

To resolve this issue, it should be something like:

```python
key_value_pair = "key=value"
key, value = key_value_pair.split('=')
```

Make sure that the `key_value_pair` string contains both a key and a value separated by an equal sign. If you are parsing lines from a configuration file, ensure that each line follows the `"key=value"` format.

**Comment by imadalishah** [comment]
> 

kindly explain, what you want to do and what are the issues being faced.
I could not understand it

**Comment by imadalishah** [comment]
> if I print kv，it will show: C:\med\configs\vit-b16_vpt\in21k-vitb16_vpt1_bs4_lr6e-4_1-shot_chest.py
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "open-mmlab/mmcv" ***@***.***&gt;; 发送时间:&nbsp;2023年8月10日(星期四) 凌晨2:12 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [open-mmlab/mmcv] key, val = kv.split('=', maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1) (Issue #1840) can you share what commands are you using? If you're using Google Colab then after downgrading the environment you require a restart. Also, ensure that the intended environment is active, before trying to install mmc. One more important point, check the documentation for stable Python as well as mmc versions; install only those. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

kindly explain, what you want to do and what are the issues being faced.
I could not understand it

**Comment by yys-abu** [comment]
Hello,&nbsp;
I am glad to receive your reply. The reason for the error was the addition of -- cfg before the running command.This is really a low-level mistake.For a beginner like me, this is really a low-level mistake.
Yours sincerely




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmcv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月16日(星期三) 上午6:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmcv] key, val = kv.split('=', maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1) (Issue #1840)





  
Hello,&nbsp; I'm glad you could reply to me,I am using pycharm to run directly. I have reinstalled the virtual environment according to the official configuration, but there are still errors： &nbsp; File "C:\Anaconda\envs\DL\lib\site-packages\mmcv\utils\config.py", line 739, in call &nbsp; &nbsp; key, val = kv.split('=', maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1)
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "open-mmlab/mmcv" @.&gt;; 发送时间:&nbsp;2023年8月10日(星期四) 凌晨2:12 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [open-mmlab/mmcv] key, val = kv.split('=', maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1) (Issue #1840) can you share what commands are you using? If you're using Google Colab then after downgrading the environment you require a restart. Also, ensure that the intended environment is active, before trying to install mmc. One more important point, check the documentation for stable Python as well as mmc versions; install only those. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
Error seems to be related to the way you are trying to split a string using the split function. The split function expects a string in the form of "key=value" and separates it into two parts based on the equal sign. The error message is indicating that the split function is not receiving the expected format with both a key and a value separated by an equal sign.
 
To resolve this issue, it should be something like:
 key_value_pair = "key=value" key, value = key_value_pair.split('=')
 
Make sure that the key_value_pair string contains both a key and a value separated by an equal sign. If you are parsing lines from a configuration file, ensure that each line follows the "key=value" format.
