### ISSUE TITLE
TypeError: cfg_dict must be a dict, but got <class 'mmcv.utils.config.Config'>

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mmcv#1986]
I tried to use gridsearch with `mim, version 0.1.5`
```bash
PYTHONPATH='.'$PYTHONPATH mim gridsearch mmcls configs/benchmarks/classification/imagenet/resnet50_8xb512-coslr-90e_in1k.py --gpus 8 --work-dir protocal_simsiam_grid_search --search-args '--optimizer.lr 1.0 1.2 1.4 1.6 1.8 2.0'
```

The error is:
```
Traceback (most recent call last):
  File "/home/tiger/.local/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/mim/commands/gridsearch.py", line 142, in cli
    other_args=other_args)
  File "/home/tiger/.local/lib/python3.7/site-packages/mim/commands/gridsearch.py", line 322, in gridsearch
    cur_cfg = Config(cp.deepcopy(cfg))
  File "/home/tiger/.local/lib/python3.7/site-packages/mmcv/utils/config.py", line 387, in __init__
    raise TypeError: cfg_dict must be a dict, but got <class 'mmcv.utils.config.Config'>
```

My environment is
```
Package         Version    Source
--------------  ---------  ----------------------------------------------
mmcls           0.23.0     https://github.com/open-mmlab/mmclassification
mmcv-full       1.5.0      https://github.com/open-mmlab/mmcv
mmdet           2.24.1     https://github.com/open-mmlab/mmdetection
mmsegmentation  0.24.1     http://github.com/open-mmlab/mmsegmentation
mmselfsup       0.9.0      /home/tiger/code/SSL/SelfSup
```

**Comment by zhouzaida** [comment]
Hi @mitming , thanks for your feedback. It is a bug of mim. We will fix it.
