### ISSUE TITLE
AttributeError: 'Version' object has no attribute 'release'

### ISSUE THREAD

**Issue by KuofengGao** [open-mmlab/mmcv#2108]
Hi, team,

When I use mmdetection3d to create KITTI dataset, I got error `AttributeError: 'Version' object has no attribute 'release'`. I tried three methods to solve it but it failed.
1. I tried `pip install -U setuptools`.
2. I tried `git clone https://github.com/open-mmlab/mmcv.git`, and run `python setup.py develop` to reinstall mmcv.
3. I tried download `[./mmcv_full-1.4.0-cp36-cp36m-manylinux1_x86_64.whl](https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/mmcv_full-1.4.0-cp36-cp36m-manylinux1_x86_64.whl)` from https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html to reinstall mmcv.
All the above methods cannot fix it so could you please help me solve my problem?

My environment is python==3.6.4, cuda==10.1, torch==1.8.0, torchvison==0.9.0, mmcv_full==1.4.0
```
>>> import mmcv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ssd2/vis/gaokuofeng/anaconda3/lib/python3.6/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/ssd2/vis/gaokuofeng/anaconda3/lib/python3.6/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/ssd2/vis/gaokuofeng/anaconda3/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/ssd2/vis/gaokuofeng/anaconda3/lib/python3.6/site-packages/mmcv/utils/__init__.py", line 49, in <module>
    from .hub import load_url
  File "/ssd2/vis/gaokuofeng/anaconda3/lib/python3.6/site-packages/mmcv/utils/hub.py", line 9, in <module>
    if TORCH_VERSION != 'parrots' and digit_version(TORCH_VERSION) < digit_version(
  File "/ssd2/vis/gaokuofeng/anaconda3/lib/python3.6/site-packages/mmcv/utils/version_utils.py", line 24, in digit_version
    assert version.release, f'failed to parse version {version_str}'
AttributeError: 'Version' object has no attribute 'release'
```

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help.

**Comment by HAOCHENYE** [comment]
You can install mmcv-full via openmim.

```bash
pip install -U openmim
mim install mmcv-full
```
