### ISSUE TITLE
Getting RuntimeError: box_iou_rotated_impl : implementation for device cuda:0 not found.

### ISSUE THREAD

**Issue by balandongiv** [open-mmlab/mmcv#2110]
When running [the](
https://github.com/open-mmlab/mmcv/blob/master/.dev_scripts/check_installation.py)  `check_installation.py`, the compiler return the following

```
Start checking the installation of mmcv-full ...
CPU ops were compiled successfully.
Traceback (most recent call last):
  File "/home/thisuser/IdeaProjects/ocr_classification/0_check_mmcv_full.py", line 37, in <module>
    check_installation()
  File "/home/thisuser/IdeaProjects/ocr_classification/0_check_mmcv_full.py", line 29, in check_installation
    box_iou_rotated(boxes1, boxes2)
  File "/home/thisuser/anaconda3/envs/dlib/lib/python3.8/site-packages/mmcv/ops/box_iou_rotated.py", line 144, in box_iou_rotated
    ext_module.box_iou_rotated(
RuntimeError: box_iou_rotated_impl: implementation for device cuda:0 not found.
```

Running `torch.cuda.is_available()` return ` True`

For context, the `mmcv-full` was installed as following

`pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.12.0/index.html`
 and the log indicate the `mmcv-full` is properly installed as shown below

```
Installing collected packages: yapf, addict, pyyaml, pyparsing, opencv-python, packaging, mmcv-full
Successfully installed addict-2.4.0 mmcv-full-1.5.3 opencv-python-4.6.0.66 packaging-21.3 pyparsing-3.0.9 pyyaml-6.0 yapf-0.32.0
```

Also, the `cuda` path is set properly

```
export PATH="/usr/local/cuda-11.6/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-11.6/lib64:$LD_LIBRARY_PATH"
```

May I know how to resolve this issue?

Thanks for the help

**Comment by zhouzaida** [comment]
It seems like cuda ops were not compiled successfully.

**Comment by balandongiv** [comment]
Thanks for the reply @zhouzaida , before I take a extreme measure (i.e., reformatting the system), is there any litmus test to verify that cuda ops were not compiled successfully?

I am following this [tutorial](https://www.how2shout.com/linux/how-to-install-cuda-on-ubuntu-20-04-lts-linux/) and able to create the CUDA C program successfully.  May I know whether if able to create CUDA C code successfully a good indicator that the `cuda ops` is actually compiled successfully?

**Comment by zhouzaida** [comment]
Hi, could you try to build mmcv-full from source? Here is a [tutorial](https://mmcv.readthedocs.io/en/latest/get_started/build.html#build-on-linux-or-macos).

**Comment by balandongiv** [comment]
Hi @zhouzaida , thanks for the tips. The `check_installation` indicated `CUDA-Ops` were compiled successfully. But, this lead to another question why the recommended way of installing is not working


```
Start checking the installation of mmcv-full ...
CPU ops were compiled successfully.
CUDA ops were compiled successfully.
mmcv-full has been installed successfully.

Environment information:
------------------------------------------------------------
sys.platform: linux
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda-11.6
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.0+cu116
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.0+cu116
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.6
------------------------------------------------------------


Process finished with exit code 0
```

**Comment by zhouzaida** [comment]
It seems like pip used the wheel in cache to install mmcv-full. You can try again with the following commands:

```bash
pip install mmcv-full  --no-cache-dir -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.12.0/index.html
```

BTW, we have not provided pre-built packages for torch1.12 so the above command will install mmcv-full from souce.

**Comment by balandongiv** [comment]
Thanks for insight @zhouzaida
