### ISSUE TITLE
Oriented RepPoints: ImportError: cannot import name 'chamfer_distance' from 'mmcv.ops'

### ISSUE THREAD

**Issue by xypu98** [open-mmlab/mmcv#2111]
I try to train a model of  Oriented-RepPoints CVPR2022.
It seems to be the version problem of mmcv, should I update the version or reinstall some environments?
Thanks!
The error occurs as :
Traceback (most recent call last):
  File "./tools/train.py", line 18, in <module>
    from mmrotate.apis import train_detector
  File "/remote-home/pxy/mmrotate/mmrotate/__init__.py", line 6, in <module>
    from .models import *  # noqa: F401, F403
  File "/remote-home/pxy/mmrotate/mmrotate/models/__init__.py", line 8, in <module>
    from .dense_heads import *  # noqa: F401, F403
  File "/remote-home/pxy/mmrotate/mmrotate/models/dense_heads/__init__.py", line 8, in <module>
    from .oriented_reppoints_head import OrientedRepPointsHead
  File "/remote-home/pxy/mmrotate/mmrotate/models/dense_heads/oriented_reppoints_head.py", line 8, in <module>
    from mmcv.ops import DeformConv2d, chamfer_distance, min_area_polygons
ImportError: cannot import name 'chamfer_distance' from 'mmcv.ops' (/remote-home/pxy/new/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py)

**Comment by zhouzaida** [comment]
Hi, what is your mmcv version?

**Comment by xypu98** [comment]
> 

Thanks for your reply.
I have solved this error by uninstalling mmcv and reinstalling mmcv and mmdet.
Now my mmcv version is 1.5.3 and mmdet version is 2.25.0.
It works.
