### ISSUE TITLE
from mmcv.ops import RoIPool error

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [open-mmlab/mmcv#2145]
I have searched related issues but cannot get the expected help.
Traceback (most recent call last):
  File "D:\widows_mm\mmdetection\demo\image_demo.py", line 5, in <module>
    from mmdet.apis import (async_inference_detector, inference_detector,
  File "d:\widows_mm\mmdetection\mmdet\apis\__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "d:\widows_mm\mmdetection\mmdet\apis\inference.py", line 8, in <module>
    from mmcv.ops import RoIPool
  File "D:\Anaconda3\envs\mmdeploy\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "D:\Anaconda3\envs\mmdeploy\lib\site-packages\mmcv\ops\assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\Anaconda3\envs\mmdeploy\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\Anaconda3\envs\mmdeploy\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的程序。
mmcv-full 1.4.0 python 3.9 cuda 10.2

**Comment by HAOCHENYE** [comment]
Hi, it seems you failed to install `mmcv-full` correctly. What's your install steps?  We suggest using `openmim` to install `mmcv-full` 
```bash
pip install -U openmim
mim install mmcv-full
```

**Comment by ELongking** [comment]
Hi @jiaqizhang123-stack , I'm facing the same problem as you do. Before that i've tried many many install or uninstall pipelines like [https://github.com/open-mmlab/mmcv/issues/1594](url). Now this is my solving method:
```
(delete previous env which contains mmcv or mmdet or mmseg... on windows10)
(create a whole new env) conda create -n your_env_name python=3.9
(install pytorch, for myself only needed cpu-version to infer) conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cpuonly
(use mim) pip install -U openmim
(install mmcv) mim install mmcv-full
(install mmdet) pip install mmdet
(install opencv) pip install opencv-python
finally mmcv==1.6.1 mmdet==2.25.1 installed, and it works for me.
```
---------------------------------------------------------------
Besides, for myself, if i use like
`pip install mmcv-full=={mmcv_version} -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html`
without mim, it failed all the time
