### ISSUE TITLE
ImportError: DLL load failed: 找不到指定的程序。

### ISSUE THREAD

**Issue by endaoguansanlu** [open-mmlab/mmcv#2147]
D:\Python\lib\site-packages\mmcv\cnn\bricks\transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "e:/MyModel/train.py", line 13, in <module>
    from mmsegmentation.mmseg.apis import set_random_seed, train_segmentor
  File "e:\MyModel\mmsegmentation\mmseg\apis\__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
    from .decode_head import BaseDecodeHead
  File "e:\mymodel\mmsegmentation\mmseg\models\decode_heads\decode_head.py", line 11, in <module>
    from ..losses import accuracy
  File "e:\mymodel\mmsegmentation\mmseg\models\losses\__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "e:\mymodel\mmsegmentation\mmseg\models\losses\focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "D:\Python\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\Python\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 12, in <module>
    ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
  File "D:\Python\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: 找不到指定的程序。

I have this problem when I use mmsegmentation, do you know why, thanks！！！

**Comment by HAOCHENYE** [comment]
Hi~, It seems you don't install `mmcv-full` correctly. Please let us know how you install `mmcv-full`

**Comment by endaoguansanlu** [comment]
> Hi~, It seems you don't install `mmcv-full` correctly. Please let us know how you install `mmcv-full`

i ues the command that 
pip install -U openmim
mim install mmcv-full

**Comment by HAOCHENYE** [comment]
> > Hi~, It seems you don't install `mmcv-full` correctly. Please let us know how you install `mmcv-full`
> 
> i ues the command that pip install -U openmim mim install mmcv-full

It seems a version error. Does your repo version matches with the version of `mmcv-full`?
