### ISSUE TITLE
EOL while scanning string literal

### ISSUE THREAD

**Issue by medlen** [open-mmlab/mmcv#2228]
I found this error when I insert the code "print(cfg.pretty_text)" into https://github.com/open-mmlab/mmdetection3d/blob/master/tools/train.py#L249 . 
```
    if cfg.checkpoint_config is not None:
        # save mmdet version, config file content and class names in
        # checkpoints as meta data
        cfg.checkpoint_config.meta = dict(
            mmdet_version=mmdet_version,
            mmseg_version=mmseg_version,
            mmdet3d_version=mmdet3d_version,
            config=cfg.pretty_text,
            CLASSES=datasets[0].CLASSES,
            PALETTE=datasets[0].PALETTE  # for segmentors
            if hasattr(datasets[0], 'PALETTE') else None)
        print(cfg.pretty_text)  #  here
```

I guess the pretty_text() function is not compatible with this case.

**Comment by HAOCHENYE** [comment]
Hi, can you provide your config file and the mmcv version? I guess there could be some syntax that is not compatible with the `mmcv.Config`.

BTW, it could be better to provide the full error messages.

**Comment by HAOCHENYE** [comment]
you can use `python -c "from mmcv.utils import collect_env; print(collect_env())"` to collect necessary environment information and paste it here.

**Comment by medlen** [comment]
python -c "from mmcv.utils import collect_env; print(collect_env())"

```
{'sys.platform': 'linux', 'Python': '3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]', 'CUDA available': False, 'GCC': 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0', 'PyTorch': '1.8.1+cpu', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, \n', 'TorchVision': '0.9.1+cpu', 'OpenCV': '4.6.0', 'MMCV': '1.6.0', 'MMCV Compiler': 'GCC 7.3', 'MMCV CUDA Compiler': 'not available'}

```

To reproduce:

```
git clone https://github.com/open-mmlab/mmdetection3d.git
```

add  code “print(cfg.pretty_text)” after https://github.com/open-mmlab/mmdetection3d/blob/master/tools/train.py#L249

and run 

```
python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py
```

Additionally, before https://github.com/open-mmlab/mmdetection3d/blob/master/tools/train.py#L226, this function is all right.

**Comment by medlen** [comment]
This is the error log:
```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/py38/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 119, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/user/anaconda3/envs/py38/lib/python3.8/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/user/anaconda3/envs/py38/lib/python3.8/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/user/anaconda3/envs/py38/lib/python3.8/lib2to3/pgen2/parse.py", line 119, in addtoken
    ilabel = self.classify(type, value, context)
  File "/home/user/anaconda3/envs/py38/lib/python3.8/lib2to3/pgen2/parse.py", line 175, in classify
    raise ParseError("bad token", type, value, context)
lib2to3.pgen2.parse.ParseError: bad token: type=58, value="'", context=('', (395, 15))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/py38/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/user/anaconda3/envs/py38/lib/python3.8/lib2to3/pgen2/driver.py", line 103, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/user/anaconda3/envs/py38/lib/python3.8/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/user/anaconda3/envs/py38/lib/python3.8/lib2to3/pgen2/parse.py", line 119, in addtoken
    ilabel = self.classify(type, value, context)
  File "/home/user/anaconda3/envs/py38/lib/python3.8/lib2to3/pgen2/parse.py", line 175, in classify
    raise ParseError("bad token", type, value, context)
lib2to3.pgen2.parse.ParseError: bad token: type=58, value="'", context=('', (395, 15))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/py38/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 183, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/user/anaconda3/envs/py38/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 131, in ParseCodeToTree
    raise e
  File "/home/user/anaconda3/envs/py38/lib/python3.8/site-packages/yapf/yapflib/pytree_utils.py", line 129, in ParseCodeToTree
    ast.parse(code)
  File "/home/user/anaconda3/envs/py38/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 395
    config='voxel_size = [0.16, 0.16, 4]
                                       ^
SyntaxError: EOL while scanning string literal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 268, in <module>
    main()
  File "tools/train.py", line 253, in main
    print(cfg.pretty_text)
  File "/home/user/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/utils/config.py", line 508, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/home/user/anaconda3/envs/py38/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 186, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
yapf.yapflib.errors.YapfError: <unknown>:395:45: EOL while scanning string literal

```

**Comment by HAOCHENYE** [comment]
Hi, the error is caused by https://github.com/open-mmlab/mmdetection3d/blob/9556958fe1c6fe432d55a9f98781b8fdd90f4e9c/tools/train.py#L246. Due to this line, the `pretty_text` of the modified `cfg` will include a substring which includes the escaping like "\n", this is not allowed for [FormatCode](https://github.com/google/yapf/issues/166). 

Is it necessary to save `pretty_text` in cfg? I'll talk about it with `mmdetection3d`

**Comment by medlen** [comment]
No, Thanks, it's not necessary for me, I just want to see the whole config file. Now I get it.
