### ISSUE TITLE
Docker instruction for pip install mmcv-full-1.5.0 ignored, 1.6 installed anyway.

### ISSUE THREAD

**Issue by domattioli** [open-mmlab/mmcv#2300]
Another library's Dockerfile requires mmcv-full. With my environment (CUDA 11.3.1, Cudnn 8, PyTorch 1.11), the following instructions define one venv:
```
# mmpose environment
RUN . /root/.bashrc && \
    conda create -n open-mmlab python=3.7 -y && \
    conda activate open-mmlab && \
    conda install -c pytorch pytorch=1.11 torchvision torchaudio cudatoolkit=11.3 && \
    pip uninstall mmcv-full && \
    pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/mmcv_full-1.5.0-cp37-cp37m-manylinux1_x86_64.whl && \
    cd /neuman/preprocess/mmpose && \
    pip install -r requirements.txt && \
    pip install -v -e . && \
    pip install openmim && \
    mim install mmdet
```

Despite the explicit installation instruction for `mmcv-full-1.5.0` I still get an error statingthat 1.6.1 is being used, and that it is incompatible:
```
Traceback (most recent call last):
  File "demo/bottom_up_img_demo.py", line 10, in <module>
    from mmpose.apis import (inference_bottom_up_pose_model, init_pose_model,
  File "/neuman/preprocess/mmpose/mmpose/__init__.py", line 26, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.6.1 is used but incompatible. Please install mmcv>=1.3.8, <=1.5.0.
```

Within my conda container, I manually edit the 'open-mmlab' venv, but `mmcv-full-1.6.1` is installed anyway:
```
(open-mmlab) root@f3fdf5d3629f:# pip uninstall mmcv-full
Found existing installation: mmcv-full 1.6.1
Uninstalling mmcv-full-1.6.1:
  Would remove:
    /opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/*
    /opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv_full-1.6.1.dist-info/*
Proceed (Y/n)? y
  Successfully uninstalled mmcv-full-1.6.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(open-mmlab) root@f3fdf5d3629f:# pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/mmcv_full-1.5.0-cp37-cp37m-manylinux1_x86_64.whl
Looking in links: https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/mmcv_full-1.5.0-cp37-cp37m-manylinux1_x86_64.whl
WARNING: Skipping page https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/mmcv_full-1.5.0-cp37-cp37m-manylinux1_x86_64.whl because the HEAD request got Content-Type: application/octet-stream.The only supported Content-Type is text/html
Collecting mmcv-full
  Using cached mmcv_full-1.6.1-cp37-cp37m-linux_x86_64.whl
Requirement already satisfied: yapf in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (0.32.0)
Requirement already satisfied: packaging in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (21.3)
Requirement already satisfied: Pillow in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (9.2.0)
Requirement already satisfied: addict in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (2.4.0)
Requirement already satisfied: numpy in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (1.21.5)
Requirement already satisfied: pyyaml in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (6.0)
Requirement already satisfied: opencv-python>=3 in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from mmcv-full) (4.6.0.66)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/envs/open-mmlab/lib/python3.7/site-packages (from packaging->mmcv-full) (3.0.9)
Installing collected packages: mmcv-full
Successfully installed mmcv-full-1.6.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(open-mmlab) root@f3fdf5d3629f:/neuman/preprocess# pip uninstall mmcv-full
Found existing installation: mmcv-full 1.6.1
Uninstalling mmcv-full-1.6.1:
  Would remove:
    /opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/*
    /opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv_full-1.6.1.dist-info/*
Proceed (Y/n)? y
  Successfully uninstalled mmcv-full-1.6.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

Edit: You can activate the open-mmlab venv within the docker container and then run `pip install mmcv-full==1.5.0`, but it takes quite a while to complete and AFAIK you need to do this each time you run the docker container.

What is going on here and does anyone have a suggestion?

**Comment by HAOCHENYE** [comment]
Hi! it seems mmcv-full 1.6.0 is installed by cache, you can try the following instruction:

```bash
mim install mmcv-full==1.5.0 --no-cache-dir
```
