### ISSUE TITLE
Python Traceback after lastest commit

### ISSUE THREAD

**Issue by zml24** [open-mmlab/mmcv#2367]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the FAQ documentation but cannot get the expected help.

After pulling [the lastet commit](https://github.com/open-mmlab/mmcv/commit/93fe4829f7f7c70b2fed22521b1c533cae86595a), mmsegmentation call mmcv met traceback.
```shell
Traceback (most recent call last):
  File "tools/test.py", line 17, in <module>
    from mmseg.apis import multi_gpu_test, single_gpu_test
  File "xxx/code/mmsegmentation/mmseg/apis/__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "xxx/code/mmsegmentation/mmseg/apis/inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "xxx/code/mmsegmentation/mmseg/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "xxx/code/mmsegmentation/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .beit import BEiT
  File "xxx/code/mmsegmentation/mmseg/models/backbones/beit.py", line 19, in <module>
    from .vit import TransformerEncoderLayer as VisionTransformerEncoderLayer
  File "xxx/code/mmsegmentation/mmseg/models/backbones/vit.py", line 9, in <module>
    from mmcv.cnn.bricks.transformer import FFN, MultiheadAttention
  File "xxx/code/mmcv/mmcv/cnn/bricks/transformer.py", line 22, in <module>
    from mmcv.ops.multi_scale_deform_attn import \
  File "xxx/code/mmcv/mmcv/ops/__init__.py", line 4, in <module>
    from .ball_query import ball_query
  File "xxx/code/mmcv/mmcv/ops/ball_query.py", line 9, in <module>
    ext_module = ext_loader.load_ext(
  File "xxx/code/mmcv/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: stack_ball_query_forward miss in module _ext
```

**Comment by zml24** [comment]
Traceback also occured after I using `git checkout master^`, and I had to use `git checkout master~2`. So [the commit](https://github.com/open-mmlab/mmcv/commit/a4f304a5f5667f9439fd767d8db09a0ae4bb79cd) may be the reason causing traceback.

**Comment by zhouzaida** [comment]
Hi, this `stack_ball_query_forward` op is a new op. You need to build mmcv from source again if pulling the latest master branch.

**Comment by zml24** [comment]
I got it. Thank you for your helpful reply.
