### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ljwLJW12** [open-mmlab/mmcv#2424]
### 分支

master 分支 (0.24 或其他 0.x 版本)

### 描述该错误

2022-11-17 15:27:37,639 - mmcls - INFO - Set random seed to 1885459642, deterministic: False
C:\Users\59192\.conda\envs\mmcla\lib\site-packages\mmcv\cnn\bricks\conv_module.py:154: UserWarning: Unnecessary conv bias before batch/instance norm
  'Unnecessary conv bias before batch/instance norm')
2022-11-17 15:27:38,202 - mmcls - INFO - initialize VGG with init_cfg [{'type': 'Kaiming', 'layer': ['Conv2d']}, {'type': 'Constant', 'val': 1.0, 'layer': ['_BatchNorm']}, {'type': 'Normal', 'std': 0.01, 'layer': ['Linear']}]
Traceback (most recent call last):
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\59192\mmclassification\mmcls\datasets\imagenet.py", line 1060, in __init__
    file_client_args=file_client_args)
  File "C:\Users\59192\mmclassification\mmcls\datasets\custom.py", line 170, in __init__
    test_mode=test_mode)
  File "C:\Users\59192\mmclassification\mmcls\datasets\base_dataset.py", line 51, in __init__
    self.data_infos = self.load_annotations()
  File "C:\Users\59192\mmclassification\mmcls\datasets\custom.py", line 211, in load_annotations
    samples = self._find_samples()
  File "C:\Users\59192\mmclassification\mmcls\datasets\custom.py", line 175, in _find_samples
    self.data_prefix)
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\mmcv\fileio\file_client.py", line 896, in infer_client
    return cls(prefix=file_prefix)
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\mmcv\fileio\file_client.py", line 814, in __new__
    f'prefix {prefix} is not supported. Currently supported ones '
ValueError: prefix C is not supported. Currently supported ones are ['s3', 'http', 'https']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\59192\mmclassification\tools\train.py", line 205, in <module>
    main()
  File "C:\Users\59192\mmclassification\tools\train.py", line 178, in main
    datasets = [build_dataset(cfg.data.train)]
  File "C:\Users\59192\mmclassification\mmcls\datasets\builder.py", line 55, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ValueError: ImageNet: prefix C is not supported. Currently supported ones are ['s3', 'http', 'https']

### 环境信息

(mmcla) C:\Users\59192\mmclassification> python -c "import mmcls.utils;import pprint;pprint.pp(dict(mmcls.utils.collect_env()))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'pprint' has no attribute 'pp'

**Comment by ljwLJW12** [comment]
> > Well, I think it should be an MMCV or yapf issue, and I will transfer this issue to MMCV.
thank you
