### ISSUE TITLE
_ext undefined symbol when using source-compiled pytorch

### ISSUE THREAD

**Issue by adizhol** [open-mmlab/mmcv#2439]
compiled pytorch v1.11.0 from source using CUDA 11.3, ubuntu 20.04, python 3.8 , installed to `/usr/local/lib/python3.8/dist-packages/torch/`
```
> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```

I also installed torchvision from source (v0.12.0)

installed mmcv-full from pip wheels
`pip install mmcv-full==1.7.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11/index.html`

error whem running mmcv:
```
> python3 -c "from mmcv.utils import collect_env; print(collect_env())"
        Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/env.py", line 124, in collect_env
        from mmcv.ops import get_compiler_version, get_compiling_cuda_version
      File "/usr/local/lib/python3.8/dist-packages/mmcv/ops/__init__.py", line 2, in <module>
        from .active_rotated_filter import active_rotated_filter
      File "/usr/local/lib/python3.8/dist-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
        ext_module = ext_loader.load_ext(
      File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
        ext = importlib.import_module('mmcv.' + name)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    ImportError: /usr/local/lib/python3.8/dist-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c107Warning4warnERKNS_14SourceLocationERKSsb
```

```
> ldd /usr/local/lib/python3.8/dist-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so 
        linux-vdso.so.1 (0x00007ffdf4141000)
        libc10.so => /usr/local/lib/python3.8/dist-packages/torch/lib/libc10.so (0x00007f0bb80ac000)
        libtorch.so => /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch.so (0x00007f0bb80a7000)
        libtorch_cpu.so => /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cpu.so (0x00007f0bae5d7000)
        libtorch_python.so => /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so (0x00007f0bad859000)
        libcudart.so.11.0 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0 (0x00007f0bad5ae000)
        libc10_cuda.so => /usr/local/lib/python3.8/dist-packages/torch/lib/libc10_cuda.so (0x00007f0bad556000)
        libtorch_cuda_cu.so => /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so (0x00007f0b7a57a000)
        libtorch_cuda_cpp.so => /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cpp.so (0x00007f0b6c657000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0b6c475000)
        libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007f0b6c326000)
        libgcc_s.so.1 => /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0b6c30b000)
        libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0b6c2e6000)
        libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007f0b6c0f4000)
        libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f0b6c0e7000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f0b6c0a5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0bbd112000)
        libtorch_cuda.so => /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda.so (0x00007f0b6c0a0000)
        libmpi_cxx.so.40 => /usr/lib/x86_64-linux-gnu/libmpi_cxx.so.40 (0x00007f0b6c082000)
        libmpi.so.40 => /usr/lib/x86_64-linux-gnu/libmpi.so.40 (0x00007f0b6bf5b000)
        librt.so.1 => /usr/lib/x86_64-linux-gnu/librt.so.1 (0x00007f0b6bf51000)
        libdl.so.2 => /usr/lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0b6bf4b000)
        libshm.so => /usr/local/lib/python3.8/dist-packages/torch/lib/libshm.so (0x00007f0b6bf41000)
        libnvToolsExt.so.1 => /usr/local/cuda/lib64/libnvToolsExt.so.1 (0x00007f0b6bd38000)
        libcudnn.so.8 => /usr/lib/x86_64-linux-gnu/libcudnn.so.8 (0x00007f0b6bb10000)
        libcusparse.so.11 => /usr/local/cuda/lib64/libcusparse.so.11 (0x00007f0b5df99000)
        libcurand.so.10 => /usr/local/cuda/lib64/libcurand.so.10 (0x00007f0b5880b000)
        libcusolver.so.11 => /usr/local/cuda/lib64/libcusolver.so.11 (0x00007f0b4b94f000)
        libnccl.so.2 => /usr/lib/x86_64-linux-gnu/libnccl.so.2 (0x00007f0b44291000)
        libcublas.so.11 => /usr/local/cuda/lib64/libcublas.so.11 (0x00007f0b3d24f000)
        libcufft.so.10 => /usr/local/cuda/lib64/libcufft.so.10 (0x00007f0b31a56000)
        libopen-rte.so.40 => /usr/lib/x86_64-linux-gnu/libopen-rte.so.40 (0x00007f0b3199c000)
        libopen-pal.so.40 => /usr/lib/x86_64-linux-gnu/libopen-pal.so.40 (0x00007f0b318ee000)
        libhwloc.so.15 => /usr/lib/x86_64-linux-gnu/libhwloc.so.15 (0x00007f0b3189d000)
        libcublasLt.so.11 => /usr/local/cuda/lib64/libcublasLt.so.11 (0x00007f0b25cbd000)
        libz.so.1 => /usr/lib/x86_64-linux-gnu/libz.so.1 (0x00007f0b25ca1000)
        libevent-2.1.so.7 => /usr/lib/x86_64-linux-gnu/libevent-2.1.so.7 (0x00007f0b25c4b000)
        libutil.so.1 => /usr/lib/x86_64-linux-gnu/libutil.so.1 (0x00007f0b25c46000)
        libevent_pthreads-2.1.so.7 => /usr/lib/x86_64-linux-gnu/libevent_pthreads-2.1.so.7 (0x00007f0b25c3f000)
        libudev.so.1 => /usr/lib/x86_64-linux-gnu/libudev.so.1 (0x00007f0b25c12000)
        libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f0b25c07000)
```

**Comment by zhouzaida** [comment]
Hi @adizhol , could you provide the outputs of `torch.__version__` and `torch.version.cuda`?

**Comment by adizhol** [comment]
torch version : 1.11.0a0+gitbc2c6ed
torch.version.cuda: 11.3

**Comment by adizhol** [comment]
**Update**
if I install **mmcv** from source (tag v1.7.0), torchvision (v0.12.0) and mmdet (2.25.3), I get erros when loading mmcv._ect:
```

>>> from mmdet.models.backbones.resnet import ResNet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/utils/__init__.py", line 13, in <module>
    from .point_sample import (get_uncertain_point_coords_with_randomness,
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/utils/point_sample.py", line 3, in <module>
    from mmcv.ops import point_sample
  File "/mmcv/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/mmcv/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/mmcv/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```

**Comment by zhouzaida** [comment]
Hi, if you want to build mmcv from source, you need to use `MMCV_WITH_OPS=1 pip install -e . -v` to compile mmcv.

**Comment by adizhol** [comment]
OK, now there is no more issue with mmcv._ext, but mmdet doens't load models:
```
>>> from mmdet.models.backbones.resnet import ResNetA
      ImportError: cannot import name 'ResNetA' from 'mmdet.models.backbones.resnet' (/mmdetection/mmdet/models/backbones/resnet.py)
```
This happnes both when I pip install mmdet==2.25.3 and when I build from source

**Comment by zhouzaida** [comment]
If we want to use `mmcv._ext` module, we need to set `MMCV_WITH_OPS=1` to compile the cuda op and  `MMCV_WITH_OPS=1 python setup.py install` should be OK.

**Comment by adizhol** [comment]
Compiling inside a docker with `MCV_WITH_OPS=1 python setup.py install` doesn't keep 'MMCV CUDA Compiler':

 python3 -c "from mmcv.utils import collect_env; print(collect_env())"
**'MMCV CUDA Compiler': 'not available'}**

    {'sys.platform': 'linux', 'Python': '3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]', 'CUDA available': True, 'GPU 0,1': 'NVIDIA GeForce RTX 3080', 'CUDA_HOME': '/usr/local/cuda', 'NVCC': 'Cuda compilation tools, release 11.3, V11.3.109', 'GCC': 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0', 'PyTorch': '1.11.0a0+gitbc2c6ed', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 9.4\n  - C++ Version: 201402\n  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.3\n  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86\n  - CuDNN 8.6  (built against CUDA 11.8)\n  - Build settings: BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.6.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n', 'TorchVision': '0.12.0+cu102', 'OpenCV': '4.5.4', 'MMCV': '1.7.0', 'MMCV Compiler': 'GCC 9.4', 'MMCV CUDA Compiler': 'not available'}

If I run the install again, it will be set correctly.

**Comment by adizhol** [comment]
When I try to load/use a resnet+deformable convolution i get this error:
`modulated_deformable_im2col_impl: implementation for device cuda:1 not found`
```

File "/root/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda/lib/python3.8/site-packages/mmcv_full-1.7.0-py3.8-linux-x86_64.egg/mmcv/ops/modulated_deform_conv.py", line 255, in forward
    return modulated_deform_conv2d(x, offset, mask, self.weight, self.bias,
  File "/root/miniconda/lib/python3.8/site-packages/mmcv_full-1.7.0-py3.8-linux-x86_64.egg/mmcv/ops/modulated_deform_conv.py", line 76, in forward
    ext_module.modulated_deform_conv_forward(
RuntimeError: modulated_deformable_im2col_impl: implementation for device cuda:1 not found.

```

**Comment by adizhol** [comment]
**UPDATE**
solved problems by setting enviroment variable
TORCH_CUDA_ARCH_LIST="3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6+PTX"
(https://github.com/pytorch/extension-cpp/issues/71#issuecomment-1183674660)

Finally to build mmcv-full:
```
TORCH_CUDA_ARCH_LIST="3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6+PTX" \
MMCV_WITH_OPS=1 \
FORCE_CUDA=1 \
python setup.py install
```
