### ISSUE TITLE
Fix the log error when IterBasedRunner is used

### ISSUE THREAD

**Issue by MaxDeveloper** [open-mmlab/mmcv#2457]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help.
3. The unexpected results still exist in the latest version.

**Describe the Issue**
Train script throws **KeyError: 'data_time'** exception on evaluation step.

**Reproduction**

1. What command, code, or script did you run?

```bash
python tools/train.py configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py
```

**Error traceback**
If applicable, paste the error traceback here.

```none
2022-11-24 17:53:39,658 - mmocr - INFO - Iter [95/6000] lr: 6.901e-03, eta: 2:37:37, time: 1.217, data_time: 0.088, memory: 3471, loss_prob: 1.6170, loss_db: 0.2242, loss_thr: 0.8002, loss: 2.6413
2022-11-24 17:53:48,957 - mmocr - INFO - Iter [100/6000]        lr: 6.896e-03, eta: 2:37:50, time: 1.672, data_time: 0.120, memory: 3471, loss_prob: 1.5775, loss_db: 0.2204, loss_thr: 0.7904, loss: 2.5884
[>>>>>>>>>>>>>>>>>>>>>>>>  ] 1638Traceback (most recent call last): ETA:     7s
  File "tools/train.py", line 243, in <module>
    run_train_cmd(args)
  File "tools/train.py", line 238, in run_train_cmd
    meta=meta)
  File "/mmocr/mmocr/apis/train.py", line 155, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 70, in train
    self.call_hook('after_train_iter')
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/hooks/logger/base.py", line 158, in after_train_iter
    self.log(runner)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/hooks/logger/text.py", line 234, in log
    self._log_info(log_dict, runner)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/hooks/logger/text.py", line 153, in _log_info
    log_str += f'time: {log_dict["time"]:.3f}, ' \
KeyError: 'data_time'
```

**Bug fix**
[It seems the same problem described here](https://github.com/open-mmlab/mmdetection/pull/5882)](https://github.com/open-mmlab/mmdetection/pull/5882). But that was related to mmdetection.
Fixed by adding **priority='LOW'** input parameter in mmocr/apis/train.py:149
```python
runner.register_hook(eval_hook(val_dataloader, **eval_cfg), priority='LOW')
```

**Comment by HAOCHENYE** [comment]
Hi, sorry for my late reply, and thanks for your feedback. The solution in the Bug fix looks good to me, but I still suggest you to experience MMOCR with the latest branch, which has been refactored based on MMEngine!
