### ISSUE TITLE
[Bug] Device error. BasicVSR++ from GPU to NPU [RuntimeError]: modulated_deformable_im2col_impl: implementation for device xla:0 not found.

### ISSUE THREAD

**Issue by youwowa** [open-mmlab/mmcv#2467]
Hello developer, I encountered the following errors during the BasicVSR++GPU migration NPU task. I hope I could get your help.
[error info](https://foruda.gitee.com/images/1670071405980559557/b1b4a026_7893297.png)

The problem that the input device reports an error is that npudataralle only has the first card, so the deviceid must be 0
[deviceId set 0](https://foruda.gitee.com/images/1670072452113033185/63e46a22_7893297.png)

The error of xla is to go to the custom operator library of mmlab
[xla error](https://foruda.gitee.com/images/1670071902219334204/171b2895_7893297.png)

**How to reproduce this error**
install [Add steps to install mmcv-full on NPU machine](https://github.com/open-mmlab/mmcv/pull/2363/files)
install mmedit
```
mmedit/api/train.py function _non_dist_train()
change from
model = MMDataParallel(model, device_ids=range(cfg.gpus))
to
from mmcv.device.npu import NPUDataParallel
model = NPUDataParallel(model.npu(), dim=0, device_ids=[0])
```
python3.7 mmediting/tools/train.py basicvsr_plusplus_c64n7_4x2_300k_vimeo90k_bi.py --work-dir work-dir/ --device npu

**error info**
`Traceback (most recent call last):
  File "train.py", line 174, in <module>
    main()
  File "train.py", line 170, in main
    meta=meta)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/apis/train.py", line 115, in train_model
    meta=meta)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/apis/train.py", line 370, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/test_user07/mmcv/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/test_user07/mmcv/mmcv/runner/iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/test_user07/mmcv/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/models/restorers/basicvsr.py", line 103, in train_step
    outputs = self(**data_batch, test_mode=False)
  File "/home/test_user07/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/test_user07/mmcv/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/models/restorers/basic_restorer.py", line 77, in forward
    return self.forward_train(lq, gt)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/models/restorers/basic_restorer.py", line 90, in forward_train
    output = self.generator(lq)
  File "/home/test_user07/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/models/backbones/sr_backbones/basicvsr_pp.py", line 347, in forward
    feats = self.propagate(feats, flows, module)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/models/backbones/sr_backbones/basicvsr_pp.py", line 218, in propagate
    flow_n1, flow_n2)
  File "/home/test_user07/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/models/backbones/sr_backbones/basicvsr_pp.py", line 433, in forward
    self.deform_groups)
  File "/home/test_user07/mmcv/mmcv/ops/modulated_deform_conv.py", line 95, in forward
    with_bias=ctx.with_bias)
RuntimeError: modulated_deformable_im2col_impl: implementation for device xla:0 not found.

THPModule_npu_shutdown success.`

**Comment by youwowa** [comment]
已解决，MMCV1.7.0已更新NPU算子。效率太高了
