### ISSUE TITLE
Error's with installing

### ISSUE THREAD

**Issue by p0wned17** [open-mmlab/mmcv#2471]
Hello everyone, when I try to install mmcv-full from 1.2.6 to 1.3.0. This error occurs. I tried to install this guide https://github.com/deepinsight/insightface/tree/master/detection/scrfd 

Complete error
```
Traceback(most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/powned/mmcv-1.2.6/setup.py", line 279, in <module>
        setup(
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
        self.run_command(cmd)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.run()
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
        self.distribution.run_command(command)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.run()
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
        self.build_extensions()
      File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 485, in build_extensions
        compiler_name, compiler_version = self._check_abi()
      File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 869, in _check_abi
        _, version = get_compiler_abi_compatibility_and_version(compiler)
      File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 336, in get_compiler_abi_compatibility_and_version
        if not check_compiler_ok_for_platform(compiler):
      File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 290, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/home/powned/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 421, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/home/powned/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 526, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['which', '/usr/bin/gcc-10']' returned non-zero exit status 1.
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/powned/anaconda3/envs/myenv/bin/python3.10 -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
    
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    
    __file__ = %r
    sys.argv[0] = __file__
    
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
    
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/home/powned/mmcv-1.2.6/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /home/powned/mmcv-1.2.6/
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by p0wned17** [comment]
```
note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/powned/anaconda3/envs/myenv/bin/python3.10 -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
    
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    
    __file__ = %r
    sys.argv[0] = __file__
    
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
    
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/home/powned/mmcv-1.2.6/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /home/powned/mmcv-1.2.6/
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by zhouzaida** [comment]
Hi, what is your command to install mmcv?

**Comment by p0wned17** [comment]
> Hi, what is your command to install mmcv?

I download 1.2.6 release and use this command MMCV_WITH_OPS=1 pip install -e . -v
In conda environment

**Comment by p0wned17** [comment]
```
(myenv) powned@powned-B460MDS3HV2:~/mmcv-1.2.6$ MMCV_WITH_OPS=1 pip install -e . -v
Using pip 22.3.1 from /home/powned/.local/lib/python3.10/site-packages/pip (python 3.10)
Obtaining file:///home/powned/mmcv-1.2.6
  Running command python setup.py egg_info
  /home/powned/.local/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    warnings.warn(
  running egg_info
  creating /tmp/pip-pip-egg-info-x81ossht/mmcv_full.egg-info
  writing /tmp/pip-pip-egg-info-x81ossht/mmcv_full.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-x81ossht/mmcv_full.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-x81ossht/mmcv_full.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-x81ossht/mmcv_full.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-x81ossht/mmcv_full.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-x81ossht/mmcv_full.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-x81ossht/mmcv_full.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in /home/powned/.local/lib/python3.10/site-packages (from mmcv-full==1.2.6) (2.4.0)
Requirement already satisfied: numpy in /home/powned/anaconda3/envs/myenv/lib/python3.10/site-packages (from mmcv-full==1.2.6) (1.23.5)
Requirement already satisfied: Pillow in /home/powned/anaconda3/envs/myenv/lib/python3.10/site-packages (from mmcv-full==1.2.6) (9.3.0)
Requirement already satisfied: pyyaml in /home/powned/anaconda3/envs/myenv/lib/python3.10/site-packages (from mmcv-full==1.2.6) (6.0)
Requirement already satisfied: yapf in /home/powned/.local/lib/python3.10/site-packages (from mmcv-full==1.2.6) (0.32.0)
Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full
    Running command python setup.py develop
    /home/powned/.local/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
      warnings.warn(
    running develop
    /home/powned/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /home/powned/.local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    creating mmcv_full.egg-info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/powned/mmcv-1.2.6/setup.py", line 279, in <module>
        setup(
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
        self.run_command(cmd)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.run()
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
        self.distribution.run_command(command)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.run()
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/powned/.local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
        self.build_extensions()
      File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 485, in build_extensions
        compiler_name, compiler_version = self._check_abi()
      File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 869, in _check_abi
        _, version = get_compiler_abi_compatibility_and_version(compiler)
      File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 336, in get_compiler_abi_compatibility_and_version
        if not check_compiler_ok_for_platform(compiler):
      File "/home/powned/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 290, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/home/powned/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 421, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/home/powned/anaconda3/envs/myenv/lib/python3.10/subprocess.py", line 526, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['which', '/usr/bin/gcc-10']' returned non-zero exit status 1.
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/powned/anaconda3/envs/myenv/bin/python3.10 -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
    
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    
    __file__ = %r
    sys.argv[0] = __file__
    
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
    
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/home/powned/mmcv-1.2.6/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /home/powned/mmcv-1.2.6/
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by zhouzaida** [comment]
What is your pytorch version?

**Comment by zhouzaida** [comment]
I'm not sure if gcc is too high, and I usually use gcc5.4. By the way, even if it compiles successfully, mmcv 1.2.6 doesn't work well on torch1.13. Suggest using lower pytorch or higher mmcv.
