### ISSUE TITLE
error with installing

### ISSUE THREAD

**Issue by sunnyyhyh** [open-mmlab/mmcv#2497]
Hello, when I try to install mmcv-full , this error occurs. I install follow [https://mmcv.readthedocs.io/zh_CN/latest/get_started/build.html](https://mmcv.readthedocs.io/zh_CN/latest/get_started/build.html)

My environment：pytorch 1.10.1+cu111 gcc 9.3.0

Complete error

```
Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/mnt/disk/zhangyunan/Code1217/mmcv/setup.py", line 463, in <module>
        zip_safe=False)
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/zhangyunan/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 735, in build_extensions
        build_ext.build_extensions(self)
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/cvteam/anaconda3/envs/table_m/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/home/zhangyunan/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 565, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/zhangyunan/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1404, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/zhangyunan/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/cvteam/anaconda3/envs/table_m/bin/python -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize

    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)

    __file__ = %r
    sys.argv[0] = __file__

    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"

    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/mnt/disk/zhangyunan/Code1217/mmcv/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /mnt/disk/zhangyunan/Code1217/mmcv/
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by zhouzaida** [comment]
Hi @sunnyyhyh , what was your command to install mmcv-full? BTW, you can install mmcv-full with mim.

```bash
pip install -U openmim
mim install mmcv-full
```

**Comment by sunnyyhyh** [comment]
@zhouzaida 
Hi, I use  ```MMCV_WITH_OPS=1 pip install -e . -v```  to install
and I also use 
```
pip install -U openmim
mim install mmcv-full
```

but got the same error
