### ISSUE TITLE
Get "TypeError: unsupported operand type(s) for |: 'int' and 'function' " when import mmcv

### ISSUE THREAD

**Issue by SSKKai** [open-mmlab/mmcv#2511]
I got **TypeError: unsupported operand type(s) for |: 'int' and 'function'** when import mmcv, the full traceback is as follow:
Traceback (most recent call last):
  File "C:\Users\lskdy\anaconda3\envs\py38\lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-012ad463f8e3>", line 1, in <module>
    import mmcv
  File "D:\Program Files\JetBrains\PyCharm 2021.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "d:\depends\mmcv\mmcv\__init__.py", line 7, in <module>
    from .image import *
  File "D:\Program Files\JetBrains\PyCharm 2021.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "d:\depends\mmcv\mmcv\image\__init__.py", line 5, in <module>
    from .geometric import (cutout, imcrop, imflip, imflip_, impad,
  File "D:\Program Files\JetBrains\PyCharm 2021.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "d:\depends\mmcv\mmcv\image\geometric.py", line 9, in <module>
    from .io import imread_backend
  File "D:\Program Files\JetBrains\PyCharm 2021.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "d:\depends\mmcv\mmcv\image\io.py", line 40, in <module>
    IMREAD_IGNORE_ORIENTATION | IMREAD_GRAYSCALE
TypeError: unsupported operand type(s) for |: 'int' and 'function'

It seems the error is from IMREAD_IGNORE_ORIENTATION | IMREAD_GRAYSCALE, what should I do?

**Comment by zhouzaida** [comment]
Hi, what is your OpenCV version?
