### ISSUE TITLE
Using mmcv-full for Swin-Transformer

### ISSUE THREAD

**Issue by imadalishah** [open-mmlab/mmcv#2521]
Hi, Im following https://github.com/SwinTransformer/Swin-Transformer-Object-Detection installation and have encountered the follwoing error for this code in GoogleColab:
!python tools/train.py configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_mfdataset.py --cfg-options model.pretrained = checkpoints/swin_tiny_patch4_window7_224.pth --gpus=1 --gpu-ids=1

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 87, in main
    args = parse_args()
  File "tools/train.py", line 71, in parse_args
    args = parser.parse_args()
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1886, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/config.py", line 739, in __call__
    key, val = kv.split('=', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

What is the possible issue, I've installed mmcv-full==1.3.17

**Comment by HAOCHENYE** [comment]
Sorry for my late reply. It seems you configure `cfg-option` incorrectly. There is extra space in 
`--cfg-options model.pretrained = checkpoints/swin_tiny_patch4_window7_224.pth`
it should be 
--cfg-options model.pretrained=checkpoints/swin_tiny_patch4_window7_224.pth
