### ISSUE TITLE
Could not install mmcv-full

### ISSUE THREAD

**Issue by sezer12138** [open-mmlab/mmcv#2565]
Use "mim install mmcv-full"
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 611, in _exec
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 57, in <module>
ImportError: cannot import name 'six' from 'pkg_resources.extern' (/home/wenkai/.local/lib/python3.9/site-packages/pkg_resources/extern/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wenkai/.local/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/wenkai/.local/lib/python3.9/site-packages/mim/commands/install.py", line 72, in cli
    exit_code = install(list(args), index_url=index_url, is_yes=is_yes)
  File "/home/wenkai/.local/lib/python3.9/site-packages/mim/commands/install.py", line 108, in install
    importlib.reload(pip._vendor.pkg_resources)
  File "/usr/lib/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 617, in _exec
KeyError: 'pkg_resources'

**Comment by ice-tong** [comment]
Hi @sezer12138 , can you provide more information so that we can reproduce this issue. (e.g. `pip list`)

**Comment by dmMaze** [comment]
I encountered the same error, upgrading the pip to the latest version resolve the problem. 
Maybe it is related to https://github.com/open-mmlab/mim/blob/dd7f11c6794ce67bae99160f70ae6b50209d06cf/mim/commands/install.py#L91-L107

**Comment by ice-tong** [comment]
> I encountered the same error, upgrading the pip to the latest version resolve the problem. Maybe it is related to https://github.com/open-mmlab/mim/blob/dd7f11c6794ce67bae99160f70ae6b50209d06cf/mim/commands/install.py#L91-L107

Hi @dmMaze, what version of pip are you using before? Can you help me to reproduce this issue? ^_^
Thank you very much!

**Comment by dmMaze** [comment]
> > I encountered the same error, upgrading the pip to the latest version resolve the problem. Maybe it is related to https://github.com/open-mmlab/mim/blob/dd7f11c6794ce67bae99160f70ae6b50209d06cf/mim/commands/install.py#L91-L107
> 
> Hi @dmMaze, what version of pip are you using before? Can you help me to reproduce this issue? ^_^ Thank you very much!

Sorry, can't recall that XXD, you could try < 22.0 according to https://github.com/open-mmlab/mim/blob/dd7f11c6794ce67bae99160f70ae6b50209d06cf/mim/commands/install.py#L91-L107
And I'm not sure if it is the problem with pip version, I upgrade the system from Ubuntu 20.04 to 22.04 recently and the py3.10 that came with it broke my original py setup, which could also be the source of the trouble
