### ISSUE TITLE
[Bug] Deprecated neptune.new module.

### ISSUE THREAD

**Issue by saratrajput** [open-mmlab/mmcv#2636]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

I have a config file with the ```NeptuneLoggerHook```:
```
log_config = dict(
    interval=50,
    hooks=[
        # dict(type='TextLoggerHook'),
        dict(type="NeptuneLoggerHook")
    ],
)
```

I have set the environment variables for ```NEPTUNE_PROJECT``` and ```NEPTUNE_API_TOKEN```.

Upon launching training, I get the error shown in the **error-message** section. 

### Reproduces the problem - code sample

```python
python tools/train.py my_configs/mask_rcnn_swin-t-p4-w7_fpn_1x_coco_abc.py
```

### Reproduces the problem - command or script

```python
python tools/train.py my_configs/mask_rcnn_swin-t-p4-w7_fpn_1x_coco_abc.py
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 231, in main
    train_detector(
  File "/home/sp/dev_root/mmdetection/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/sp/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 117, in run
    self.call_hook('before_run')
  File "/home/sp/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/sp/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 135, in wrapper
    return func(*args, **kwargs)
  File "/home/sp/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/hooks/logger/neptune.py", line 73, in before_run
    self.run = self.neptune.init()
AttributeError: module 'neptune.new' has no attribute 'init'
```

### Additional information

The error is related due to using the deprecated ```neptune.new``` module.

**Comment by saratrajput** [comment]
I have already fixed the issue on my end. I can submit a small PR soon if it's okay.

**Comment by zhouzaida** [comment]
Hi @saratrajput , thanks for your feedback. PRs are welcome.
