### ISSUE TITLE
 failed building mmcv from source with nvidia rtx 4080

### ISSUE THREAD

**Issue by ZJLauu** [open-mmlab/mmcv#2746]
Thanks for reporting the unexpected results and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help.
3. The unexpected results still exist in the latest version.

**Describe the Issue**
Windows10上mmcv2.0.0使用torch2.0.0+cu117从源码编译，在nvidia rtx 4080上编译失败

**Reproduction**

1. What command, code, or script did you run?

```bash
python setup.py build_ext 
```

2. Did you make any modifications on the code? Did you understand what you have modified?
    No

**Environment**
```
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: (MinGW.org GCC-6.3.0-1) 6.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

nvcc -V：
  nvcc: NVIDIA (R) Cuda compiler driver
  Copyright (c) 2005-2022 NVIDIA Corporation
  Built on Wed_Jun__8_16:59:34_Pacific_Daylight_Time_2022
  Cuda compilation tools, release 11.7, V11.7.99
  Build cuda_11.7.r11.7/compiler.31442593_0


Python version: 3.9.0 (default, Nov 15 2020, 08:30:55) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4080
Nvidia driver version: 531.41
cuDNN version: D:\Program Files\NVIDAI GPU Computing Toolkit\CUDA\v11.7\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3400
DeviceID=CPU0
Family=198
L2CacheSize=8192
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3400
Name=13th Gen Intel(R) Core(TM) i7-13700K
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0+cu117
[pip3] torchaudio==2.0.1+cu117
[pip3] torchvision==0.15.1+cu117
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py39h2bbff1b_0
[conda] mkl_fft                   1.3.1            py39h277e83a_0
[conda] mkl_random                1.2.2            py39hf11a4ad_0
[conda] numpy                     1.23.5           py39h3b20f71_0
[conda] numpy-base                1.23.5           py39h4da318b_0
[conda] torch                     2.0.0+cu117              pypi_0    pypi
[conda] torchaudio                2.0.1+cu117              pypi_0    pypi
[conda] torchvision               0.15.1+cu117             pypi_0    pypi
```

2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch 
      pip
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
      CUDA_PATH                       D:\Program Files\NVIDAI GPU Computing Toolkit\CUDA\v11.7
      TORCH_CUDA_ARCH_LIST             8.9
      MMCV_WITH_OPS  1
      MAX_JOBS  8

**Error traceback**

```none
...
...
...
nvcc fatal : Unsupported gpu architecture 'compute_89'
...
...
...
D:\Anaconda3\envs\mmcv\lib\site-packages\torch\include\ATen/core/dispatch/OperatorEntry.h(270): note: 查看对正在编译的 类 模板 实例化“ska::flat_hash_map<c10::DispatchKey,std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>,std::hash<c10::DispatchKey>,std::equal_to<K>,std::allocat
or<std::pair<K,V>>>”的引用
        with
        [
            K=c10::DispatchKey,
            V=std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>
        ]
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "D:\Anaconda3\envs\mmcv\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '23']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Pythonproject\Machine_Learning\CV\dev\Openmmlab\mmcv\setup.py", line 317, in <module>
    setup(
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 549, in build_extension
    objects = self.compiler.compile(
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\Anaconda3\envs\mmcv\lib\site-packages\torch\utils\cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by ZJLauu** [comment]
need torch2.0.0+cuda11.8.   torch1.13.x or cuda11.7 does not support GPU with 8.9 architecture
