### ISSUE TITLE
[Bug] RuntimeError: box_iou_rotated_impl: implementation for device xla:1 not found.

### ISSUE THREAD

**Issue by Sweewangyu** [open-mmlab/mmcv#2834]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

absl-py            1.4.0
addict             2.4.0
apex               0.1-ascend
attrs              23.1.0
auto-tune          0.1.0
backports.lzma     0.0.14
certifi            2022.12.7
cffi               1.15.1
charset-normalizer 3.1.0
click              8.1.3
colorama           0.4.6
cycler             0.11.0
Cython             0.29.34
decorator          5.1.1
e2cnn              0.2.3
expecttest         0.1.4
filelock           3.12.0
fonttools          4.38.0
fsspec             2023.1.0
hccl               0.1.0
hccl-parser        0.1
huggingface-hub    0.15.1
idna               3.4
importlib-metadata 6.6.0
kiwisolver         1.4.4
Markdown           3.4.3
markdown-it-py     2.2.0
matplotlib         3.5.3
mdurl              0.1.2
mmcv               1.7.1       /root/nju/mmcv
mmcv-full          1.7.1       /root/nju/mmcv
mmdet              2.28.2      /root/nju/mmdetection
mmengine           0.7.4
mmrotate           0.3.4       /root/nju/mmrotate1
model-index        0.1.11
mpmath             1.3.0
msadvisor          1.0.0
ninja              1.11.1
numpy              1.21.6
op-gen             0.1
op-test-frame      0.1
opc-tool           0.1.0
opencv-python      4.7.0.72
openmim            0.3.7
ordered-set        4.1.0
packaging          23.1
pandas             1.3.5
pathlib2           2.3.7.post1
Pillow             9.5.0
pip                23.1.2
protobuf           4.23.1
psutil             5.9.5
pycocotools        2.0.6
pycparser          2.21
Pygments           2.15.1
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2023.3
PyYAML             6.0
requests           2.30.0
rich               13.3.5
safetensors        0.3.1
schedule-search    0.0.1
scipy              1.7.3
setuptools         65.6.3
shapely            2.0.1
six                1.16.0
sympy              1.10.1
tabulate           0.9.0
te                 0.4.0
termcolor          2.3.0
terminaltables     3.1.10
timm               0.9.3.dev0
tomli              2.0.1
torch              1.8.1
torch-npu          1.8.1.post1
torchvision        0.9.1
tqdm               4.65.0
typing_extensions  4.5.0
urllib3            2.0.2
wheel              0.38.4
yapf               0.33.0
zipp               3.15.0

### Reproduces the problem - code sample

bash tools/dist_train.sh configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py 8

### Reproduces the problem - command or script

Traceback (most recent call last):
  File "tools/train.py", line 194, in <module>
    main()
  File "tools/train.py", line 190, in main
    meta=meta)
  File "/root/nju/mmrotate1/mmrotate/apis/train.py", line 144, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/nju/mmcv/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/nju/mmcv/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/root/nju/mmcv/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    **kwargs)
  File "/root/nju/mmcv/mmcv/parallel/distributed.py", line 63, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/root/nju/mmdetection/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/nju/mmcv/mmcv/runner/fp16_utils.py", line 149, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/root/nju/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/root/nju/mmrotate1/mmrotate/models/detectors/two_stage.py", line 150, in forward_train
    **kwargs)
  File "/root/nju/mmrotate1/mmrotate/models/roi_heads/oriented_standard_roi_head.py", line 70, in forward_train
    gt_labels[i])
  File "/root/nju/mmdetection/mmdet/core/bbox/assigners/max_iou_assigner.py", line 111, in assign
    overlaps = self.iou_calculator(gt_bboxes, bboxes)
  File "/root/nju/mmrotate1/mmrotate/core/bbox/iou_calculators/rotate_iou2d_calculator.py", line 45, in __call__
    is_aligned)
  File "/root/nju/mmrotate1/mmrotate/core/bbox/iou_calculators/rotate_iou2d_calculator.py", line 89, in rbbox_overlaps
    return box_iou_rotated(clamped_bboxes1, clamped_bboxes2, mode, is_aligned)
  File "/root/nju/mmcv/mmcv/ops/box_iou_rotated.py", line 148, in box_iou_rotated
    bboxes1, bboxes2, ious, mode_flag=mode_flag, aligned=aligned)
RuntimeError: box_iou_rotated_impl: implementation for device xla:1 not found.

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/train.py", line 194, in <module>
    main()
  File "tools/train.py", line 190, in main
    meta=meta)
  File "/root/nju/mmrotate1/mmrotate/apis/train.py", line 144, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/nju/mmcv/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/nju/mmcv/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/root/nju/mmcv/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    **kwargs)
  File "/root/nju/mmcv/mmcv/parallel/distributed.py", line 63, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/root/nju/mmdetection/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/nju/mmcv/mmcv/runner/fp16_utils.py", line 149, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/root/nju/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/root/nju/mmrotate1/mmrotate/models/detectors/two_stage.py", line 150, in forward_train
    **kwargs)
  File "/root/nju/mmrotate1/mmrotate/models/roi_heads/oriented_standard_roi_head.py", line 70, in forward_train
    gt_labels[i])
  File "/root/nju/mmdetection/mmdet/core/bbox/assigners/max_iou_assigner.py", line 111, in assign
    overlaps = self.iou_calculator(gt_bboxes, bboxes)
  File "/root/nju/mmrotate1/mmrotate/core/bbox/iou_calculators/rotate_iou2d_calculator.py", line 45, in __call__
    is_aligned)
  File "/root/nju/mmrotate1/mmrotate/core/bbox/iou_calculators/rotate_iou2d_calculator.py", line 89, in rbbox_overlaps
    return box_iou_rotated(clamped_bboxes1, clamped_bboxes2, mode, is_aligned)
  File "/root/nju/mmcv/mmcv/ops/box_iou_rotated.py", line 148, in box_iou_rotated
    bboxes1, bboxes2, ious, mode_flag=mode_flag, aligned=aligned)
RuntimeError: box_iou_rotated_impl: implementation for device xla:1 not found.

**Comment by zhouzaida** [comment]
Hi @Sweewangyu , what device did you use?
