### ISSUE TITLE
[Bug] Failed to install mmcv,Could not build wheels for mmcv, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmcv#2866]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

i installed the pytorch by `conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch`
my environment variables is: 
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.2/lib64
export PATH=$PATH:/usr/local/cuda-12.2/bin
export CUDA_HOME=$CUDA_HOME:/usr/local/cuda-12.2
export CMAKE_CUDA_COMPILER=/usr/local/cuda-12.2/bin/nvcc
```
And conda list:
```
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                         mkl  
brotlipy                  0.7.0           py38h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.05.30           h06a4308_0  
certifi                   2023.5.7         py38h06a4308_0  
cffi                      1.15.0           py38h7f8727e_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     7.1.2                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
cryptography              39.0.1           py38h9ce1e76_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.12.1               h4a9f257_0  
giflib                    5.2.1                h5eee18b_3  
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
idna                      3.4              py38h06a4308_0  
importlib-metadata        6.8.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
jpeg                      9e                   h5eee18b_1  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
lerc                      3.0                  h295c915_0  
libdeflate                1.17                 h5eee18b_0  
libedit                   3.1.20221030         h5eee18b_0  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.4                h5eee18b_0  
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.4.3                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.1            py38hd3c417c_0  
mkl_random                1.2.2            py38h51133e4_0  
model-index               0.1.11                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
numpy                     1.24.3           py38h14f4228_0  
numpy-base                1.24.3           py38h31eccc5_0  
openh264                  2.1.1                h4ff587b_0  
openmim                   0.1.6                    pypi_0    pypi
openssl                   1.1.1u               h7f8727e_0  
ordered-set               4.1.0                    pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pillow                    9.4.0            py38h6a678d5_0  
pip                       23.1.2           py38h06a4308_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.0.0           py38h06a4308_0  
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.0                h0371630_2  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.12.1          py3.8_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  7.0                  h7b6447c_5  
requests                  2.29.0           py38h06a4308_0  
setuptools                67.8.0           py38h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.33.0               h62c20be_0  
tabulate                  0.9.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torchaudio                0.12.1               py38_cu113    pytorch
torchvision               0.13.1               py38_cu113    pytorch
typing_extensions         4.6.3            py38h06a4308_0  
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.16          py38h06a4308_0  
wheel                     0.38.4           py38h06a4308_0  
xz                        5.4.2                h5eee18b_0  
zipp                      3.16.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0  
```

### Reproduces the problem - code sample

mim install mmcv=2.0.0

### Reproduces the problem - command or script

mim install mmcv=2.0.0

### Reproduces the problem - error message

it occur this problem:
![image](https://github.com/open-mmlab/mmcv/assets/86214036/8cec281e-f6a8-4726-84c1-1d659fac4940)

```
/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
installing mmcv from wheel.
Collecting mmcv==2.0.0
  Downloading mmcv-2.0.0.tar.gz (473 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 473.2/473.2 kB 531.2 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting addict (from mmcv==2.0.0)
  Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting mmengine>=0.2.0 (from mmcv==2.0.0)
  Using cached mmengine-0.8.1-py3-none-any.whl (433 kB)
Requirement already satisfied: numpy in ./miniconda3/envs/mm/lib/python3.8/site-packages (from mmcv==2.0.0) (1.24.3)
Collecting packaging (from mmcv==2.0.0)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in ./miniconda3/envs/mm/lib/python3.8/site-packages (from rich->mmengine>=0.2.0->mmcv==2.0.0) (4.6.3)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->mmengine>=0.2.0->mmcv==2.0.0)
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/mm/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib->mmengine>=0.2.0->mmcv==2.0.0) (1.16.0)
Building wheels for collected packages: mmcv
  Building wheel for mmcv (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [1174 lines of output]
      running bdist_wheel
      /home/music/miniconda3/envs/mm/lib/python3.8/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/mmcv
      copying mmcv/version.py -> build/lib.linux-x86_64-cpython-38/mmcv
      copying mmcv/__init__.py -> build/lib.linux-x86_64-cpython-38/mmcv
      creating build/lib.linux-x86_64-cpython-38/mmcv/arraymisc
      copying mmcv/arraymisc/quantization.py -> build/lib.linux-x86_64-cpython-38/mmcv/arraymisc
      copying mmcv/arraymisc/__init__.py -> build/lib.linux-x86_64-cpython-38/mmcv/arraymisc
      creating build/lib.linux-x86_64-cpython-38/mmcv/transforms
      copying mmcv/transforms/formatting.py -> build/lib.linux-x86_64-cpython-38/mmcv/transforms
      copying mmcv/transforms/builder.py -> build/lib.linux-x86_64-cpython-38/mmcv/transforms
      copying mmcv/transforms/wrappers.py -> build/lib.linux-x86_64-cpython-38/mmcv/transforms
      copying mmcv/transforms/base.py -> build/lib.linux-x86_64-cpython-38/mmcv/transforms
      copying mmcv/transforms/processing.py -> build/lib.linux-x86_64-cpython-38/mmcv/transforms
      copying mmcv/transforms/loading.py -> build/lib.linux-x86_64-cpython-38/mmcv/transforms
      copying mmcv/transforms/__init__.py -> build/lib.linux-x86_64-cpython-38/mmcv/transforms
      copying mmcv/transforms/utils.py -> build/lib.linux-x86_64-cpython-38/mmcv/transforms
      creating build/lib.linux-x86_64-cpython-38/mmcv/video
      copying mmcv/video/optflow.py -> build/lib.linux-x86_64-cpython-38/mmcv/video
      copying mmcv/video/io.py -> build/lib.linux-x86_64-cpython-38/mmcv/video
      copying mmcv/video/processing.py -> build/lib.linux-x86_64-cpython-38/mmcv/video
      copying mmcv/video/__init__.py -> build/lib.linux-x86_64-cpython-38/mmcv/video
      creating build/lib.linux-x86_64-cpython-38/mmcv/image
      copying mmcv/image/io.py -> build/lib.linux-x86_64-cpython-38/mmcv/image
      copying mmcv/image/misc.py -> build/lib.linux-x86_64-cpython-38/mmcv/image
      copying mmcv/image/colorspace.py -> build/lib.linux-x86_64-cpython-38/mmcv/image
      copying mmcv/image/photometric.py -> build/lib.linux-x86_64-cpython-38/mmcv/image
      copying mmcv/image/__init__.py -> build/lib.linux-x86_64-cpython-38/mmcv/image
      copying mmcv/image/geometric.py -> build/lib.linux-x86_64-cpython-38/mmcv/image
      creating build/lib.linux-x86_64-cpython-38/mmcv/utils
      copying mmcv/utils/env.py -> build/lib.linux-x86_64-cpython-38/mmcv/utils
      copying mmcv/ops/bezier_align.py -> build/lib.linux-x86_64-cpython-38/mmcv/ops
      copying mmcv/ops/modulated_deform_conv.py -> build/lib.linux-x86_64-cpython-38/mmcv/ops
      copying mmcv/ops/sync_bn.py -> build/lib.linux-x86_64-cpython-38/mmcv/ops
      copying mmcv/ops/sparse_conv.py -> build/lib.linux-x86_64-cpython-38/mmcv/ops
      copying mmcv/ops/points_in_boxes.py -> build/lib.linux-x86_64-cpython-38/mmcv/ops
      copying mmcv/ops/active_rotated_filter.py -> build/lib.linux-x86_64-cpython-38/mmcv/ops
      copying mmcv/ops/box_iou_quadri.py -> build/lib.linux-x86_64-cpython-38/mmcv/ops
      copying mmcv/ops/diff_iou_rotated.py -> build/lib.linux-x86_64-cpython-38/mmcv/o
        check.warn(importable)
      creating build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc
      creating build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/common
      copying mmcv/ops/csrc/common/box_iou_rotated_utils.hpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/common
      copying mmcv/ops/csrc/pytorch/mlu/roi_pool_mlu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/mlu
      copying mmcv/ops/csrc/pytorch/mlu/roiaware_pool3d_mlu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/mlu
      copying mmcv/ops/csrc/pytorch/mlu/roipoint_pool3d_mlu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/mlu
      copying mmcv/ops/csrc/pytorch/mlu/three_nn_mlu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/mlu
      copying mmcv/ops/csrc/pytorch/mlu/tin_shift_mlu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/mlu
      creating build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/mps
      copying mmcv/ops/csrc/pytorch/mps/bbox_overlaps_mps.mm -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/mps
      creating build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/npu
      copying mmcv/ops/csrc/pytorch/npu/bbox_overlaps_npu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/npu
      copying mmcv/ops/csrc/pytorch/npu/deform_roi_pool.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/npu
      copying mmcv/ops/csrc/pytorch/npu/focal_loss_npu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/npu
      copying mmcv/ops/csrc/pytorch/npu/fused_bias_leakyrelu_npu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/npu
      copying mmcv/ops/csrc/pytorch/npu/gather_points_npu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/npu
      copying mmcv/ops/csrc/pytorch/npu/nms_npu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/npu
      copying mmcv/ops/csrc/pytorch/npu/nms_rotated_npu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/npu
      copying mmcv/ops/csrc/pytorch/npu/psa_mask_npu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/npu
      copying mmcv/ops/csrc/pytorch/npu/roi_pool_npu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/npu
      copying mmcv/ops/csrc/pytorch/npu/voxelization_npu.cpp -> build/lib.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/npu
      running build_ext
      error: [Errno 2] No such file or directory: ':/usr/local/cuda-12.2/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv
  Running setup.py clean for mmcv
Failed to build mmcv
ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mim/utils/utils.py", line 419, in call_command
    subprocess.check_call(cmd)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'pip', '--default-timeout', '45', 'install', 'mmcv==2.0.0']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/music/miniconda3/envs/mm/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mim/commands/install.py", line 102, in cli
    install(
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mim/commands/install.py", line 212, in install
    install_from_wheel(target_pkg, target_version, find_url, timeout,
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mim/commands/install.py", line 580, in install_from_wheel
    call_command(install_cmd)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mim/utils/utils.py", line 421, in call_command
    raise highlighted_error(e)  # type: ignore
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mim/utils/utils.py", line 393, in highlighted_error
    return click.style(msg, fg='red', bold=True)  # type: ignore
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/click/termui.py", line 519, in style
    return "".join(bits)
TypeError: sequence item 2: expected str instance, CalledProcessError found
```

### Additional information

my nvidia driver is 535.54.03, my cuda version is 12.2.0 in the base env
![image](https://github.com/open-mmlab/mmcv/assets/86214036/1f561a47-94d1-428b-8f83-a3648461f1d3)

**Comment by zhouzaida** [comment]
Hi, you can install mmcv with the pre-built package.

```bash
pip install -U openmim
mim install mmcv==2.0.0
```

**Comment by lijoe123** [comment]
thank you. may be i had forgot to pip install -U openmim. But now it work.

**Comment by GDragon986** [comment]
> Hi, I have the same problem as you when installing mmcv, can you please tell me how you solved it?

**Comment by lijoe123** [comment]
> > Hi, I have the same problem as you when installing mmcv, can you please tell me how you solved it?

I'm sorry, i dont konw exactly. I just use the command again `pip install -U openmim` and success, may be i forgot to use this command.

**Comment by kyrie2to11** [comment]
> Hi, you can install mmcv with the pre-built package.
> 
> ```shell
> pip install -U openmim
> mim install mmcv==2.0.0
> ```

I encountered the same problem when installing mmcv-full==1.6.0. However, updating pip and then reinstalling mmcv-full did not resolve the issue.

**Comment by fanqiNO1** [comment]
> > Hi, you can install mmcv with the pre-built package.
> > ```shell
> > pip install -U openmim
> > mim install mmcv==2.0.0
> > ```
> 
> I encountered the same problem when installing mmcv-full==1.6.0 and confirmed the existence of the path "/usr/local/cuda/bin/nvcc". However, updating pip and then reinstalling mmcv-full did not resolve the issue.

Could you provide the version of torch and cuda you use?

**Comment by LorenzoSun-V** [comment]
> > > > Hi, you can install mmcv with the pre-built package.
> > > > ```shell
> > > > pip install -U openmim
> > > > mim install mmcv==2.0.0
> > > > ```
> > > 
> > > 
> > > I encountered the same problem when installing mmcv-full==1.6.0 and confirmed the existence of the path "/usr/local/cuda/bin/nvcc". However, updating pip and then reinstalling mmcv-full did not resolve the issue.
> > 
> > 
> > Could you provide the version of torch and cuda you use?
> 
> torch 1.13.1 + cuda 11.7. By the way, this issue may have been caused by the configuration of `$CUDA_HOME`. I resolved it by resetting it using the command `export CUDA_HOME=/usr/local/cuda`, instead of `export CUDA_HOME=$CUDA_HOME:/usr/local/cuda`, and it worked.

This is helpful indeed.
