### ISSUE TITLE
[Bug] ImportError: cannot import name 'is_list_of' from 'mmcv.utils'

### ISSUE THREAD

**Issue by lizhyuxi** [open-mmlab/mmcv#2882]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

Python 3.8
PyTorch 1.7.1
mmcv                2.0.0rc4
mmcv-full           1.5.3

### Reproduces the problem - code sample

  File "/users/k20103423/.conda/envs/CGFormer/lib/python3.8/site-packages/mmcv/fileio/io.py", line 6, in <module>
    from ..utils import is_list_of

### Reproduces the problem - command or script

none

### Reproduces the problem - error message

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    from model import build_segmenter
  File "/scratch/users/k20103423/zhiyu/CGFormer/model/__init__.py", line 4, in <module>
    from .backbone import MultiModalSwinTransformer
  File "/scratch/users/k20103423/zhiyu/CGFormer/model/backbone.py", line 9, in <module>
    from .mmcv_custom import load_checkpoint
  File "/scratch/users/k20103423/zhiyu/CGFormer/model/mmcv_custom/__init__.py", line 3, in <module>
    from .checkpoint import load_checkpoint
  File "/scratch/users/k20103423/zhiyu/CGFormer/model/mmcv_custom/checkpoint.py", line 19, in <module>
    from mmcv.fileio import FileClient
  File "/users/k20103423/.conda/envs/CGFormer/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 4, in <module>
    from .io import dump, load, register_handler
  File "/users/k20103423/.conda/envs/CGFormer/lib/python3.8/site-packages/mmcv/fileio/io.py", line 6, in <module>
    from ..utils import is_list_of
ImportError: cannot import name 'is_list_of' from 'mmcv.utils' (/users/k20103423/.conda/envs/CGFormer/lib/python3.8/site-packages/mmcv/utils/__init__.py)

### Additional information

'is_list_of' do not exist in this init file
![image](https://github.com/open-mmlab/mmcv/assets/71909976/a738e96e-336a-458e-abee-da84a74369c6)

**Comment by fanqiNO1** [comment]
It seems that it's because you use mmcv>=2.0, but the original project uses mmcv<2.0. `mmcv.utils.is_list_of` has been moved to `mmengine.utils` with mmcv=2.0. So you can try to install mmcv<2.0.
https://github.com/open-mmlab/mmengine/blob/53474ef1ba0b166508c231fa525b55b580adf20f/mmengine/utils/__init__.py#L23

**Comment by yangdeai** [comment]
the compatibility of openmmlab's package is son of beach!!! It's a torture to use it.

**Comment by PegaXuX** [comment]
how can you make mmcv and mmcv-full both working, i thoughr they are incompatible
