### ISSUE TITLE
ImportError: cannot import name 'TORCH_VERSION' from 'mmcv.utils' (C:\Users\hongzheng\.conda\envs\opencd\lib\site-packages\mmcv\utils\__init__.py)[Docs] 

### ISSUE THREAD

**Issue by HZWXW371** [open-mmlab/mmcv#2984]
### 📚 The doc issue

Traceback (most recent call last):
  File "D:\GIS\LightCDNet-main\tools\train.py", line 15, in <module>
    from mmcv.runner import get_dist_info, init_dist
  File "C:\Users\hongzheng\.conda\envs\opencd\lib\site-packages\mmcv\runner\__init__.py", line 3, in <module>
    from .base_runner import BaseRunner
  File "C:\Users\hongzheng\.conda\envs\opencd\lib\site-packages\mmcv\runner\base_runner.py", line 16, in <module>
    from ..parallel import is_module_wrapper
  File "C:\Users\hongzheng\.conda\envs\opencd\lib\site-packages\mmcv\parallel\__init__.py", line 5, in <module>
    from .distributed import MMDistributedDataParallel
  File "C:\Users\hongzheng\.conda\envs\opencd\lib\site-packages\mmcv\parallel\distributed.py", line 10, in <module>
    from mmcv.utils import TORCH_VERSION, digit_version
ImportError: cannot import name 'TORCH_VERSION' from 'mmcv.utils' (C:\Users\hongzheng\.conda\envs\opencd\lib\site-packages\mmcv\utils\__init__.py)

Process finished with exit code 1

### Suggest a potential alternative/fix

Traceback (most recent call last):
  File "D:\GIS\LightCDNet-main\tools\train.py", line 15, in <module>
    from mmcv.runner import get_dist_info, init_dist
  File "C:\Users\hongzheng\.conda\envs\opencd\lib\site-packages\mmcv\runner\__init__.py", line 3, in <module>
    from .base_runner import BaseRunner
  File "C:\Users\hongzheng\.conda\envs\opencd\lib\site-packages\mmcv\runner\base_runner.py", line 16, in <module>
    from ..parallel import is_module_wrapper
  File "C:\Users\hongzheng\.conda\envs\opencd\lib\site-packages\mmcv\parallel\__init__.py", line 5, in <module>
    from .distributed import MMDistributedDataParallel
  File "C:\Users\hongzheng\.conda\envs\opencd\lib\site-packages\mmcv\parallel\distributed.py", line 10, in <module>
    from mmcv.utils import TORCH_VERSION, digit_version
ImportError: cannot import name 'TORCH_VERSION' from 'mmcv.utils' (C:\Users\hongzheng\.conda\envs\opencd\lib\site-packages\mmcv\utils\__init__.py)

Process finished with exit code 1

**Comment by zhouzaida** [comment]
Hi, what is your mmcv version?

**Comment by tanatomoe** [comment]
Did you manage to fix this issue?

**Comment by Manishnayak234** [comment]
hey anybody solved this issue ?

**Comment by vetsasai** [comment]
`from mmengine.utils.dl_utils import TORCH_VERSION`

This worked for me

**Comment by CoffeeinTeaC** [comment]
than i meet a problem as follows:
ImportError: cannot import name 'digit_version' from 'mmcv.utils' (/home/cyg/anaconda3/envs/tinydet/lib/python3.8/site-packages/mmcv/utils/__init__.py)

**Comment by smolan** [comment]
from mmengine.utils.dl_utils import TORCH_VERSION
from mmengine.utils import digit_version
