### ISSUE TITLE
Config-File: whitespaces in dict

### ISSUE THREAD

**Issue by Kaeseknacker** [open-mmlab/mmcv#299]
Hi,
I use mmdetection and therefore indirectly mmcv. 
In mmdetection < v2.0 i could use whitespaces in dictionary keys in model config files.
Example:
```
test_map = {'12 3': '456'}
```
Since mmdetection v2.0 this isn't possible anymore.
Here some error traceback:
```
Traceback (most recent call last):
  File "./tools/train.py", line 161, in <module>
    main()
  File "./tools/train.py", line 104, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/spraul/anaconda3/envs/mmv2/lib/python3.7/site-packages/mmcv/utils/config.py", line 307, in dump
    f.write(self.pretty_text)
  File "/home/spraul/anaconda3/envs/mmv2/lib/python3.7/site-packages/mmcv/utils/config.py", line 271, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/home/spraul/anaconda3/envs/mmv2/lib/python3.7/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/spraul/anaconda3/envs/mmv2/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
    raise e
  File "/home/spraul/anaconda3/envs/mmv2/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    ast.parse(code)
  File "/home/spraul/anaconda3/envs/mmv2/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 565
    12 3='456')
       ^
SyntaxError: invalid syntax

```

Is there still a way to use whitespaces as keys in dictionarys?

**Comment by hellock** [comment]
This issue should have been fixed in #304.
