### ISSUE TITLE
[Bug] AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

### ISSUE THREAD

**Issue by Grushus** [open-mmlab/mmcv#3096]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

```OrderedDict([('sys.platform', 'linux'),
('Python', '3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]'),
('CUDA available', True), 
('MUSA available', False),
('numpy_random_seed', 2147483648),
('GPU 0', 'NVIDIA A100-SXM4-40GB'),
('CUDA_HOME', '/usr/local/cuda'),
('NVCC', 'Cuda compilation tools, release 12.2, V12.2.140'),
('GCC', 'x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'),
('PyTorch', '2.1.0a0+32f93b1'),

('PyTorch compiling details', 'PyTorch built with:\n  - GCC 11.2\n  - C++ Version: 201703\n  - Intel(R) oneAPI Math Kernel Library Version 2021.1-Product Build 20201104 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.7.3 (Git Hash N/A)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 12.2\n  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_72,code=sm_72;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_87,code=sm_87;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_90,code=compute_90\n  - CuDNN 8.9.5\n  - Magma 2.6.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.2, CUDNN_VERSION=8.9.5, CXX_COMPILER=/opt/rh/gcc-toolset-11/root/usr/bin/c++, CXX_FLAGS=-fno-gnu-unique -D_GLIBCXX_USE_CXX11_ABI=1 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n'),

('TorchVision', '0.16.0a0'),
('OpenCV', '4.7.0'), 
('MMEngine', '0.10.4'),
('MMCV', '2.2.0'),
('MMCV Compiler', 'GCC 11.4'),
('MMCV CUDA Compiler', '12.2')])```

### Reproduces the problem - code sample

Installing mmcv like this
```
%pip install -U openmim
!mim install mmengine
!sed -i 's/^LayerId = cv2.dnn.DictValue/#&/' /usr/local/lib/python3.10/dist-packages/cv2/typing/__init__.py
!mim install "mmcv>=2.1.0"
%cd mmdetection
%pip install -v -e .
%pip install protobuf==3.20
```
Installs the latest version 2.2.0 since it was released yesterday
```
!python /home/MMDetection/mmdetection/tools/train.py \
/home/MMDetection/mmdetection/configs/retinanet/retinanet_r50_fpn_1x_Headvhelmet.py \
--work-dir /home/MMDetection/blablabladelete/test```

### Reproduces the problem - command or script

Installing mmcv like this
```
%pip install -U openmim
!mim install mmengine
!sed -i 's/^LayerId = cv2.dnn.DictValue/#&/' /usr/local/lib/python3.10/dist-packages/cv2/typing/__init__.py
!mim install "mmcv>=2.1.0"
%cd mmdetection
%pip install -v -e .
%pip install protobuf==3.20
```
Installs the latest version 2.2.0 since it was released yesterday
```
!python /home/MMDetection/mmdetection/tools/train.py \
/home/MMDetection/mmdetection/configs/retinanet/retinanet_r50_fpn_1x_Headvhelmet.py \
--work-dir /home/MMDetection/blablabladelete/test```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "/home/MMDetection/mmdetection/tools/train.py", line 10, in <module>
    from mmdet.utils import setup_cache_size_limit_of_dynamo
  File "/home/MMDetection/mmdetection/mmdet/__init__.py", line 17, in <module>
    and mmcv_version < digit_version(mmcv_maximum_version)), \
AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

```

### Additional information

1. For the training script from mmdetection to work. 
2. Dataset not relevant
3. I think the reason might be something in the mmcv 2.2.0 version doesnt work with the train.py from mmdetection

**Comment by solayuta** [comment]
I installed the latest version of release today

I had the same problem

**Comment by DrRazadyne** [comment]
Same issue. Any solution?

**Comment by Grushus** [comment]
@DrRazadyne @solayuta  For me I changed `!mim install "mmcv>=2.1.0"` to `!mim install "mmcv==2.1.0"` as a current solution so it doesnt install 2.2.0

**Comment by ashishnex007** [comment]
pip install mmcv==2.0.0rc4

try this, in my case it got fixed

**Comment by HuysArthur** [comment]
> pip install mmcv==2.0.0rc4
> 
> try this, in my case it got fixed

For me this doesn't help, I get the following error by running "pip install mmcv==2.0.0rc4":

```
Building wheels for collected packages: mmcv
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for mmcv (setup.py) ... error
  ERROR: Failed building wheel for mmcv
  Running setup.py clean for mmcv
Failed to build mmcv
ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects
```

Online I found a fix online to install mmcv from the source but then I get the first problem again that I have version 2.2.0.

Does anyone know how to fix this?

**Comment by Nhanvu1009** [comment]
[https://github.com/open-mmlab/mmdetection/issues/10104#issuecomment-1502567657](url)
 i've solve this problem by following his instruction

**Comment by Zhijing-W** [comment]
maybe your mmdet version are too high. If you git mmdet from website, it is the latest 3.3.0. I recommend you to install mmdet==3.0.0 (https://github.com/open-mmlab/mmdetection/releases/tag/v3.0.0), then try this again `pip install mmcv=2.0.0rc4`. And don't use mim to install.

**Comment by Zhijing-W** [comment]
I have this issue on installing mmyolo. Both mmyolo and mmcv=2.0.0 can't be installed. So I just uninstall all pakages and follow the following instruction:
<img width="689" alt="image" src="https://github.com/open-mmlab/mmcv/assets/140717414/b67beb09-5c41-4b73-b71a-c2ca337fa199">

**Comment by wstlxx** [comment]
just use 2.1.0 instead

**Comment by ArenaGrenade** [comment]
@Zhijing-W where are you getting that compatibility matrix from? The one I can see isnt right I think: [https://github.com/open-mmlab/mmsegmentation/blob/main/docs/en/notes/faq.md](https://github.com/open-mmlab/mmsegmentation/blob/main/docs/en/notes/faq.md).

Is this issue due to a recent update? What is the last stable version I can use now? Or is the library completely broken until next patch?

**Comment by uptownfunkmars** [comment]
in my case, i comment out part of the code in  mmseg/__init__.py from line 60 to line 62, it got fixed

**Comment by Zhijing-W** [comment]
> @Zhijing-W where are you getting that compatibility matrix from? The one I can see isnt right I think: https://github.com/open-mmlab/mmsegmentation/blob/main/docs/en/notes/faq.md.
> 
> Is this issue due to a recent update? What is the last stable version I can use now? Or is the library completely broken until next patch?

From here: https://mmyolo.readthedocs.io/en/latest/get_started/dependencies.html. I use the version mmcv==2.0.0rc4, mmengine==0.7.1,for installing mmyolo==0.6.0. Incompatibility may caused by too high version. You can strictly follow the requirements of the compatibility matrix.

**Comment by zhouzaida** [comment]
> try this, in my case it got fixed

Such modification is OK and works well.

**Comment by zhouzaida** [comment]
Why is this error occurring? The reason is that we have released a new version but the downstream libraries are not yet supported. There are two solutions, one is to install a lower version of mmcv (but the lower version of mmcv may not provide support for torch2.2.0), and the other is to change the mmcv version restriction in the __init__ file of the downstream libraries, which works fine this way.

**Comment by sailfish009** [comment]
You will need to modify all c++14 to c++17 in **setup.py**  
install the necessary development library packages on Linux using apt. 

```
sudo apt install gcc-12
sudo apt install g++-12
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12
gcc --version
g++ --version
```

```
export CUDA_HOME=$HOME/tools/cuda-9.0 # change to your path
export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME
export LD_LIBRARY_PATH="$CUDA_HOME/extras/CUPTI/lib64:$LD_LIBRARY_PATH"
export LIBRARY_PATH=$CUDA_HOME/lib64:$LIBRARY_PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export CFLAGS="-I$CUDA_HOME/include $CFLAGS"
```

`pip install -e .`

**Comment by vaidatascientist** [comment]
If you are working in google colab, just run this
```
!pip install -U openmim
!mim install mmengine
!mim install "mmcv>=2.0.0rc4, <2.2.0."
```
After the first pip install for openmim, it might ask you to reset your session for colab, do that, and then re-run the same cell again, it should take around 45-60m to run the entire thing, but it should run successfully, give it a try

**Comment by NhiNguyen34** [comment]
Change  `mmcv_maximum_version = '2.2.0'` to `mmcv_maximum_version = '2.2.1'` and it works for me.
![image](https://github.com/open-mmlab/mmcv/assets/118429842/f957ef36-58dd-401d-a426-e817c92a1a3b)

**Comment by antopost** [comment]
As @wstlxx mentioned above, if using 2.1.0 is an option for you then you can just install the version that is compatible with your pytorch and cuda version.
You can find compatible versions [here](https://mmcv.readthedocs.io/en/latest/get_started/installation.html).

Example for cuda 12.1 and torch 2.1:
pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1/index.html

**Comment by alexsuakim** [comment]
Thanks for the suggestions! However, I tried to install with the command `mim install "mmcv>=2.0.0rc4, <2.2.0."` but I get this following error. This doesn't happen when I try to install version 2.2.0. Does anyone know how to resolve this when trying to set up for MMDetection?
<img width="940" alt="image" src="https://github.com/open-mmlab/mmcv/assets/99973140/834f51cc-ac58-4774-a602-9d89e0610841">

**Comment by SyedShafiq** [comment]
I am getting this error:

ImportError: /usr/local/lib/python3.8/dist-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

**Comment by vaidatascientist** [comment]
@alexsuakim I think if you use the CUDA 12.0+ versions it should work fine

**Comment by Lenleooo** [comment]
> **在我的例子中，我注释掉了 mmseg/ init.py**中第 60 行到第 62 行的部分代码，问题得到了解决

i love you! you are very very handsome!

**Comment by jannifer007** [comment]
thanks!this works for me!!!

**Comment by shukurullo2004** [comment]
> thanks!this works for me!!!



THANK YOU IT WORKS FOR ME ALSO

**Comment by sparshgarg23** [comment]
not sure but the issue is still persisting for me,I tried 
'''
!pip3 install openmim
!mim install mmengine
!mim install "mmcv>=2.0.0,<2.1.0"
'''
but  it gives failed to build wheel error.
if I don't put the constraints for 2.1.0,then I end up getting the same incompatible error.

**Comment by sevenzhigu** [comment]
> pip install mmcv==2.0.0rc4
> 
> try this, in my case it got fixed

useful for me

**Comment by HsinyuG** [comment]
In my case (Ubuntu 20.04, cuda 11.4, torch 2.4.1+cu118):
mmcv       2.1.0 
mmdet      3.2.0 
mmdet3d    1.4.0  
mmengine   0.10.5    
This combination works for me to run the test installation command.
Instead of running 
```
mim install 'mmcv>=2.0.0rc4'
mim install 'mmdet>=3.0.0'
```
I run 
```
mim install mmcv==2.1.0
mim install mmdet==3.2.0
```

**Comment by weikangqi** [comment]
so fuck stupid

**Comment by weixi234** [comment]
The problem is this:
cuda:12.1
torch:2.2.2
and i must install mmcv2.2.0,according [MMCV installation](https://mmcv.readthedocs.io/en/latest/get_started/installation.html)
but mmdet have no applicable version available

**Comment by MadVij2021** [comment]
> I changed "mmdet/**init**.py" line9 "2.2.0" to "2.2.1" to forcely make it compatible. The demo code is ok. but I don't know whether such a modification will cause other incompatibility issues

It seriously worked bruh😂 you are fantastic

**Comment by TimotheeWrightFicha** [comment]
Can't believe they have a colab demo script that crashes at first run bruh

**Comment by GandalfGondor** [comment]
> Change `mmcv_maximum_version = '2.2.0'` to `mmcv_maximum_version = '2.2.1'` and it works for me. ![image](https://private-user-images.githubusercontent.com/118429842/340080022-f957ef36-58dd-401d-a426-e817c92a1a3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDYzNzUsIm5iZiI6MTczNDAwNjA3NSwicGF0aCI6Ii8xMTg0Mjk4NDIvMzQwMDgwMDIyLWY5NTdlZjM2LTU4ZGQtNDAxZC1hNDI2LWU4MTdjOTJhMWEzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQxMjIxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjU3MmMwYWQ5MTY0ZDhkOTNlNzIwODMzMDg0ZTIwZmI1NzlmYmQ1NTM0M2FkY2I2ZDAzOWEzOGNhZDBjYzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U2OxF_8QATM2WV6HiqrsThFK5tIG-SRXNxdnRaIgo1A)


it works

**Comment by WASIDJ** [comment]
> I changed "mmdet/**init**.py" line9 "2.2.0" to "2.2.1" to forcely make it compatible. The demo code is ok. but I don't know whether such a modification will cause other incompatibility issues我将“mmdet/init.py“第9行“2.2.0”改为“2.2.1”，以便使其兼容。Demo代码是OK的。但我不知道这样的修改是否会导致其他不兼容的问题

god bless.
I love you!!!
mmmmum❤.

**Comment by anushka-kore** [comment]
Refer to my post. Hopefully, it helps- https://github.com/open-mmlab/mmdetection/discussions/12328

**Comment by vitorpmh** [comment]
> I changed "mmdet/**init**.py" line9 "2.2.0" to "2.2.1" to forcely make it compatible. The demo code is ok. but I don't know whether such a modification will cause other incompatibility issues

if anyone needs this for mmseg i changedl line 11 MMCV_MAX = '2.2.0' to MMCV_MAX = '2.2.1'

**Comment by Helen1p** [comment]
真是难用得要死

**Comment by shenshanf** [comment]
这种情况说明需要手动编译：[](https://mmcv.readthedocs.io/en/latest/get_started/build.html)

**Comment by marvinirwin** [comment]
This took me forever to figure out but I was able to get it all working in this notebook, in short I had to 

1. downgrade numpy to <2
2. Install everything
3. Comment out the mmdet version check

@Helen1p   搞了好久终于跑通了，这里有个简化版的 Google Colab 示例

https://colab.research.google.com/gist/marvinirwin/e938956321b8bda86ea708f81042fc3c/minimal-mmcv.ipynb

**Comment by jmorgan-wellovate** [comment]
This has got to be the worst and most garbage bug of all time. Not sure if the repo owners even care given all the people that have/are struggling with this issue and the lack of a clear/easy fix.

**Comment by kasteric** [comment]
> This has got to be the worst and most garbage bug of all time. Not sure if the repo owners even care given all the people that have/are struggling with this issue and the lack of a clear/easy fix.

The members no longer maintain this repo anymore. Maybe they have been fired.

**Comment by shenshanf** [comment]
建议各位源码编译的方式安装mmcv，编译用不了多久时间。

**Comment by kasteric** [comment]
> 建议各位源码编译的方式安装mmcv，编译用不了多久时间。

我源码编译了mmcv在h20上，用的sm_90架构flag，在mmdetection上同样的代码，同样的数据，AP几乎为0。应该产生了静默bug

**Comment by liuer12** [comment]
ZH：这个bug确实折磨人，折腾了好久。总结一下，不管你是使用mmdet还是mmpose或者是其他涉及安装mmdet的项目，最好不要通过pip或者mim安装mmdet，最好是通过源码安装mmdet，在执行"python install -v -e ."之前需要修改"mmdet/init.py" line9 "2.2.0" to "2.2.1"。
EN：This bug is indeed frustrating and has been causing problems for a long time. To summarize, whether you are using mmdet, mmpose, or any other project that involves installing mmdet, it is best not to install mmdet via pip or mim. Instead, it is recommended to install mmdet from source code. Before executing “python install -v -e .”, you need to modify line 9 of “mmdet/init.py” from “2.2.0” to “2.2.1”.

> Why is this error occurring? The reason is that we have released a new version but the downstream libraries are not yet supported. There are two solutions, one is to install a lower version of mmcv (but the lower version of mmcv may not provide support for torch2.2.0), and the other is to change the mmcv version restriction in the **init** file of the downstream libraries, which works fine this way.

**Comment by TC120** [comment]
in my case，I used “pip uninstall mmcv”， then "mim install 'mmcv==2.1.0'", it got fixed

**Comment by FeatureSpitter** [comment]
> > This has got to be the worst and most garbage bug of all time. Not sure if the repo owners even care given all the people that have/are struggling with this issue and the lack of a clear/easy fix.
> 
> The members no longer maintain this repo anymore. Maybe they have been fired.

all the MM projects are dead. So weird. I don't know any better alternatives.

**Comment by aakash-chakraborty1995** [comment]
> pip install mmcv==2.0.0rc4

This works for python==3.9.0

**Comment by juliaajan** [comment]
I had the same problem when trying to install the latest version of mmcv and mmdet. For mmpose 1.3.2, mmdet<3.3.0,>=3.0.0 was required, but mmdet 3.0.0 requires mmcv<2.1.0,>=2.0.0rc4 which I was ubable to install. The solution for me was to downgrade pytorch.

What solved the problem for me was:

- First uninstall any mmcv (and mmdet) versions that you might have installed
`pip uninstall mmdet`
`pip uninstall mmcv`

- Check your CUDA version
- `nvcc --version`
- use this docu to check which pytorch version is compatible with the CUDA and mmcv version that you want: https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-with-pip
- Than use the pytorch page to get the correct command for the pytorch version that you need: https://pytorch.org/get-started/previous-versions/ and install it
e.g. `pip install torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 --index-url https://download.pytorch.org/whl/cu118
` for CUDA 11.8

- again check the mmcv docs (link above) to generate the correct command to install mmcv with pip (installation with mim did not work for me)
 e.g.` pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html`
- finally, if needed, install the mmdet version that was specified in your error (for me, mmdet 3.0.0)
`mim install mmdet==3.0.0`

**Comment by kennykwan1419** [comment]
[juliaajan](https://github.com/juliaajan)   finish , thx

**Comment by Michael-Yi-Rong** [comment]
> > I changed "mmdet/**init**.py" line9 "2.2.0" to "2.2.1" to forcely make it compatible. The demo code is ok. but I don't know whether such a modification will cause other incompatibility issues我将“mmdet/init.py“第9行“2.2.0”改为“2.2.1”，以便使其兼容。Demo代码是OK的。但我不知道这样的修改是否会导致其他不兼容的问题
> 
> god bless. I love you!!! mmmmum❤.

1
