### ISSUE TITLE
[Bug] ascend pytorch23.0.RC1-1.8.1安装mmcv后import报错

### ISSUE THREAD

**Issue by BoomSky0416** [open-mmlab/mmcv#3204]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [X] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

python 3.7.5   
CANN 6.3.RC1
Pytorch 1.8.1

Package            Version     Editable project location
------------------ ----------- ------------------------------
absl-py            1.4.0
addict             2.4.0
apex               0.1+ascend
attr               0.3.2
attrs              23.1.0
auto-tune          0.1.0
certifi            2023.5.7
cffi               1.12.3
charset-normalizer 3.1.0
cycler             0.11.0
decorator          5.1.1
DLLogger           1.0.0
easydict           1.9
exceptiongroup     1.1.1
fonttools          4.38.0
grpcio             1.54.2
grpcio-tools       1.54.2
hccl               0.1.0
idna               3.4
importlib-metadata 6.6.0
iniconfig          2.0.0
joblib             1.2.0
kiwisolver         1.4.4
lxml               4.5.2
markdown-it-py     3.0.0
matplotlib         3.5.3
mdurl              0.1.2
mmcv               2.0.1       /workspace/open-mmlab-2.0/mmcv
mmengine           0.10.5
mpmath             1.3.0
numexpr            2.8.4
numpy              1.21.6
opc-tool           0.1.0
opencv-python      4.5.5.64
packaging          23.1
pandas             1.3.5
pathlib2           2.3.7.post1
Pillow             9.1.0
pip                23.1.2
pluggy             1.0.0
protobuf           4.23.0
psutil             5.9.5
pycocotools        2.0.6
pycparser          2.21
Pygments           2.18.0
pyparsing          3.0.9
pytest             7.3.1
python-dateutil    2.8.2
pytz               2023.3
PyYAML             6.0
requests           2.30.0
rich               13.9.4
schedule-search    0.0.1
scikit-learn       1.0.2
scipy              1.7.3
setuptools         41.2.0
six                1.16.0
sklearn            0.0
sympy              1.4
tables             3.7.0
te                 0.4.0
termcolor          2.5.0
threadpoolctl      3.1.0
tomli              2.0.1
torch              1.8.1
torch-npu          1.8.1.post1
torchvision        0.9.1
typing_extensions  4.5.0
urllib3            2.0.2
wheel              0.40.0
xdoctest           1.1.0
yapf               0.33.0
zipp               3.15.0

### Reproduces the problem - code sample

MMCV_WITH_OPS=1 MAX_JOBS=8 FORCE_NPU=1 python setup.py build_ext
MMCV_WITH_OPS=1 FORCE_NPU=1 python setup.py develop

### Reproduces the problem - command or script

import mmcv

### Reproduces the problem - error message

>>> import mmcv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/open-mmlab-2.0/mmcv/mmcv/__init__.py", line 4, in <module>
    from .image import *
  File "/workspace/open-mmlab-2.0/mmcv/mmcv/image/__init__.py", line 5, in <module>
    from .geometric import (cutout, imcrop, imflip, imflip_, impad,
  File "/workspace/open-mmlab-2.0/mmcv/mmcv/image/geometric.py", line 7, in <module>
    from mmengine.utils import to_2tuple
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmengine-0.10.5-py3.7.egg/mmengine/__init__.py", line 3, in <module>
    from .config import *
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmengine-0.10.5-py3.7.egg/mmengine/config/__init__.py", line 2, in <module>
    from .config import Config, ConfigDict, DictAction, read_base
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmengine-0.10.5-py3.7.egg/mmengine/config/config.py", line 26, in <module>
    from mmengine.fileio import dump, load
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmengine-0.10.5-py3.7.egg/mmengine/fileio/__init__.py", line 2, in <module>
    from .backends import (BaseStorageBackend, HTTPBackend, LmdbBackend,
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmengine-0.10.5-py3.7.egg/mmengine/fileio/backends/__init__.py", line 2, in <module>
    from .base import BaseStorageBackend
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmengine-0.10.5-py3.7.egg/mmengine/fileio/backends/base.py", line 5, in <module>
    from mmengine.logging import print_log
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmengine-0.10.5-py3.7.egg/mmengine/logging/__init__.py", line 3, in <module>
    from .logger import MMLogger, print_log
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmengine-0.10.5-py3.7.egg/mmengine/logging/logger.py", line 13, in <module>
    from termcolor import colored
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/termcolor-2.5.0-py3.7.egg/termcolor/__init__.py", line 5, in <module>
    from termcolor.termcolor import ATTRIBUTES, COLORS, HIGHLIGHTS, RESET, colored, cprint
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/termcolor-2.5.0-py3.7.egg/termcolor/termcolor.py", line 34, in <module>
    from ._types import Attribute, Color, Highlight
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/termcolor-2.5.0-py3.7.egg/termcolor/_types.py", line 3, in <module>
    from typing import Literal
ImportError: cannot import name 'Literal' from 'typing' (/usr/local/python3.7.5/lib/python3.7/typing.py)

**Comment by BoomSky0416** [comment]
@momo609
