### ISSUE TITLE
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('Cython')

### ISSUE THREAD

**Issue by guotong1988** [open-mmlab/mmcv#337]
Python3.6.8, `pip3 install mmcv` get error:

```
    ERROR: Command errored out with exit status 1:
     command: /home/gt/Py36/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n86bgsfi/mmcv/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n86bgsfi/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cwvmv3h_
         cwd: /tmp/pip-install-n86bgsfi/mmcv/
    Complete output (21 lines):
    Download error on https://pypi.org/simple/Cython/: unknown url type: https -- Some packages may not be found!
    Couldn't find index page for 'Cython' (maybe misspelled?)
    Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
    No local packages or working download links found for Cython
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-n86bgsfi/mmcv/setup.py", line 6, in <module>
        dist.Distribution().fetch_build_eggs(['Cython', 'numpy>=1.11.1'])
      File "/home/gt/Py36/lib/python3.6/site-packages/setuptools/dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/gt/Py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "/home/gt/Py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "/home/gt/Py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1075, in obtain
        return installer(requirement)
      File "/home/gt/Py36/lib/python3.6/site-packages/setuptools/dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/gt/Py36/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('Cython')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

@hellock @xvjiarui @OceanPang @yhcao6 Thank you!

**Comment by guotong1988** [comment]
pip3 install Cython
pip3 install pytest-runner
