### ISSUE TITLE
Error when useing Config.fromfile(args.config) ：SyntaxError and FileNotFoundError

### ISSUE THREAD

**Issue by Fang6** [open-mmlab/mmcv#364]
Hi guys：
when I use mmdetection :
`python tools/train.py configs/fcos/fcos_x101_64x4d_fpn_gn-head_mstrain_640-800_4x2_2x_coco.py --gpus 1 --no-validate --work-dir work_dirs`
I get the following error:
```
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 68, in main
    cfg = Config.fromfile(args.config)
  File "/home/wangfeng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 165, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/home/wangfeng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 95, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/wangfeng/anaconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpv339bd1t/tmpr_4q7t4s.py", line 24
    multiscale_mode='value',
                  ^
SyntaxError: invalid syntax
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x2b08085483b0>
Traceback (most recent call last):
  File "/home/wangfeng/anaconda3/envs/open-mmlab/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/wangfeng/anaconda3/envs/open-mmlab/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpv339bd1t/tmpr_4q7t4s.py'
```
I think it is similar to the issues[https://github.com/open-mmlab/mmcv/issues/248](url)
but,my config.py is right?
How can I deal with the problem

**Comment by hellock** [comment]
The config file you used contains syntax errors.

**Comment by Fang6** [comment]
> The config file you used contains syntax errors.

Thank you for your replying. I did not modify the config file

**Comment by xvjiarui** [comment]
Hi @Fang6 
Sorry for the late reply. 
Could you please try the latest mmdetection? I couldn't reproduce this error. 
You may try again with latest code.
