### ISSUE TITLE
KeyError: '\\C'

### ISSUE THREAD

**Issue by ousinkou** [open-mmlab/mmcv#454]
I  reinstall mmcv on win10 and encouter this problem. How could I fix it?

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pytorch-env\lib\sre_parse.py", line 1015, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\C'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pytorch-env\lib\site-packages\mmcv\utils\config.py", line 127, in _file2dict
    temp_config_file.name)
  File "C:\ProgramData\Anaconda3\envs\pytorch-env\lib\site-packages\mmcv\utils\config.py", line 108, in _substitute_predefined_vars
    config_file = re.sub(regexp, value, config_file)
  File "C:\ProgramData\Anaconda3\envs\pytorch-env\lib\re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\ProgramData\Anaconda3\envs\pytorch-env\lib\re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "C:\ProgramData\Anaconda3\envs\pytorch-env\lib\re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\ProgramData\Anaconda3\envs\pytorch-env\lib\sre_parse.py", line 1018, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \C at position 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pytorch-env\lib\shutil.py", line 402, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] 目录不是空的。: 'C:\\Temp\\tmpvk8jf5zz'

**Comment by ousinkou** [comment]
File "C:\ProgramData\Anaconda3\envs\pytorch-env\lib\site-packages\mmcv\utils\config.py", line 108, in _substitute_predefined_vars
config_file = re.sub(regexp, value, config_file)

There's a bug when parsing "\\" in windows path. I add `value=value.replace("\\","/")` , and it works OK.
