### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'ga_assigner'

### ISSUE THREAD

**Issue by lxg15066629402** [open-mmlab/mmcv#486]
Traceback (most recent call last):
  File "tools/train.py", line 176, in <module>
    main()
  File "tools/train.py", line 138, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/dicom/Jone/Dection_mass/mmdet/models/builder.py", line 48, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/dicom/Jone/Dection_mass/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/mmcv-0.5.9-py3.7-linux-x86_64.egg/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
  File "/dicom/Jone/Dection_mass/mmdet/models/detectors/mask_rcnn.py", line 23, in __init__
    pretrained=pretrained)
  File "/dicom/Jone/Dection_mass/mmdet/models/detectors/two_stage.py", line 36, in __init__
    self.rpn_head = build_head(rpn_head_)
  File "/dicom/Jone/Dection_mass/mmdet/models/builder.py", line 40, in build_head
    return build(cfg, HEADS)
  File "/dicom/Jone/Dection_mass/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/mmcv-0.5.9-py3.7-linux-x86_64.egg/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
  File "/dicom/Jone/Dection_mass/mmdet/models/dense_heads/ga_rpn_head.py", line 22, in __init__
    1, in_channels, background_label=0, **kwargs)
  File "/dicom/Jone/Dection_mass/mmdet/models/dense_heads/guided_anchor_head.py", line 193, in __init__
    self.ga_assigner = build_assigner(self.train_cfg.ga_assigner)
  File "/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/mmcv-0.5.9-py3.7-linux-x86_64.egg/mmcv/utils/config.py", line 34, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'ga_assigner'

**Comment by hellock** [comment]
You may check the config file.

**Comment by lxg15066629402** [comment]
yes, I have checked the config file. Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kai Chen"<notifications@github.com&gt;; 
发送时间: 2020年8月13日(星期四) 下午3:17
收件人: "open-mmlab/mmcv"<mmcv@noreply.github.com&gt;; 
抄送: "Jone"<it_lxg@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [open-mmlab/mmcv] AttributeError: &#39;ConfigDict&#39; object has no attribute &#39;ga_assigner&#39; (#486)





 
You may check the config file.
