### ISSUE TITLE
ImportError: cannot import name 'ContextBlock' from 'mmcv.ops' (/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py)

### ISSUE THREAD

**Issue by lxg15066629402** [open-mmlab/mmcv#503]
2020-08-18 11:01:47.183324: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-08-18 11:01:47.183353: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "trainer.py", line 10, in <module>
    from model.add_model import MassDectection
  File "/data/Adam/models/np_model/model/add_model/MassDectection.py", line 17, in <module>
    from mmdet.ops import RoIAlign, RoIPool
  File "/data/Jone/mmdetection/mmdet/ops/__init__.py", line 5, in <module>
    from mmcv.ops import (ContextBlock, Conv2d, ConvTranspose2d, ConvWS2d,
ImportError: cannot import name 'ContextBlock' from 'mmcv.ops' (/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py)

**Comment by hellock** [comment]
In the latest version, `ContextBlock` is not in `mmcv.ops` but `mmcv.cnn`.
