### ISSUE TITLE
distributed training 

### ISSUE THREAD

**Issue by monsters-s** [open-mmlab/mmcv#551]
I have two 1080ti, about 20 GB memory.  When I use distributed training like this ' ./tools/dist_train.sh configs/detectors/detectors_cascade_rcnn_r50_1x_coco.py  2', there is an error :
2020-09-12 20:38:18,110 - mmdet - INFO - Start running, host: lsw@sedlight, work_dir: /home/lsw/mmdetection/work_dirs/detectors_cascade_rcnn_r50_1x_coco
2020-09-12 20:38:18,110 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "./tools/train.py", line 177, in <module>
    main()
  File "./tools/train.py", line 173, in main
    meta=meta)
  File "/home/lsw/mmdetection/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lsw/mmcv/mmcv/runner/epoch_based_runner.py", line 123, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lsw/mmcv/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 719, in __init__
    w.start()
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/util.py", line 455, in spawnv_passfds
    False, False, None)
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/lsw/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/lsw/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/detectors/detectors_cascade_rcnn_r50_1x_coco.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

but when I use 'python tools/train.py configs/detectors/detectors_cascade_rcnn_r50_1x_coco.py' or './tools/dist_train.sh configs/detectors/detectors_cascade_rcnn_r50_1x_coco.py  1 ', I can train rightly

I'm sorry to ask what should I do?

**Comment by hellock** [comment]
Seems that your CPU memory is not sufficient.

**Comment by monsters-s** [comment]
@hellock  Thanks.I have solved it.
