### ISSUE TITLE
unable to compile from source

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmcv#568]
```bash
MMCV_WITH_OPS=1 python setup.py build -j4 develop
```

this would produce

[log.txt](https://github.com/open-mmlab/mmcv/files/5244297/log.txt)

**Comment by ZwwWayne** [comment]
I tried your command and meet the same error.  After I met this error, I try `MMCV_WITH_OPS=1 python setup.py build develop` and it compiles the flow op successfully.
I think the bug is caused by `-j4`, if you remove it, you could compile all the modules successfully.

**Comment by twmht** [comment]
@ZwwWayne 

thank you for the help, btw, this might be one of the commit causing this issue, since I never have this problem before even with `-j4`.

**Comment by ZwwWayne** [comment]
Thanks for your report, we will check that.

**Comment by MeteoriteWeny** [comment]
I've tried both ways to compile mmcv-full from source, but none of them worked. (I've tried to use pip install mmcv-full, it didn't work either )  I'm running at Windows 10 and this happened when I tried to install mmdetection with pytorch=1.6.0+CUDA10.2 in an Anaconda virtual environment. 
During the compiling procedure, the same exception occurred as below:

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "E:\Anaconda\envs\open-mmlab\lib\site-packages\torch\utils\cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "E:\Anaconda\envs\open-mmlab\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 219, in <module>
    zip_safe=False)
  File "E:\Anaconda\envs\open-mmlab\lib\site-packages\setuptools\__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "E:\Anaconda\envs\open-mmlab\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "E:\Anaconda\envs\open-mmlab\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "E:\Anaconda\envs\open-mmlab\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\Anaconda\envs\open-mmlab\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "E:\Anaconda\envs\open-mmlab\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "E:\Anaconda\envs\open-mmlab\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\Anaconda\envs\open-mmlab\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "E:\Anaconda\envs\open-mmlab\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "E:\Anaconda\envs\open-mmlab\lib\site-packages\torch\utils\cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "E:\Anaconda\envs\open-mmlab\lib\distutils\command\build_ext.py", line 447, in build_extensions
    self._build_extensions_parallel()
  File "E:\Anaconda\envs\open-mmlab\lib\distutils\command\build_ext.py", line 469, in _build_extensions_parallel
    fut.result()
  File "E:\Anaconda\envs\open-mmlab\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "E:\Anaconda\envs\open-mmlab\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "E:\Anaconda\envs\open-mmlab\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\Anaconda\envs\open-mmlab\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "E:\Anaconda\envs\open-mmlab\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "E:\Anaconda\envs\open-mmlab\lib\site-packages\torch\utils\cpp_extension.py", line 631, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "E:\Anaconda\envs\open-mmlab\lib\site-packages\torch\utils\cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "E:\Anaconda\envs\open-mmlab\lib\site-packages\torch\utils\cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

I wonder if  there's any solution of this scenario, thanks.

**Comment by ZwwWayne** [comment]
Hi @MeteoriteWeny ,
This is not a full log of the compilation. Could you record the full log as this issue and create a new Issue to report your bug? Your issue is more like some problem with the Windows Support and is different from this issue.
