### ISSUE TITLE
pytorch2onnx --verify failing for retinanet and output incorrect

### ISSUE THREAD

**Issue by pablovela5620** [open-mmlab/mmcv#601]
Getting the following error from trying to convert `retinanet_r50_fpn_1x_coco.py` after running
``` 
python tools/pytorch2onnx.py configs/retinanet/retinanet_test_r50_fpn_1x_coco.py ~/0Dev/data/mmdetection/retinanet_r50_fpn_1x_coco_20200130-c2398f9e.pth --output-file ~/0Dev/data/mmdetection/retinanet_r50_fpn_1x_coco_20200130-c2398f9e.onnx --verify --input-img demo/demo.jpg
```
```
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 170, in <module>
    normalize_cfg=normalize_cfg)
  File "tools/pytorch2onnx.py", line 85, in pytorch2onnx
    pytorch_result[0][:, 4], onnx_results[:, 4]
TypeError: list indices must be integers or slices, not tuple
```
It seems like the error is in the final assert statement. I tried changing
```python 
pytorch_result[0][:, 4], onnx_results[:, 4]
```
to 
``` python 
pytorch_result[0][0][:, 4], onnx_results[:, 4]
```
but then the error
```
ValueError: operands could not be broadcast together with shapes (9,) (6,) 
```
It seems like the model did successfully convert but the outputs seem incorrect. 

I visualized by adding the following to the end of the verify function
```python
# only compare a part of result
bbox_results = bbox2result(det_bboxes, det_labels, 80)
onnx_results = bbox_results[0]
mmcv.imshow_bboxes(input_img, bbox_results)
```
I got the following image from the visualization
![image](https://user-images.githubusercontent.com/25287427/95019742-25137e80-0635-11eb-98b1-811d49ca2a10.png)

**Comment by pablovela5620** [comment]
Whoops, posted this on the wrong repo. Closed
