### ISSUE TITLE
About mmcv : libtorch_cpu.so

### ISSUE THREAD

**Issue by Purdandelion** [open-mmlab/mmcv#660]
Hello, I install mmcv and tourch(pip install mmcv-full), they meet version requirement.  it is true when I import them,  but there is a wrong in mmcv when I run code.  Can you help me?
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
  File "/home/iwogh/.local/lib/python3.6/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/iwogh/.local/lib/python3.6/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/iwogh/.local/lib/python3.6/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by ZwwWayne** [comment]
Hi @Purdandelion ，
What version of PyTorch, CUDA, gcc are you using? According to the discussion in https://github.com/open-mmlab/mmdetection/issues/2627, there are some incompatibility issues in some versions of PyTorch and CUDA.
