### ISSUE TITLE
Installing specific version of mmcv with find-links fails with new pip-20.3

### ISSUE THREAD

**Issue by Erotemic** [open-mmlab/mmcv#679]
I'm not sure what's happening. 

With pip 20.1.1 I was able to run: 

```
pip install mmcv_full==1.0.5+torch1.6.0+cpu -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html
```

and it works fine. 

After upgrading pip to 20.3 I run the same command and get: 

```
Looking in links: https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html
ERROR: Exception:
Traceback (most recent call last):
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'mmcv-full'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 210, in _main
    status = self.run(options, args)
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 82, in from_requirement
    if not cands:
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_vendor/resolvelib/structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 96, in __bool__
    return any(self)
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 20, in _deduplicated_by_version
    for candidate in candidates:
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 203, in iter_index_candidates
    version=ican.version,
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 145, in _make_candidate_from_link
    link, template, factory=self, name=name, version=version,
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
    wheel_version = Version(wheel.version)
  File "/home/joncrall/.local/conda/envs/py36/lib/python3.6/site-packages/pip/_vendor/packaging/version.py", line 298, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
pip._vendor.packaging.version.InvalidVersion: Invalid version: '1.0.5+torch1.6.0+cpu'
```

OS is Ubuntu 20.04.

**Comment by Erotemic** [comment]
Running a version with +cpu also fails:

```
pip install mmcv_full==1.0.5+torch1.6.0 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html
``` 


However, removing both torch and cpu specification works: 

```
pip install mmcv_full -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html
```

That works, but it takes a very long time and maxes out several of my cpu cores. (Its probably solving some dependency resolution problem).

**Comment by hellock** [comment]
Thanks for reporting! `pip install mmcv_full` actually downloads the package from pypi and compiles it locally. PyTorch also adopts similar package names, i.e., `1.7.0+cu110`, does it also breaks?

**Comment by Hastyrush** [comment]
Hi, the same problem occurred to me. I'm using pytorch 1.7.0 with cudatoolkit 10.2 and the command 

'pip install mmcv-full==latest+torch1.7.0+cu102 -f https://download.openmmlab.com/mmcv/dist/index.html'

gives the same error as specified.

**Comment by hellock** [comment]
> Hi, the same problem occurred to me. I'm using pytorch 1.7.0 with cudatoolkit 10.2 and the command
> 
> 'pip install mmcv-full==latest+torch1.7.0+cu102 -f https://download.openmmlab.com/mmcv/dist/index.html'
> 
> gives the same error as specified using pip 20.3. It works properly with pip 20.2.4

As a workaround suggested by @Erotemic, you can use `pip install mmcv-full==latest+torch1.7.0+cu102 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html --use-deprecated=legacy-resolver`.

**Comment by Hastyrush** [comment]
Yup, already solved it. Downgrading the pip version to 20.2.4 in the conda environment works as well, thanks!

**Comment by yy897673025** [comment]
Thank you,it does work!

**Comment by yy897673025** [comment]
Thank you,it does work!

**Comment by Adblu** [comment]
Downgrading to pip 20.2.4 works however it cannot be a proper solution, especially when my pipeline is fully automated.

**Comment by Erotemic** [comment]
@hellock The issue I raised in the pip repo: https://github.com/pypa/pip/issues/9183 has some insights. 

The main issue is that the mmcv version scheme doesn't conform to [PEP 440](https://www.python.org/dev/peps/pep-0440/). 

From what I understand the two `+` characters are the main issue. The reason torch `1.7.0+cu110` works is because there is only one `+` character. 

PEP440 says that you can specify one `+` and everything after it is a "local version", which can only contain alphanumeric and the `.` character. I think a semi-robust fix would be changing `latest+torch1.7.0+cu102` to `latest+torch1.7.0.cu102`. I don't think two hard dependencies in the version string is well supported at the moment, so this might be the best we can do.

---

For everyone downgrading pip, the better (but still temporary) solution may be to use the `--use-deprecated=legacy-resolver` for now instead of forcing a downgrade.

**Comment by hellock** [comment]
Thanks. @ycxioooong will fix the version scheme on the side of mmcv.

**Comment by ycxioooong** [comment]
Please see the latest README.md for installation with pip20.3

**Comment by Erotemic** [comment]
Specifying the torch and cuda versions in the `--find-links` URL seems like an elegant workaround for this problem. Thank you all for working on and fixing this issue.
