### ISSUE TITLE
mmdetection/tools/pytorch2onnx.py gives error in torch.nn.functional.interpolate() with scale_factor and opset_version=11

### ISSUE THREAD

**Issue by mathmanu** [open-mmlab/mmcv#690]
Hi,

I am trying to export to ONNX, the model generated by retinanet_r50_fpn_2x_coco.py in mmdetection. This model exports fine without any issue. I am using ONNX opset_version=11

**I wanted to use scale_factor in the ONNX Resize() operator and modified the forward() method of FPN class in mmdetection as follows:**
        for i in range(used_backbone_levels - 1, 0, -1):
            # In some cases, fixing `scale factor` (e.g. 2) is preferred, but
            #  it cannot co-exist with `size` in `F.interpolate`.
            if 'scale_factor' in self.upsample_cfg:
                laterals[i - 1] += F.interpolate(laterals[i],
                                                 **self.upsample_cfg)
            else:
                prev_shape = laterals[i - 1].shape[2:]
                cur_shape = laterals[i].shape[2:]
                **scale_factor = (float(prev_shape[0]) / float(cur_shape[0]), float(prev_shape[1]) / float(cur_shape[1]))**
                laterals[i - 1] += F.interpolate(
                    laterals[i], scale_factor=scale_factor, **self.upsample_cfg)

**But when I pass scale_factor to interpolate, I get the following error:**

/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/bin/python /user/a0393608/files/work/github/open-mmlab/mmdetection/tools/pytorch2onnx.py ./configs/retinanet/retinanet_r50_fpn_2x_coco.py http://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r50_fpn_2x_coco/retinanet_r50_fpn_2x_coco_20200131-fdb43119.pth --out mmdet_retinanet_r50_fpn_2x_coco_1216x800.onnx --shape 800 1216 --opset-version 11
Traceback (most recent call last):
  File "/user/a0393608/files/work/github/open-mmlab/mmdetection/tools/pytorch2onnx.py", line 203, in <module>
    dataset=args.dataset)
  File "/user/a0393608/files/work/github/open-mmlab/mmdetection/tools/pytorch2onnx.py", line 52, in pytorch2onnx
    opset_version=opset_version)
  File "/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/lib/python3.7/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/lib/python3.7/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/lib/python3.7/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/lib/python3.7/site-packages/torch/onnx/utils.py", line 421, in _model_to_graph
    dynamic_axes=dynamic_axes, input_names=input_names)
  File "/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/lib/python3.7/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/lib/python3.7/site-packages/torch/onnx/__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/lib/python3.7/site-packages/torch/onnx/utils.py", line 934, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/lib/python3.7/site-packages/mmcv/onnx/symbolic.py", line 17, in symbolic_fn
    g, interpolate_mode, args)
  File "/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 254, in _get_interpolate_attributes
    scales = _interpolate_get_scales_if_available(g, scales)
  File "/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 229, in _interpolate_get_scales_if_available
    available_scales = _maybe_get_const(scales[0], 'f') != -1 and not _is_none(
  File "/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 64, in _maybe_get_const
    return _parse_arg(value, desc)
  File "/user/a0393608/files/apps/anaconda3/envs/pytorch-mmdet/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 33, in _parse_arg
    return float(tval)
**ValueError: only one element tensors can be converted to Python scalars**

Process finished with exit code 1

**There is no issue if I use opset_version=12.**

**After debugging at bit, I found out that if I comment out a few lines in mmcv/onnx/symbolic.py, it works fine in opset_version=11:**
def register_extra_symbolics(opset=11):
    register_op('one_hot', one_hot, '', opset)
    register_op('im2col', im2col, '', opset)
    register_op('topk', topk, '', opset)
    register_op('softmax', softmax, '', opset)
    register_op('constant_pad_nd', constant_pad_nd, '', opset)
    register_op('reflection_pad1d', reflection_pad1d, '', opset)
    register_op('reflection_pad2d', reflection_pad2d, '', opset)
    register_op('reflection_pad3d', reflection_pad3d, '', opset)
    register_op('avg_pool1d', avg_pool1d, '', opset)
    register_op('avg_pool2d', avg_pool2d, '', opset)
    register_op('avg_pool3d', avg_pool3d, '', opset)
    register_op('adaptive_avg_pool1d', adaptive_avg_pool1d, '', opset)
    register_op('adaptive_avg_pool2d', adaptive_avg_pool2d, '', opset)
    register_op('adaptive_avg_pool3d', adaptive_avg_pool3d, '', opset)
    register_op('masked_select', masked_select, '', opset)
    #register_op('upsample_nearest1d', upsample_nearest1d, '', opset)
    #register_op('upsample_nearest2d', upsample_nearest2d, '', opset)
    #register_op('upsample_nearest3d', upsample_nearest3d, '', opset)
    #register_op('upsample_linear1d', upsample_linear1d, '', opset)
    #register_op('upsample_bilinear2d', upsample_bilinear2d, '', opset)
    #register_op('upsample_trilinear3d', upsample_trilinear3d, '', opset)
    #register_op('upsample_bicubic2d', upsample_bicubic2d, '', opset)
    register_op('new_full', new_full, '', opset)

**I am using python 3.7 and following packages:**
onnx                      1.8.0                    pypi_0    pypi
pytorch                   1.7.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
torchvision               0.6.0                    pypi_0    pypi

**Comment by RunningLeon** [comment]
Strongly suggest you use pytorch=1.6.0 and opset=11. Up to now, tests are not fully covered with Pytorch=1.7.0.
