### ISSUE TITLE
Cannot install mmcv on RTX3090

### ISSUE THREAD

**Issue by mmeendez8** [open-mmlab/mmcv#691]
I have followed the next steps:
```
conda create -n mmendez-mmdet python=3.7 -y
conda activate mmendez-mmdet
conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch
```
Then I have tried to install mmcv from source as suggested in https://github.com/open-mmlab/mmdetection/pull/4176 with: 
```
MMCV_WITH_OPS=1 MMCV_CUDA_ARGS='-gencode=arch=compute_80,code=sm_80' pip install -e .
```
Error is: 
```

Obtaining file:///media/data/workspace/mmendez/mmcv
Requirement already satisfied: addict in /media/data/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages (from mmcv-full==1.2.1) (2.4.0)
Requirement already satisfied: numpy in /media/data/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages (from mmcv-full==1.2.1) (1.19.2)
Requirement already satisfied: Pillow in /media/data/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages (from mmcv-full==1.2.1) (8.0.1)
Requirement already satisfied: pyyaml in /media/data/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages (from mmcv-full==1.2.1) (5.3.1)
Requirement already satisfied: yapf in /media/data/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages (from mmcv-full==1.2.1) (0.30.0)
Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full
    ERROR: Command errored out with exit status 1:
     command: /opt/miniconda3/envs/mmendez-mmdet/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/media/data/workspace/mmendez/mmcv/setup.py'"'"'; __file__='"'"'/media/data/workspace/mmendez/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /media/data/workspace/mmendez/mmcv/
    Complete output (87 lines):
    running develop
    running egg_info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._flow_warp_ext' extension
    Emitting ninja build file /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Using envvar MAX_JOBS (4) as the number of workers...
    ninja: no work to do.
    g++ -pthread -shared -B /opt/miniconda3/envs/mmendez-mmdet/compiler_compat -L/opt/miniconda3/envs/mmendez-mmdet/lib -Wl,-rpath=/opt/miniconda3/envs/mmendez-mmdet/lib -Wl,--no-as-needed -Wl,--sysroot=/ /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/./mmcv/video/optflow_warp/flow_warp_module.o /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/./mmcv/video/optflow_warp/flow_warp.o -o build/lib.linux-x86_64-3.7/mmcv/_flow_warp_ext.cpython-37m-x86_64-linux-gnu.so
    building 'mmcv._ext' extension
    Emitting ninja build file /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Using envvar MAX_JOBS (4) as the number of workers...
    [1/39] /usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/media/data/workspace/mmendez/mmcv/mmcv/ops/csrc -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/TH -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/miniconda3/envs/mmendez-mmdet/include/python3.7m -c -c /media/data/workspace/mmendez/mmcv/mmcv/ops/csrc/pytorch/focal_loss_cuda.cu -o /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/focal_loss_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -gencode=arch=compute_80,code=sm_80 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/focal_loss_cuda.o
    /usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/media/data/workspace/mmendez/mmcv/mmcv/ops/csrc -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/TH -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/miniconda3/envs/mmendez-mmdet/include/python3.7m -c -c /media/data/workspace/mmendez/mmcv/mmcv/ops/csrc/pytorch/focal_loss_cuda.cu -o /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/focal_loss_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -gencode=arch=compute_80,code=sm_80 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_80'
    [2/39] /usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/media/data/workspace/mmendez/mmcv/mmcv/ops/csrc -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/TH -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/miniconda3/envs/mmendez-mmdet/include/python3.7m -c -c /media/data/workspace/mmendez/mmcv/mmcv/ops/csrc/pytorch/carafe_naive_cuda.cu -o /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/carafe_naive_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -gencode=arch=compute_80,code=sm_80 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/carafe_naive_cuda.o
    /usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/media/data/workspace/mmendez/mmcv/mmcv/ops/csrc -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/TH -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/miniconda3/envs/mmendez-mmdet/include/python3.7m -c -c /media/data/workspace/mmendez/mmcv/mmcv/ops/csrc/pytorch/carafe_naive_cuda.cu -o /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/carafe_naive_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -gencode=arch=compute_80,code=sm_80 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_80'
    [3/39] /usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/media/data/workspace/mmendez/mmcv/mmcv/ops/csrc -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/TH -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/miniconda3/envs/mmendez-mmdet/include/python3.7m -c -c /media/data/workspace/mmendez/mmcv/mmcv/ops/csrc/pytorch/nms_cuda.cu -o /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/nms_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -gencode=arch=compute_80,code=sm_80 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/nms_cuda.o
    /usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/media/data/workspace/mmendez/mmcv/mmcv/ops/csrc -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/TH -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/miniconda3/envs/mmendez-mmdet/include/python3.7m -c -c /media/data/workspace/mmendez/mmcv/mmcv/ops/csrc/pytorch/nms_cuda.cu -o /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/nms_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -gencode=arch=compute_80,code=sm_80 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_80'
    [4/39] /usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/media/data/workspace/mmendez/mmcv/mmcv/ops/csrc -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/TH -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/miniconda3/envs/mmendez-mmdet/include/python3.7m -c -c /media/data/workspace/mmendez/mmcv/mmcv/ops/csrc/pytorch/nms_rotated_cuda.cu -o /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -gencode=arch=compute_80,code=sm_80 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/nms_rotated_cuda.o
    /usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/media/data/workspace/mmendez/mmcv/mmcv/ops/csrc -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/TH -I/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/miniconda3/envs/mmendez-mmdet/include/python3.7m -c -c /media/data/workspace/mmendez/mmcv/mmcv/ops/csrc/pytorch/nms_rotated_cuda.cu -o /media/data/workspace/mmendez/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -gencode=arch=compute_80,code=sm_80 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    nvcc fatal   : Unsupported gpu architecture 'compute_80'
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1522, in _run_ninja_build
        env=env)
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/media/data/workspace/mmendez/mmcv/setup.py", line 228, in <module>
        zip_safe=False)
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
        build_ext.build_extensions(self)
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/opt/miniconda3/envs/mmendez-mmdet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/miniconda3/envs/mmendez-mmdet/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/media/data/workspace/mmendez/mmcv/setup.py'"'"'; __file__='"'"'/media/data/workspace/mmendez/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

Note I also tried pytorch nightly build with same result...

**Comment by RyanXLi** [comment]
Please check your CUDA version, which is normally linked in `/usr/local/cuda`. Make sure the version is higher than 11.0, otherwise it will not support sm_80.
