### ISSUE TITLE
mmcv is not support pytorch1.8.0.dev20201117

### ISSUE THREAD

**Issue by 13517592731** [open-mmlab/mmcv#721]
My environment is：Python3.7.9, cuda11.1, cudnn8.0.5, rtx3090
When I run mmpose, I had a mistake:
Traceback (most recent call last):
  File "demo/top_down_video_demo_with_mmdet.py", line 8, in <module>
    from mmdet.apis import inference_detector, init_detector
  File "/home/machine/project/python/mmpose/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/machine/project/python/mmpose/mmdetection/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/home/machine/application/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/machine/application/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/machine/application/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/machine/application/anaconda3/envs/mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/machine/application/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv

How can I solve this problem？

**Comment by ycxioooong** [comment]
Hi @13517592731  We will support PyTorch1.8 when it becomes the stable version.
