### ISSUE TITLE
import error after install mmcv 0.2.8

### ISSUE THREAD

**Issue by notfox** [open-mmlab/mmcv#73]
install mmcv success:
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
pip install .

but import error

 import mmcv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xgf/mmcv/mmcv/__init__.py", line 7, in <module>
    from .video import *
  File "/home/xgf/mmcv/mmcv/video/__init__.py", line 3, in <module>
    from .optflow import (flowread, flowwrite, quantize_flow,
  File "/home/xgf/mmcv/mmcv/video/optflow.py", line 6, in <module>
    from mmcv._ext import flow_warp_c
ModuleNotFoundError: No module named 'mmcv._ext'

anyone can help me? thanks

**Comment by notfox** [comment]
sorry,wrong PYTHONPATH

**Comment by marshallwu1** [comment]
> sorry,wrong PYTHONPATH

what do you mean by wrong PYTHONPATH ?
