### ISSUE TITLE
ModuleNotFoundError: No module named 'pytest'

### ISSUE THREAD

**Issue by shinya7y** [open-mmlab/mmcv#762]
It seems a new runtime requirement from https://github.com/open-mmlab/mmcv/pull/673

```
Traceback (most recent call last):
  File "./tools/train.py", line 8, in <module>
    import mmcv
  File "/home/shinya7y/miniconda3/envs/mmd270/lib/python3.7/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/shinya7y/miniconda3/envs/mmd270/lib/python3.7/site-packages/mmcv/fileio/__init__.py", line 4, in <module>
    from .io import dump, load, register_handler
  File "/home/shinya7y/miniconda3/envs/mmd270/lib/python3.7/site-packages/mmcv/fileio/io.py", line 4, in <module>
    from ..utils import is_list_of, is_str
  File "/home/shinya7y/miniconda3/envs/mmd270/lib/python3.7/site-packages/mmcv/utils/__init__.py", line 36, in <module>
    from .parrots_jit import jit, skip_no_elena, skip_no_parrots
  File "/home/shinya7y/miniconda3/envs/mmd270/lib/python3.7/site-packages/mmcv/utils/parrots_jit.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

**Comment by hellock** [comment]
Thanks for reporting the bug! It has been fixed in #763, and a new patch version will be released.
