### ISSUE TITLE
Importing flow_warp_c giving numpy size change errors

### ISSUE THREAD

**Issue by agneevguin** [open-mmlab/mmcv#810]
Receiving ValueError while importing mmcv, specifically flow_warp_c.

```
>>> from mmcv._ext import flow_warp_c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxxx/anaconda2/envs/conda_env/lib/python3.7/site-packages/mmcv/__init__.py", line 8, in <module>
    from .video import *
  File "/home/xxxxx/anaconda2/envs/conda_env/lib/python3.7/site-packages/mmcv/video/__init__.py", line 3, in <module>
    from .optflow import (dequantize_flow, flow_warp, flowread, flowwrite,
  File "/home/xxxxx/anaconda2/envs/conda_env/lib/python3.7/site-packages/mmcv/video/optflow.py", line 4, in <module>
    from mmcv._ext import flow_warp_c
  File "mmcv/video/optflow_warp/flow_warp_module.pyx", line 1, in init mmcv._ext
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

Any suggestions or help?

**Comment by agneevguin** [comment]
This was an issue in mmcv version 0.5.9
Can be fixed with `pip install mmcv==0.6.0`
