### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by oreo-lp** [open-mmlab/mmcv#821]
`ERROR: Command errored out with exit status 1:
     command: /home/lupeng/anaconda3/envs/open-mmlab/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sbvthk4m/mmcv-full_ed893921b56c478284273043bf71907f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sbvthk4m/mmcv-full_ed893921b56c478284273043bf71907f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-s1v5_js2
         cwd: /tmp/pip-install-sbvthk4m/mmcv-full_ed893921b56c478284273043bf71907f/
    Complete output (33 lines):
    WARNING: The repository located at pypi.douban.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.douban.com'.
    ERROR: Could not find a version that satisfies the requirement pytest-runner
    ERROR: No matching distribution found for pytest-runner
    Traceback (most recent call last):
      File "/home/lupeng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/home/lupeng/anaconda3/envs/open-mmlab/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/lupeng/anaconda3/envs/open-mmlab/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpyy9gs60l', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sbvthk4m/mmcv-full_ed893921b56c478284273043bf71907f/setup.py", line 304, in <module>
        zip_safe=False)
      File "/home/lupeng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/home/lupeng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/lupeng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/dist.py", line 689, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/lupeng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/__init__.py", line 768, in resolve
        replace_conflicting=replace_conflicting
      File "/home/lupeng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/home/lupeng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/home/lupeng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/dist.py", line 745, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/lupeng/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/home/lupeng/anaconda3/envs/open-mmlab/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpyy9gs60l', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
Command I ran: pip install mmcv-full
and my environment is :
python=3.7
torch=1.7.1
cuda=10.1
cudnn=8_8.0.5.39-1

**Comment by oreo-lp** [comment]
i have solved this problems:
my command: pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/index.html
reference: https://github.com/open-mmlab/mmcv#installation
