### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by wen-flow** [open-mmlab/mmcv#845]
import torch
from mmcv.ops import RoIAlign
roi_align = RoIAlign(output_size=(7, 7)).cuda()
feat = torch.randn([1, 3, 24, 24]).cuda()
roi = torch.tensor([[0., 0., 0., 1., 1.]], dtype=torch.float32).cuda()
ret = roi_align(feat, roi)
print(ret.shape)

Traceback (most recent call last):
File "test.py", line 6, in
ret = roi_align(feat, roi)
File "/home/wjc/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "/home/wjc/Documents/liuwenlong/mmaction2/mmcv/mmcv/ops/roi_align.py", line 212, in forward
self.sampling_ratio, self.pool_mode, self.aligned)
File "/home/wjc/Documents/liuwenlong/mmaction2/mmcv/mmcv/ops/roi_align.py", line 102, in forward
aligned=ctx.aligned)
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)

environment: ubuntu18.04, pytorch1.7.1 cuda10.1 cudatoolkit10.1 1080ti

**Comment by hellock** [comment]
Please refer to https://mmcv.readthedocs.io/en/latest/trouble_shooting.html.
