### ISSUE TITLE
Installation failed with RTX3090+PyTorch1.7.1+CUDA11.0

### ISSUE THREAD

**Issue by HzZHoO** [open-mmlab/mmcv#876]
Really need help for installation! Thanks!

My env:

- ubuntu18.04
- RTX3090
- Python3.7
- GCC 7.5.0
- CUDA11.0
- PyTorch1.7.1
- cudatoolkit11.0

Tried to install **mmcv-1.2.7**
Here's the error info:

`(/home/zhz/anaconda3/envs/mmdec) zhz@lab:~/data/codes/mmcv$ MMCV_WITH_OPS=1 pip install -vv -e . 
Using pip 21.0.1 from /home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-xj_ztalv
Created temporary directory: /tmp/pip-req-tracker-twzbt1hg
Initialized build tracking at /tmp/pip-req-tracker-twzbt1hg
Created build tracker: /tmp/pip-req-tracker-twzbt1hg
Entered build tracker: /tmp/pip-req-tracker-twzbt1hg
Created temporary directory: /tmp/pip-install-yx152mjd
Obtaining file:///home/zhz/data/codes/mmcv
  Added file:///home/zhz/data/codes/mmcv to build tracker '/tmp/pip-req-tracker-twzbt1hg'
    Running setup.py (path:/home/zhz/data/codes/mmcv/setup.py) egg_info for package from file:///home/zhz/data/codes/mmcv
    Created temporary directory: /tmp/pip-pip-egg-info-lml6k8cv
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-lml6k8cv/mmcv_full.egg-info
    writing /tmp/pip-pip-egg-info-lml6k8cv/mmcv_full.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-lml6k8cv/mmcv_full.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-lml6k8cv/mmcv_full.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-lml6k8cv/mmcv_full.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-lml6k8cv/mmcv_full.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-lml6k8cv/mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file '/tmp/pip-pip-egg-info-lml6k8cv/mmcv_full.egg-info/SOURCES.txt'
  Source in /home/zhz/data/codes/mmcv has version 1.2.7, which satisfies requirement mmcv-full==1.2.7 from file:///home/zhz/data/codes/mmcv
  Removed mmcv-full==1.2.7 from file:///home/zhz/data/codes/mmcv from build tracker '/tmp/pip-req-tracker-twzbt1hg'
Requirement already satisfied: addict in /home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages (from mmcv-full==1.2.7) (2.4.0)
Requirement already satisfied: numpy in /home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages (from mmcv-full==1.2.7) (1.19.2)
Requirement already satisfied: Pillow in /home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages (from mmcv-full==1.2.7) (8.1.1)
Requirement already satisfied: pyyaml in /home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages (from mmcv-full==1.2.7) (5.4.1)
Requirement already satisfied: yapf in /home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages (from mmcv-full==1.2.7) (0.30.0)
Created temporary directory: /tmp/pip-unpack-6ve63wx_
Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full
    Running command /home/zhz/anaconda3/envs/mmdec/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/zhz/data/codes/mmcv/setup.py'"'"'; __file__='"'"'/home/zhz/data/codes/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext' extension
    Emitting ninja build file /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Using envvar MAX_JOBS (4) as the number of workers...
    [1/38] :/usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/home/zhz/data/codes/mmcv/mmcv/ops/csrc -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/TH -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/zhz/anaconda3/envs/mmdec/include/python3.7m -c -c /home/zhz/data/codes/mmcv/mmcv/ops/csrc/pytorch/bbox_overlaps_cuda.cu -o /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/bbox_overlaps_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
    FAILED: /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/bbox_overlaps_cuda.o
    :/usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/home/zhz/data/codes/mmcv/mmcv/ops/csrc -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/TH -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/zhz/anaconda3/envs/mmdec/include/python3.7m -c -c /home/zhz/data/codes/mmcv/mmcv/ops/csrc/pytorch/bbox_overlaps_cuda.cu -o /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/bbox_overlaps_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
    /bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
    [2/38] :/usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/home/zhz/data/codes/mmcv/mmcv/ops/csrc -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/TH -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/zhz/anaconda3/envs/mmdec/include/python3.7m -c -c /home/zhz/data/codes/mmcv/mmcv/ops/csrc/pytorch/focal_loss_cuda.cu -o /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/focal_loss_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
    FAILED: /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/focal_loss_cuda.o
    :/usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/home/zhz/data/codes/mmcv/mmcv/ops/csrc -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/TH -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/zhz/anaconda3/envs/mmdec/include/python3.7m -c -c /home/zhz/data/codes/mmcv/mmcv/ops/csrc/pytorch/focal_loss_cuda.cu -o /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/focal_loss_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
    /bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
    [3/38] :/usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/home/zhz/data/codes/mmcv/mmcv/ops/csrc -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/TH -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/zhz/anaconda3/envs/mmdec/include/python3.7m -c -c /home/zhz/data/codes/mmcv/mmcv/ops/csrc/pytorch/roi_pool_cuda.cu -o /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/roi_pool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
    FAILED: /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/roi_pool_cuda.o
    :/usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/home/zhz/data/codes/mmcv/mmcv/ops/csrc -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/TH -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/zhz/anaconda3/envs/mmdec/include/python3.7m -c -c /home/zhz/data/codes/mmcv/mmcv/ops/csrc/pytorch/roi_pool_cuda.cu -o /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/roi_pool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
    /bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
    [4/38] :/usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/home/zhz/data/codes/mmcv/mmcv/ops/csrc -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/TH -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/zhz/anaconda3/envs/mmdec/include/python3.7m -c -c /home/zhz/data/codes/mmcv/mmcv/ops/csrc/pytorch/nms_rotated_cuda.cu -o /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
    FAILED: /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/nms_rotated_cuda.o
    :/usr/local/cuda/bin/nvcc -DMMCV_WITH_CUDA -I/home/zhz/data/codes/mmcv/mmcv/ops/csrc -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/TH -I/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/zhz/anaconda3/envs/mmdec/include/python3.7m -c -c /home/zhz/data/codes/mmcv/mmcv/ops/csrc/pytorch/nms_rotated_cuda.cu -o /home/zhz/data/codes/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
    /bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1539, in _run_ninja_build
        env=env)
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/zhz/data/codes/mmcv/setup.py", line 316, in <module>
        zip_safe=False)
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
        build_ext.build_extensions(self)
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 500, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
ERROR: Command errored out with exit status 1: /home/zhz/anaconda3/envs/mmdec/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/zhz/data/codes/mmcv/setup.py'"'"'; __file__='"'"'/home/zhz/data/codes/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 400, in run
    pycompile=options.compile,
  File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 88, in install_given_reqs
    pycompile=pycompile,
  File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 774, in install
    unpacked_source_directory=self.unpacked_source_directory,
  File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/pip/_internal/operations/install/editable_legacy.py", line 51, in install_editable
    cwd=unpacked_source_directory,
  File "/home/zhz/anaconda3/envs/mmdec/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 258, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /home/zhz/anaconda3/envs/mmdec/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/zhz/data/codes/mmcv/setup.py'"'"'; __file__='"'"'/home/zhz/data/codes/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-twzbt1hg'
`

**Comment by kali20gakki** [comment]
Hello. 
Have you solved the problem? We have the same problem, the same environment and the same hardware（RTX3090）.

**Comment by MaxLin86** [comment]
RTX3090+PyTorch1.8.1+CUDA11.1 
same problem

**Comment by zhouzaida** [comment]
@MaxLin86 , could you print `nvcc --version` in terminal?

**Comment by zhouzaida** [comment]
The issue of @HzZHoO  is `/bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found`

**Comment by MaxLin86** [comment]
> @MaxLin86 , could you print `nvcc --version` in terminal?

I can print 'nvcc --version' in bace env and virtual conda env.

But still '/bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found'

**Comment by MaxLin86** [comment]
By the way.
The compile was success in base env which python is 3.8.5, and without pytorch.

My virtual env which python is 3.6.13, pytorch1.8.1

**Comment by MaxLin86** [comment]
I just try python3.6.13+cuda11.1+pytorch1.8.0, 
then using "pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html" 

when debug 
`from mmdet.apis import init_detector, inference_detector

config_file = 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
# download the checkpoint from model zoo and put it in `checkpoints/`
# url: http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'
device = 'cuda:0'
# init a detector
model = init_detector(config_file, checkpoint_file, device=device)
# inference the demo image
inference_detector(model, 'demo/demo.jpg')`
it shows: RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by zhouzaida** [comment]
try to run `python -c "import torch;print(torch.max(torch.rand((30,30),device='cuda')))"`

**Comment by MaxLin86** [comment]
> try to run `python -c "import torch;print(torch.max(torch.rand((30,30),device='cuda')))"`

print result:  tensor(0.9998, device='cuda:0')

and the torch environment is tested to be OK.

the RuntimeError I just mentioned was occured in NMSop.

**Comment by zhouzaida** [comment]
@hhaAndroid

**Comment by MaxLin86** [comment]
> @hhaAndroid

The problem was solved. 
Finally env: RTX3090 + CUDA11.1 + conda virtual env python 3.6.13 + torch1.7.1+cu110 + ‘pip install mmcv-full==1.3.1 -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.0/index.html’
