### ISSUE TITLE
MMCV_WITH_OPS=1 pip install -e .

### ISSUE THREAD

**Issue by wd490755634** [open-mmlab/mmcv#973]
when i use    MMCV_WITH_OPS=1 pip install -e .

![image](https://user-images.githubusercontent.com/34602701/115515382-a96add80-a2b7-11eb-916f-938931f162c2.png)

Installing collected packages: mmcv
  Running setup.py develop for mmcv
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/data/mmcv-1.2.4/setup.py'"'"'; __file__='"'"'/root/data/mmcv-1.2.4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /root/data/mmcv-1.2.4/
    Complete output (52 lines):
    running develop
    running egg_info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/data/mmcv-1.2.4/setup.py", line 259, in <module>
        zip_safe=False)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/opt/conda/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
        build_ext.build_extensions(self)
      File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/conda/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
        cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
      File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 337, in unix_cuda_flags
        cflags + _get_cuda_arch_flags(cflags))
      File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1339, in _get_cuda_arch_flags
        raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
    ValueError: Unknown CUDA arch (8.0) or GPU not supported
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/data/mmcv-1.2.4/setup.py'"'"'; __file__='"'"'/root/data/mmcv-1.2.4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
====================================================================
  My CUDA Version: 11.2. Can I install successfully without changing the CUDA version?

**Comment by zhouzaida** [comment]
Maybe it is hard.

**Comment by lengmo1996** [comment]
Maybe you can try to update your driver version. 
Does your driver versions compatible with your CUDA version?
My CUDA version is 11.1 and the driver version is 450.80. It is satisfied the requirements in https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html, but still got a similar error with you. When I update my driver version to 460, it works.

**Comment by zhouzaida** [comment]
hi, @wd490755634 , has the issue been resolved?
